package au.com.shiftyjelly.pocketcasts.utils.featureflag

import au.com.shiftyjelly.pocketcasts.helper.BuildConfig
import java.time.LocalDate

private val isDebugOrPrototypeBuild = BuildConfig.DEBUG || BuildConfig.IS_PROTOTYPE

enum class Feature(
    val key: String,
    val title: String,
    val defaultValue: Boolean,
    val tier: FeatureTier,
    val hasFirebaseRemoteFlag: Boolean,
    val hasDevToggle: Boolean,
    val addedOn: LocalDate,
) {
    // This is a set of features used only for testing purposes.
    TEST_FREE_FEATURE(
        key = "test_free_feature",
        title = "Free feature used for testing",
        defaultValue = true,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2025-06-05"),
    ),
    TEST_PLUS_FEATURE(
        key = "test_plus_feature",
        title = "Plus feature used for testing",
        defaultValue = true,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = false,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2025-06-05"),
    ),
    TEST_PLUS_RESTRICTED_FEATURE(
        key = "test_plus_restricted_feature",
        title = "Plus feature with Patron exclusive access used for testing",
        defaultValue = true,
        tier = FeatureTier.Plus(ReleaseVersion(1, 0)),
        hasFirebaseRemoteFlag = false,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2025-06-05"),
    ),
    TEST_PATRON_FEATURE(
        key = "test_patron_feature",
        title = "Patron feature used for testing",
        defaultValue = true,
        tier = FeatureTier.Patron,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2025-06-05"),
    ),

    // Here are the feature flags used by the app
    SYNC_EOY_DATA_ON_STARTUP(
        key = "sync_eoy_data_on_startup",
        title = "Whether the End of Year data should be synced on startup",
        defaultValue = false,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2024-10-23"),
    ),
    END_OF_YEAR_2025(
        key = "end_of_year_2025",
        title = "End of Year 2025",
        defaultValue = false,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2025-10-27"),
    ),
    INTERCEPTOR_REFRESH_TOKEN_FALLBACK(
        key = "interceptor_refresh_token_fallback",
        title = "Interceptor refresh token fallback",
        defaultValue = true,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-06-01"),
    ),
    INTRO_PLUS_OFFER_ENABLED(
        key = "intro_plus_offer_enabled",
        title = "Intro Offer Plus",
        defaultValue = false,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2024-02-06"),
    ),
    SLUMBER_STUDIOS_YEARLY_PROMO(
        key = "slumber_studios_yearly_promo_code",
        title = "Slumber Studios Yearly Promo",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(null),
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2024-02-28"),
    ),
    EXPLAT_EXPERIMENT(
        key = "explat_experiment",
        title = "ExPlat Experiment",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2024-09-26"),
    ),
    ENGAGE_SDK(
        key = "engage_sdk",
        title = "Integrate Pocket Casts with Engage SDK",
        defaultValue = true,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = false,
        addedOn = LocalDate.parse("2024-08-20"),
    ),
    LIBRO_FM(
        key = "libro_fm",
        title = "Libro FM in Upsell",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-04-11"),
    ),
    RECOMMENDATIONS(
        key = "recommendations",
        title = "Recommendations",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-04-04"),
    ),
    NOTIFICATIONS_REVAMP(
        key = "notifications_revamp",
        title = "Notifications Revamp",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-04-03"),
    ),
    BANNER_ADS_PLAYER(
        key = "banner_ad_player",
        title = "Banner Ads Player",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-08-29"),
    ),
    BANNER_ADS_PODCASTS(
        key = "banner_ad_podcasts",
        title = "Banner Ads Podcasts",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-08-29"),
    ),
    IMPROVED_SEARCH_SUGGESTIONS(
        key = "search_predictive",
        title = "Predictive search suggestions",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-10-07"),
    ),
    IMPROVE_APP_RATINGS(
        key = "improve_app_ratings",
        title = "Banner prompting for app rating",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-11-05"),
    ),
    NEW_INSTALLMENT_PLAN(
        key = "new_installment_plan",
        title = "New Installment Plan",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-01-08"),
    ),

    MEDIA3_SESSION(
        key = "media3_session",
        title = "Media3 MediaSession",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-03-04"),
    ),
    NEXT_EPISODE_PREFETCH(
        key = "next_episode_prefetch",
        title = "Next Episode Prefetch",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-03-04"),
    ),
    LOAD_ERROR_HANDLING_POLICY(
        key = "load_error_handling_policy",
        title = "Custom load error handling policy for the player",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-03-13"),
    ),
    UP_NEXT_SYNC_PROTOBUF(
        key = "up_next_sync_protobuf",
        title = "Up Next sync with Protocol Buffers",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2025-12-18"),
    ),
    LIVE_ANALYTICS(
        key = "live_analytics",
        title = "Live analytics debugging",
        defaultValue = true,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-03-17"),
    ),
    PLAYBACK_ERROR_INFO_BAR(
        key = "display_errors_on_player",
        title = "Playback error info bar",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-03-31"),
    ),
    EXPLICIT_PODCAST_INDICATOR(
        key = "explicit_podcast_indicator",
        title = "Explicit podcast indicator",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-04-23"),
    ),
    IMPROVED_LISTENING_STATS(
        key = "improved_listening_stats",
        title = "Show improved listening stats",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-04-28"),
    ),
    BLOGS(
        key = "blogs",
        title = "Blogs into a podcast",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-04"),
    ),
    PROFILE_SHARING(
        key = "profile_sharing",
        title = "Profile sharing",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-12"),
    ),
    EPISODE_CHAT(
        key = "episode_chat",
        title = "Episode Chat",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-04-22"),
    ),
    EPISODE_CHAT_PLAYABLE_QUOTES(
        key = "episode_chat_playable_quotes",
        title = "Episode Chat: Playable Quotes",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-04-27"),
    ),
    AI_SUMMARIES(
        key = "ai_summaries",
        title = "AI Summaries",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-12"),
    ),
    GENERATED_CHAPTERS(
        key = "generated_chapters",
        title = "AI-Generated Chapters",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-12"),
    ),
    SYNCED_TRANSCRIPTS(
        key = "synced_transcripts",
        title = "Synced transcripts with playback timing",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-08"),
    ),
    SYNCED_TRANSCRIPT_DEBUG(
        key = "synced_transcript_debug",
        title = "Synced transcript debug timeline",
        defaultValue = false,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-29"),
    ),
    UP_NEXT_SORT(
        key = "up_next_sort",
        title = "Up Next sort by duration",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-06-09"),
    ),
    SMART_BOOKMARKS(
        key = "smart_bookmarks",
        title = "AI-enriched bookmarks with title and summary",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Plus(),
        hasFirebaseRemoteFlag = false,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-05-27"),
    ),
    HLS_STREAMING(
        key = "hls_streaming",
        title = "Prefer HLS stream when available",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-06-11"),
    ),
    STATS_HEATMAP(
        key = "stats_heatmap",
        title = "Show listening activity heatmap on Stats",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-07-02"),
    ),
    INTERRUPTION_REWIND(
        key = "interruption_rewind",
        title = "Rewind after audio interruptions like calls and navigation",
        defaultValue = isDebugOrPrototypeBuild,
        tier = FeatureTier.Free,
        hasFirebaseRemoteFlag = true,
        hasDevToggle = true,
        addedOn = LocalDate.parse("2026-07-19"),
    ),
}

sealed class FeatureTier {
    data object Free : FeatureTier()

    class Plus(
        val patronExclusiveAccessRelease: ReleaseVersion? = null,
    ) : FeatureTier()

    data object Patron : FeatureTier()
}
