# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: Gradle Wrapper Validation
    command: validate_gradle_wrapper
    agents:
      queue: linter

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - group: "📲 Prototype Builds"
    steps:
      - label: ":android: No CC Build"
        command: |
          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :closed_lock_with_key: Installing Secrets"
          bundle exec fastlane run configure_apply

          echo "--- :android: Building without configuration cache"
          ./gradlew assembleDebug --no-configuration-cache --no-build-cache
        plugins: [$CI_TOOLKIT]

      - label: ":android: CC Build"
        command: |
          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :closed_lock_with_key: Installing Secrets"
          bundle exec fastlane run configure_apply

          echo "--- :android: Building without configuration cache"
          ./gradlew assembleDebug --no-build-cache
        plugins: [$CI_TOOLKIT]
