# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - group: "Linters"
    steps:
      - label: "☢️ Danger - PR Check"
        command: danger
        key: danger
        if: "build.pull_request.id != null"
        retry:
          manual:
            permit_on_passed: true
        agents:
          queue: "linter"

      - label: 'Lint'
        command: |
          echo "--- 🧹 Linting"
          ./gradlew lintDebug
        plugins: [$CI_TOOLKIT]
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  - label: 'Unit tests'
    command: |
      echo "--- 🧪 Testing"
      ./gradlew testDebugUnitTest
    plugins: [$CI_TOOLKIT]

  - label: 'Spotless formatting check'
    command: |
      echo "--- 🔎 Checking formatting with Spotless"
      ./gradlew spotlessCheck
    plugins: [$CI_TOOLKIT]

  - label: "Instrumented tests"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems
      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply
      echo "--- 🧪 Testing"
      bundle exec fastlane build_and_instrumented_test
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/instrumented-tests/**/*"

  - label: "Assemble release APK"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems
      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply
      echo "--- ⚙️ Building release variant"
      ./gradlew assembleRelease -PskipSentryProguardMappingUpload=true
    plugins: [ $CI_TOOLKIT ]
    artifact_paths:
      - "**/build/outputs/apk/**/*"

  - label: "Prototype Builds"
    if: "build.pull_request.id != null"
    command: |
      ".buildkite/commands/prototype-build.sh"
    plugins: [ $CI_TOOLKIT ]
    artifact_paths:
      - "**/build/outputs/apk/**/*"
