# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - group: "Linters"
    steps:
      - label: "☢️ Danger - PR Check"
        command: .buildkite/commands/danger-pr-check.sh
        plugins:
          - docker#v5.8.0:
              image: "public.ecr.aws/docker/library/ruby:3.2.2"
              propagate-environment: true
              environment:
                - "DANGER_GITHUB_API_TOKEN"
        if: "build.pull_request.id != null"
        agents:
          queue: "default"
        retry:
          manual:
            permit_on_passed: true

      - label: 'Lint'
        command: |
          echo "--- 🧹 Linting"
          ./gradlew lintDebug
        plugins: *common_plugins
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  - label: 'Unit tests'
    command: |
      echo "--- 🧪 Testing"
      ./gradlew testDebugUnitTest
    plugins: *common_plugins

  - label: 'Spotless formatting check'
    command: |
      echo "--- 🔎 Checking formatting with Spotless"
      ./gradlew spotlessCheck
    plugins: *common_plugins

  - label: "Instrumented tests"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems
      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply
      echo "--- 🧪 Testing"
      bundle exec fastlane build_and_instrumented_test
    plugins: *common_plugins
    artifact_paths:
      - "**/build/instrumented-tests/**/*"
