# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: Gradle Wrapper Validation
    command: validate_gradle_wrapper
    agents:
      queue: linter

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Get inputs"
    if: "build.pull_request.id != null"
    command: |
      ".buildkite/commands/prototype-build.sh"
    plugins: [ $CI_TOOLKIT ]
    artifact_paths:
      - "**/build/*-task-inputs**.*"
