# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.6.0

steps:
  - label: 'Unit tests'
    command: |
      echo "--- 🧪 Testing"
      ./gradlew testDebugUnitTest
    plugins: *common_plugins

  - label: 'Lint'
    command: |
      echo "--- 🧹 Linting"
      ./gradlew lintDebug
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/lint-results*.*"
