# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android-staging"

steps:
  - label: Gradle Wrapper Validation
    command: validate_gradle_wrapper
    agents:
      queue: linter

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - group: "Linters"
    steps:
      - label: "☢️ Danger - PR Check"
        command: danger
        key: danger
        if: "build.pull_request.id != null"
        retry:
          manual:
            permit_on_passed: true
        agents:
          queue: "linter"

      - label: 'Lint'
        command: ".buildkite/commands/lint.sh"
        plugins: [$CI_TOOLKIT]
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  - label: 'Unit tests'
    command: ".buildkite/commands/run-unit-tests.sh"
    plugins: [$CI_TOOLKIT]

  - label: 'Dependency diff'
    if: build.pull_request.id != null
    command: comment_with_dependency_diff 'app' 'releaseRuntimeClasspath'
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/reports/diff/*"

  - label: 'Spotless formatting check'
    command: |
      echo "--- 🔎 Checking formatting with Spotless"
      ./gradlew spotlessCheck
    plugins: [$CI_TOOLKIT]

  - label: "Instrumented tests"
    command: ".buildkite/commands/run-instrumented-tests.sh"
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/instrumented-tests/**/*"

  - label: "Assemble release APK"
    command: ".buildkite/commands/assemble-release-apk.sh"
    plugins: [ $CI_TOOLKIT ]
    artifact_paths:
      - "**/build/outputs/apk/**/*"

  - label: "Prototype Builds"
    if: "build.pull_request.id != null"
    command: |
      ".buildkite/commands/prototype-build.sh"
    plugins: [ $CI_TOOLKIT ]
    artifact_paths:
      - "**/build/outputs/apk/**/*"
