# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:

  - group: "Diff Reports"
    steps:
      - label: "Merged Manifest Diff"
        command: ".buildkite/commands/diff-merged-manifest.sh release"
        if: build.pull_request.id != null
        plugins: [$CI_TOOLKIT]
        artifact_paths:
          - "**/build/reports/diff_manifest/**/**/*"
