# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "🛠 Assemble with CC [No Build Cache]"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply

      echo "--- 🛠 Build with CC [No Build Cache]"
      ./gradlew assembleDebug --no-build-cache
    plugins: [ $CI_TOOLKIT ]

  - label: "🛠 Assemble without CC [No Build Cache]"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply

      echo "--- 🛠 Build without CC [No Build Cache]"
      ./gradlew assembleDebug --no-build-cache --no-configuration-cache
    plugins: [ $CI_TOOLKIT ]
