name: ✨ New enhancement
description: If you have a suggestion to improve an existing feature in the Android app please let us know.
labels: ["[Type] Enhancement"]
body:

  - type: markdown
    attributes:
      value: |
        _Thanks for taking the time to send us your idea!_

  - type: textarea
    attributes:
      label: Description
      description: Please describe the enhancement you're suggesting, including the current behavior and how you envision the improvement.
      placeholder: |
        I'd like to improve '...' by adding/enhancing '...', so that '...' happens instead.”
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots or screen recording
      description: |
        Help us see what you see! Please upload a screenshot or screen recording, to help explain the improvement.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Did you search for existing list?
      description: Please confirm that you searched for existing suggestion in https://github.com/Automattic/pocket-casts-android/issues before opening this issue.
      options:
        - label: I have searched for existing issues.
          required: true
