name: Feature suggestion
description: Propose a feature in the Pocket Casts Android app
labels: ["feature", "triage"]
body:

    - type: markdown
      attributes:
          value: |
              _Thanks for taking the time to suggest a feature!_

    - type: textarea
      attributes:
          label: What problem does this address?
          description: |
              Please describe if this feature or enhancement is related to a current problem or pain point. For example, "I'm always frustrated when ..." or "It is currently difficult to ...".
      validations:
          required: true

    - type: textarea
      attributes:
          label: What is your proposed solution?
          description: |
              Please outline the feature or enhancement that you want and how it addresses the problem identified above.
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Did you search for existing feature suggestions?
          description: Please confirm that you searched for existing feature suggestions in https://github.com/Automattic/pocket-casts-android/issues before opening this issue.
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true

