// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface ApiPodcastListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ApiPodcastListResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .api.ApiPodcastResponse podcasts = 1;</code>
   */
  java.util.List<com.pocketcasts.service.api.ApiPodcastResponse> 
      getPodcastsList();
  /**
   * <code>repeated .api.ApiPodcastResponse podcasts = 1;</code>
   */
  com.pocketcasts.service.api.ApiPodcastResponse getPodcasts(int index);
  /**
   * <code>repeated .api.ApiPodcastResponse podcasts = 1;</code>
   */
  int getPodcastsCount();
}
