// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.EpisodeSyncResponse}
 */
public  final class EpisodeSyncResponse extends
    com.google.protobuf.GeneratedMessageLite<
        EpisodeSyncResponse, EpisodeSyncResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.EpisodeSyncResponse)
    EpisodeSyncResponseOrBuilder {
  private EpisodeSyncResponse() {
    uuid_ = "";
    bookmarks_ = emptyProtobufList();
  }
  public static final int UUID_FIELD_NUMBER = 1;
  private java.lang.String uuid_;
  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    return uuid_;
  }
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uuid_);
  }
  /**
   * <code>string uuid = 1;</code>
   * @param value The uuid to set.
   */
  private void setUuid(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    uuid_ = value;
  }
  /**
   * <code>string uuid = 1;</code>
   */
  private void clearUuid() {

    uuid_ = getDefaultInstance().getUuid();
  }
  /**
   * <code>string uuid = 1;</code>
   * @param value The bytes for uuid to set.
   */
  private void setUuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uuid_ = value.toStringUtf8();

  }

  public static final int PLAYING_STATUS_FIELD_NUMBER = 2;
  private int playingStatus_;
  /**
   * <code>int32 playing_status = 2;</code>
   * @return The playingStatus.
   */
  @java.lang.Override
  public int getPlayingStatus() {
    return playingStatus_;
  }
  /**
   * <code>int32 playing_status = 2;</code>
   * @param value The playingStatus to set.
   */
  private void setPlayingStatus(int value) {
    
    playingStatus_ = value;
  }
  /**
   * <code>int32 playing_status = 2;</code>
   */
  private void clearPlayingStatus() {

    playingStatus_ = 0;
  }

  public static final int PLAYED_UP_TO_FIELD_NUMBER = 3;
  private int playedUpTo_;
  /**
   * <code>int32 played_up_to = 3;</code>
   * @return The playedUpTo.
   */
  @java.lang.Override
  public int getPlayedUpTo() {
    return playedUpTo_;
  }
  /**
   * <code>int32 played_up_to = 3;</code>
   * @param value The playedUpTo to set.
   */
  private void setPlayedUpTo(int value) {
    
    playedUpTo_ = value;
  }
  /**
   * <code>int32 played_up_to = 3;</code>
   */
  private void clearPlayedUpTo() {

    playedUpTo_ = 0;
  }

  public static final int IS_DELETED_FIELD_NUMBER = 4;
  private boolean isDeleted_;
  /**
   * <code>bool is_deleted = 4;</code>
   * @return The isDeleted.
   */
  @java.lang.Override
  public boolean getIsDeleted() {
    return isDeleted_;
  }
  /**
   * <code>bool is_deleted = 4;</code>
   * @param value The isDeleted to set.
   */
  private void setIsDeleted(boolean value) {
    
    isDeleted_ = value;
  }
  /**
   * <code>bool is_deleted = 4;</code>
   */
  private void clearIsDeleted() {

    isDeleted_ = false;
  }

  public static final int STARRED_FIELD_NUMBER = 5;
  private boolean starred_;
  /**
   * <code>bool starred = 5;</code>
   * @return The starred.
   */
  @java.lang.Override
  public boolean getStarred() {
    return starred_;
  }
  /**
   * <code>bool starred = 5;</code>
   * @param value The starred to set.
   */
  private void setStarred(boolean value) {
    
    starred_ = value;
  }
  /**
   * <code>bool starred = 5;</code>
   */
  private void clearStarred() {

    starred_ = false;
  }

  public static final int DURATION_FIELD_NUMBER = 6;
  private int duration_;
  /**
   * <code>int32 duration = 6;</code>
   * @return The duration.
   */
  @java.lang.Override
  public int getDuration() {
    return duration_;
  }
  /**
   * <code>int32 duration = 6;</code>
   * @param value The duration to set.
   */
  private void setDuration(int value) {
    
    duration_ = value;
  }
  /**
   * <code>int32 duration = 6;</code>
   */
  private void clearDuration() {

    duration_ = 0;
  }

  public static final int BOOKMARKS_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.BookmarkResponse> bookmarks_;
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.pocketcasts.service.api.BookmarkResponse> getBookmarksList() {
    return bookmarks_;
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  public java.util.List<? extends com.pocketcasts.service.api.BookmarkResponseOrBuilder> 
      getBookmarksOrBuilderList() {
    return bookmarks_;
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  @java.lang.Override
  public int getBookmarksCount() {
    return bookmarks_.size();
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BookmarkResponse getBookmarks(int index) {
    return bookmarks_.get(index);
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  public com.pocketcasts.service.api.BookmarkResponseOrBuilder getBookmarksOrBuilder(
      int index) {
    return bookmarks_.get(index);
  }
  private void ensureBookmarksIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.BookmarkResponse> tmp = bookmarks_;
    if (!tmp.isModifiable()) {
      bookmarks_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void setBookmarks(
      int index, com.pocketcasts.service.api.BookmarkResponse value) {
    value.getClass();
  ensureBookmarksIsMutable();
    bookmarks_.set(index, value);
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void addBookmarks(com.pocketcasts.service.api.BookmarkResponse value) {
    value.getClass();
  ensureBookmarksIsMutable();
    bookmarks_.add(value);
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void addBookmarks(
      int index, com.pocketcasts.service.api.BookmarkResponse value) {
    value.getClass();
  ensureBookmarksIsMutable();
    bookmarks_.add(index, value);
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void addAllBookmarks(
      java.lang.Iterable<? extends com.pocketcasts.service.api.BookmarkResponse> values) {
    ensureBookmarksIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, bookmarks_);
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void clearBookmarks() {
    bookmarks_ = emptyProtobufList();
  }
  /**
   * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
   */
  private void removeBookmarks(int index) {
    ensureBookmarksIsMutable();
    bookmarks_.remove(index);
  }

  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.EpisodeSyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.EpisodeSyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.EpisodeSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.EpisodeSyncResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.EpisodeSyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.EpisodeSyncResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.EpisodeSyncResponse)
      com.pocketcasts.service.api.EpisodeSyncResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.EpisodeSyncResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      return instance.getUuid();
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      return instance.getUuidBytes();
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setUuid(value);
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      copyOnWrite();
      instance.clearUuid();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUuidBytes(value);
      return this;
    }

    /**
     * <code>int32 playing_status = 2;</code>
     * @return The playingStatus.
     */
    @java.lang.Override
    public int getPlayingStatus() {
      return instance.getPlayingStatus();
    }
    /**
     * <code>int32 playing_status = 2;</code>
     * @param value The playingStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPlayingStatus(int value) {
      copyOnWrite();
      instance.setPlayingStatus(value);
      return this;
    }
    /**
     * <code>int32 playing_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayingStatus() {
      copyOnWrite();
      instance.clearPlayingStatus();
      return this;
    }

    /**
     * <code>int32 played_up_to = 3;</code>
     * @return The playedUpTo.
     */
    @java.lang.Override
    public int getPlayedUpTo() {
      return instance.getPlayedUpTo();
    }
    /**
     * <code>int32 played_up_to = 3;</code>
     * @param value The playedUpTo to set.
     * @return This builder for chaining.
     */
    public Builder setPlayedUpTo(int value) {
      copyOnWrite();
      instance.setPlayedUpTo(value);
      return this;
    }
    /**
     * <code>int32 played_up_to = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayedUpTo() {
      copyOnWrite();
      instance.clearPlayedUpTo();
      return this;
    }

    /**
     * <code>bool is_deleted = 4;</code>
     * @return The isDeleted.
     */
    @java.lang.Override
    public boolean getIsDeleted() {
      return instance.getIsDeleted();
    }
    /**
     * <code>bool is_deleted = 4;</code>
     * @param value The isDeleted to set.
     * @return This builder for chaining.
     */
    public Builder setIsDeleted(boolean value) {
      copyOnWrite();
      instance.setIsDeleted(value);
      return this;
    }
    /**
     * <code>bool is_deleted = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDeleted() {
      copyOnWrite();
      instance.clearIsDeleted();
      return this;
    }

    /**
     * <code>bool starred = 5;</code>
     * @return The starred.
     */
    @java.lang.Override
    public boolean getStarred() {
      return instance.getStarred();
    }
    /**
     * <code>bool starred = 5;</code>
     * @param value The starred to set.
     * @return This builder for chaining.
     */
    public Builder setStarred(boolean value) {
      copyOnWrite();
      instance.setStarred(value);
      return this;
    }
    /**
     * <code>bool starred = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStarred() {
      copyOnWrite();
      instance.clearStarred();
      return this;
    }

    /**
     * <code>int32 duration = 6;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>int32 duration = 6;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(int value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>int32 duration = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.pocketcasts.service.api.BookmarkResponse> getBookmarksList() {
      return java.util.Collections.unmodifiableList(
          instance.getBookmarksList());
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    @java.lang.Override
    public int getBookmarksCount() {
      return instance.getBookmarksCount();
    }/**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BookmarkResponse getBookmarks(int index) {
      return instance.getBookmarks(index);
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder setBookmarks(
        int index, com.pocketcasts.service.api.BookmarkResponse value) {
      copyOnWrite();
      instance.setBookmarks(index, value);
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder setBookmarks(
        int index, com.pocketcasts.service.api.BookmarkResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setBookmarks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder addBookmarks(com.pocketcasts.service.api.BookmarkResponse value) {
      copyOnWrite();
      instance.addBookmarks(value);
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder addBookmarks(
        int index, com.pocketcasts.service.api.BookmarkResponse value) {
      copyOnWrite();
      instance.addBookmarks(index, value);
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder addBookmarks(
        com.pocketcasts.service.api.BookmarkResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addBookmarks(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder addBookmarks(
        int index, com.pocketcasts.service.api.BookmarkResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addBookmarks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder addAllBookmarks(
        java.lang.Iterable<? extends com.pocketcasts.service.api.BookmarkResponse> values) {
      copyOnWrite();
      instance.addAllBookmarks(values);
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder clearBookmarks() {
      copyOnWrite();
      instance.clearBookmarks();
      return this;
    }
    /**
     * <code>repeated .api.BookmarkResponse bookmarks = 7;</code>
     */
    public Builder removeBookmarks(int index) {
      copyOnWrite();
      instance.removeBookmarks(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.EpisodeSyncResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.EpisodeSyncResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "uuid_",
            "playingStatus_",
            "playedUpTo_",
            "isDeleted_",
            "starred_",
            "duration_",
            "bookmarks_",
            com.pocketcasts.service.api.BookmarkResponse.class,
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\u0004\u0004\u0007\u0005\u0007\u0006\u0004\u0007\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.EpisodeSyncResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.EpisodeSyncResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.EpisodeSyncResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.EpisodeSyncResponse)
  private static final com.pocketcasts.service.api.EpisodeSyncResponse DEFAULT_INSTANCE;
  static {
    EpisodeSyncResponse defaultInstance = new EpisodeSyncResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EpisodeSyncResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.EpisodeSyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EpisodeSyncResponse> PARSER;

  public static com.google.protobuf.Parser<EpisodeSyncResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

