// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializeepisodesResponse")
public inline fun episodesResponse(block: com.pocketcasts.service.api.EpisodesResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.EpisodesResponse =
    com.pocketcasts.service.api.EpisodesResponseKt.Dsl._create(com.pocketcasts.service.api.EpisodesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.EpisodesResponse`
 */
public object EpisodesResponseKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.EpisodesResponse.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.EpisodesResponse.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.EpisodesResponse = _builder.build()

        /**
         * <code>int32 total = 1;</code>
         */
        public var total: kotlin.Int
            @JvmName("getTotal")
            get() = _builder.getTotal()
            @JvmName("setTotal")
            set(value) {
                _builder.setTotal(value)
            }
        /**
         * `int32 total = 1;`
         */
        public fun clearTotal() {
            _builder.clearTotal()
        }

        /**
         * An uninstantiable, behaviorless type to represent the field in
         * generics.
         */
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        public class EpisodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         */
        public val episodes: com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>
            @kotlin.jvm.JvmSynthetic
            get() = com.google.protobuf.kotlin.DslList(
                _builder.getEpisodesList()
            )
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         * @param value The episodes to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addEpisodes")
        public fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.add(value: com.pocketcasts.service.api.EpisodeResponse) {
            _builder.addEpisodes(value)
        }
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         * @param value The episodes to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignEpisodes")
        @Suppress("NOTHING_TO_INLINE")
        public inline operator fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.plusAssign(value: com.pocketcasts.service.api.EpisodeResponse) {
            add(value)
        }
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         * @param values The episodes to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addAllEpisodes")
        public fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.addAll(values: kotlin.collections.Iterable<com.pocketcasts.service.api.EpisodeResponse>) {
            _builder.addAllEpisodes(values)
        }
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         * @param values The episodes to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignAllEpisodes")
        @Suppress("NOTHING_TO_INLINE")
        public inline operator fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.plusAssign(values: kotlin.collections.Iterable<com.pocketcasts.service.api.EpisodeResponse>) {
            addAll(values)
        }
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         * @param index The index to set the value at.
         * @param value The episodes to set.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("setEpisodes")
        public operator fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.set(index: kotlin.Int, value: com.pocketcasts.service.api.EpisodeResponse) {
            _builder.setEpisodes(index, value)
        }
        /**
         * `repeated .api.EpisodeResponse episodes = 2;`
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("clearEpisodes")
        public fun com.google.protobuf.kotlin.DslList<com.pocketcasts.service.api.EpisodeResponse, EpisodesProxy>.clear() {
            _builder.clearEpisodes()
        }
    }
}
public inline fun com.pocketcasts.service.api.EpisodesResponse.copy(block: com.pocketcasts.service.api.EpisodesResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.EpisodesResponse =
    com.pocketcasts.service.api.EpisodesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
