// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface EpisodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.EpisodesResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 total = 1;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <code>repeated .api.EpisodeResponse episodes = 2;</code>
   */
  java.util.List<com.pocketcasts.service.api.EpisodeResponse> 
      getEpisodesList();
  /**
   * <code>repeated .api.EpisodeResponse episodes = 2;</code>
   */
  com.pocketcasts.service.api.EpisodeResponse getEpisodes(int index);
  /**
   * <code>repeated .api.EpisodeResponse episodes = 2;</code>
   */
  int getEpisodesCount();
}
