// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializefindUserEpisodesRequest")
public inline fun findUserEpisodesRequest(block: com.pocketcasts.service.api.FindUserEpisodesRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.FindUserEpisodesRequest =
    com.pocketcasts.service.api.FindUserEpisodesRequestKt.Dsl._create(com.pocketcasts.service.api.FindUserEpisodesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.FindUserEpisodesRequest`
 */
public object FindUserEpisodesRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.FindUserEpisodesRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.FindUserEpisodesRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.FindUserEpisodesRequest = _builder.build()

        /**
         * `string podcast_uuid = 1;`
         */
        public var podcastUuid: kotlin.String
            @JvmName("getPodcastUuid")
            get() = _builder.getPodcastUuid()
            @JvmName("setPodcastUuid")
            set(value) {
                _builder.setPodcastUuid(value)
            }
        /**
         * `string podcast_uuid = 1;`
         */
        public fun clearPodcastUuid() {
            _builder.clearPodcastUuid()
        }

        /**
         * <code>int32 page = 2;</code>
         */
        public var page: kotlin.Int
            @JvmName("getPage")
            get() = _builder.getPage()
            @JvmName("setPage")
            set(value) {
                _builder.setPage(value)
            }
        /**
         * `int32 page = 2;`
         */
        public fun clearPage() {
            _builder.clearPage()
        }

        /**
         * <code>int32 sort = 3;</code>
         */
        public var sort: kotlin.Int
            @JvmName("getSort")
            get() = _builder.getSort()
            @JvmName("setSort")
            set(value) {
                _builder.setSort(value)
            }
        /**
         * `int32 sort = 3;`
         */
        public fun clearSort() {
            _builder.clearSort()
        }

        /**
         * `string v = 4;`
         */
        public var v: kotlin.String
            @JvmName("getV")
            get() = _builder.getV()
            @JvmName("setV")
            set(value) {
                _builder.setV(value)
            }
        /**
         * `string v = 4;`
         */
        public fun clearV() {
            _builder.clearV()
        }

        /**
         * `string m = 5;`
         */
        public var m: kotlin.String
            @JvmName("getM")
            get() = _builder.getM()
            @JvmName("setM")
            set(value) {
                _builder.setM(value)
            }
        /**
         * `string m = 5;`
         */
        public fun clearM() {
            _builder.clearM()
        }
    }
}
public inline fun com.pocketcasts.service.api.FindUserEpisodesRequest.copy(block: com.pocketcasts.service.api.FindUserEpisodesRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.FindUserEpisodesRequest =
    com.pocketcasts.service.api.FindUserEpisodesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
