// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface HistoryChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HistoryChange)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 action = 1;</code>
   * @return The action.
   */
  int getAction();

  /**
   * <code>string podcast = 2;</code>
   * @return The podcast.
   */
  java.lang.String getPodcast();
  /**
   * <code>string podcast = 2;</code>
   * @return The bytes for podcast.
   */
  com.google.protobuf.ByteString
      getPodcastBytes();

  /**
   * <code>string episode = 3;</code>
   * @return The episode.
   */
  java.lang.String getEpisode();
  /**
   * <code>string episode = 3;</code>
   * @return The bytes for episode.
   */
  com.google.protobuf.ByteString
      getEpisodeBytes();

  /**
   * <code>int64 modified_at = 4;</code>
   * @return The modifiedAt.
   */
  long getModifiedAt();

  /**
   * <code>string title = 5;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 5;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string url = 6;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 6;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>.google.protobuf.Timestamp published = 7;</code>
   * @return Whether the published field is set.
   */
  boolean hasPublished();
  /**
   * <code>.google.protobuf.Timestamp published = 7;</code>
   * @return The published.
   */
  com.google.protobuf.Timestamp getPublished();
}
