// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface HistorySyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HistorySyncRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 device_time = 1;</code>
   * @return The deviceTime.
   */
  long getDeviceTime();

  /**
   * <code>int64 server_modified = 2;</code>
   * @return The serverModified.
   */
  long getServerModified();

  /**
   * <code>repeated .api.HistoryChange changes = 3;</code>
   */
  java.util.List<com.pocketcasts.service.api.HistoryChange> 
      getChangesList();
  /**
   * <code>repeated .api.HistoryChange changes = 3;</code>
   */
  com.pocketcasts.service.api.HistoryChange getChanges(int index);
  /**
   * <code>repeated .api.HistoryChange changes = 3;</code>
   */
  int getChangesCount();

  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
