// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.LegacySyncData}
 */
public  final class LegacySyncData extends
    com.google.protobuf.GeneratedMessageLite<
        LegacySyncData, LegacySyncData.Builder> implements
    // @@protoc_insertion_point(message_implements:api.LegacySyncData)
    LegacySyncDataOrBuilder {
  private LegacySyncData() {
    records_ = emptyProtobufList();
  }
  public static final int RECORDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.LegacySyncRecord> records_;
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.pocketcasts.service.api.LegacySyncRecord> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  public java.util.List<? extends com.pocketcasts.service.api.LegacySyncRecordOrBuilder> 
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  @java.lang.Override
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.LegacySyncRecord getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  public com.pocketcasts.service.api.LegacySyncRecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }
  private void ensureRecordsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.LegacySyncRecord> tmp = records_;
    if (!tmp.isModifiable()) {
      records_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void setRecords(
      int index, com.pocketcasts.service.api.LegacySyncRecord value) {
    value.getClass();
  ensureRecordsIsMutable();
    records_.set(index, value);
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void addRecords(com.pocketcasts.service.api.LegacySyncRecord value) {
    value.getClass();
  ensureRecordsIsMutable();
    records_.add(value);
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void addRecords(
      int index, com.pocketcasts.service.api.LegacySyncRecord value) {
    value.getClass();
  ensureRecordsIsMutable();
    records_.add(index, value);
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void addAllRecords(
      java.lang.Iterable<? extends com.pocketcasts.service.api.LegacySyncRecord> values) {
    ensureRecordsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, records_);
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void clearRecords() {
    records_ = emptyProtobufList();
  }
  /**
   * <code>repeated .api.LegacySyncRecord records = 4;</code>
   */
  private void removeRecords(int index) {
    ensureRecordsIsMutable();
    records_.remove(index);
  }

  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.LegacySyncData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.LegacySyncData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.LegacySyncData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.LegacySyncData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.LegacySyncData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.LegacySyncData, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.LegacySyncData)
      com.pocketcasts.service.api.LegacySyncDataOrBuilder {
    // Construct using com.pocketcasts.service.api.LegacySyncData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.pocketcasts.service.api.LegacySyncRecord> getRecordsList() {
      return java.util.Collections.unmodifiableList(
          instance.getRecordsList());
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    @java.lang.Override
    public int getRecordsCount() {
      return instance.getRecordsCount();
    }/**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.LegacySyncRecord getRecords(int index) {
      return instance.getRecords(index);
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder setRecords(
        int index, com.pocketcasts.service.api.LegacySyncRecord value) {
      copyOnWrite();
      instance.setRecords(index, value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder setRecords(
        int index, com.pocketcasts.service.api.LegacySyncRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setRecords(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder addRecords(com.pocketcasts.service.api.LegacySyncRecord value) {
      copyOnWrite();
      instance.addRecords(value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder addRecords(
        int index, com.pocketcasts.service.api.LegacySyncRecord value) {
      copyOnWrite();
      instance.addRecords(index, value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder addRecords(
        com.pocketcasts.service.api.LegacySyncRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addRecords(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder addRecords(
        int index, com.pocketcasts.service.api.LegacySyncRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addRecords(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends com.pocketcasts.service.api.LegacySyncRecord> values) {
      copyOnWrite();
      instance.addAllRecords(values);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder clearRecords() {
      copyOnWrite();
      instance.clearRecords();
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncRecord records = 4;</code>
     */
    public Builder removeRecords(int index) {
      copyOnWrite();
      instance.removeRecords(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.LegacySyncData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.LegacySyncData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "records_",
            com.pocketcasts.service.api.LegacySyncRecord.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0004\u0004\u0001\u0000\u0001\u0000\u0004\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.LegacySyncData> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.LegacySyncData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.LegacySyncData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.LegacySyncData)
  private static final com.pocketcasts.service.api.LegacySyncData DEFAULT_INSTANCE;
  static {
    LegacySyncData defaultInstance = new LegacySyncData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LegacySyncData.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.LegacySyncData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LegacySyncData> PARSER;

  public static com.google.protobuf.Parser<LegacySyncData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

