// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.LegacySyncResponse}
 */
public  final class LegacySyncResponse extends
    com.google.protobuf.GeneratedMessageLite<
        LegacySyncResponse, LegacySyncResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.LegacySyncResponse)
    LegacySyncResponseOrBuilder {
  private LegacySyncResponse() {
    lastModified_ = "";
    changes_ = emptyProtobufList();
  }
  public static final int LAST_MODIFIED_FIELD_NUMBER = 1;
  private java.lang.String lastModified_;
  /**
   * <code>string last_modified = 1;</code>
   * @return The lastModified.
   */
  @java.lang.Override
  public java.lang.String getLastModified() {
    return lastModified_;
  }
  /**
   * <code>string last_modified = 1;</code>
   * @return The bytes for lastModified.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastModifiedBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lastModified_);
  }
  /**
   * <code>string last_modified = 1;</code>
   * @param value The lastModified to set.
   */
  private void setLastModified(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    lastModified_ = value;
  }
  /**
   * <code>string last_modified = 1;</code>
   */
  private void clearLastModified() {

    lastModified_ = getDefaultInstance().getLastModified();
  }
  /**
   * <code>string last_modified = 1;</code>
   * @param value The bytes for lastModified to set.
   */
  private void setLastModifiedBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lastModified_ = value.toStringUtf8();

  }

  public static final int CHANGES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.LegacySyncResponseRecord> changes_;
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.pocketcasts.service.api.LegacySyncResponseRecord> getChangesList() {
    return changes_;
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  public java.util.List<? extends com.pocketcasts.service.api.LegacySyncResponseRecordOrBuilder> 
      getChangesOrBuilderList() {
    return changes_;
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  @java.lang.Override
  public int getChangesCount() {
    return changes_.size();
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.LegacySyncResponseRecord getChanges(int index) {
    return changes_.get(index);
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  public com.pocketcasts.service.api.LegacySyncResponseRecordOrBuilder getChangesOrBuilder(
      int index) {
    return changes_.get(index);
  }
  private void ensureChangesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.LegacySyncResponseRecord> tmp = changes_;
    if (!tmp.isModifiable()) {
      changes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void setChanges(
      int index, com.pocketcasts.service.api.LegacySyncResponseRecord value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.set(index, value);
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void addChanges(com.pocketcasts.service.api.LegacySyncResponseRecord value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.add(value);
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void addChanges(
      int index, com.pocketcasts.service.api.LegacySyncResponseRecord value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.add(index, value);
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void addAllChanges(
      java.lang.Iterable<? extends com.pocketcasts.service.api.LegacySyncResponseRecord> values) {
    ensureChangesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, changes_);
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void clearChanges() {
    changes_ = emptyProtobufList();
  }
  /**
   * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
   */
  private void removeChanges(int index) {
    ensureChangesIsMutable();
    changes_.remove(index);
  }

  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.LegacySyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.LegacySyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.LegacySyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.LegacySyncResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.LegacySyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.LegacySyncResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.LegacySyncResponse)
      com.pocketcasts.service.api.LegacySyncResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.LegacySyncResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string last_modified = 1;</code>
     * @return The lastModified.
     */
    @java.lang.Override
    public java.lang.String getLastModified() {
      return instance.getLastModified();
    }
    /**
     * <code>string last_modified = 1;</code>
     * @return The bytes for lastModified.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastModifiedBytes() {
      return instance.getLastModifiedBytes();
    }
    /**
     * <code>string last_modified = 1;</code>
     * @param value The lastModified to set.
     * @return This builder for chaining.
     */
    public Builder setLastModified(
        java.lang.String value) {
      copyOnWrite();
      instance.setLastModified(value);
      return this;
    }
    /**
     * <code>string last_modified = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastModified() {
      copyOnWrite();
      instance.clearLastModified();
      return this;
    }
    /**
     * <code>string last_modified = 1;</code>
     * @param value The bytes for lastModified to set.
     * @return This builder for chaining.
     */
    public Builder setLastModifiedBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLastModifiedBytes(value);
      return this;
    }

    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.pocketcasts.service.api.LegacySyncResponseRecord> getChangesList() {
      return java.util.Collections.unmodifiableList(
          instance.getChangesList());
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    @java.lang.Override
    public int getChangesCount() {
      return instance.getChangesCount();
    }/**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.LegacySyncResponseRecord getChanges(int index) {
      return instance.getChanges(index);
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder setChanges(
        int index, com.pocketcasts.service.api.LegacySyncResponseRecord value) {
      copyOnWrite();
      instance.setChanges(index, value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder setChanges(
        int index, com.pocketcasts.service.api.LegacySyncResponseRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder addChanges(com.pocketcasts.service.api.LegacySyncResponseRecord value) {
      copyOnWrite();
      instance.addChanges(value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder addChanges(
        int index, com.pocketcasts.service.api.LegacySyncResponseRecord value) {
      copyOnWrite();
      instance.addChanges(index, value);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder addChanges(
        com.pocketcasts.service.api.LegacySyncResponseRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder addChanges(
        int index, com.pocketcasts.service.api.LegacySyncResponseRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder addAllChanges(
        java.lang.Iterable<? extends com.pocketcasts.service.api.LegacySyncResponseRecord> values) {
      copyOnWrite();
      instance.addAllChanges(values);
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder clearChanges() {
      copyOnWrite();
      instance.clearChanges();
      return this;
    }
    /**
     * <code>repeated .api.LegacySyncResponseRecord changes = 2;</code>
     */
    public Builder removeChanges(int index) {
      copyOnWrite();
      instance.removeChanges(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.LegacySyncResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.LegacySyncResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "lastModified_",
            "changes_",
            com.pocketcasts.service.api.LegacySyncResponseRecord.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.LegacySyncResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.LegacySyncResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.LegacySyncResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.LegacySyncResponse)
  private static final com.pocketcasts.service.api.LegacySyncResponse DEFAULT_INSTANCE;
  static {
    LegacySyncResponse defaultInstance = new LegacySyncResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LegacySyncResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.LegacySyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LegacySyncResponse> PARSER;

  public static com.google.protobuf.Parser<LegacySyncResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

