// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializelegacyRequest")
public inline fun legacyRequest(block: com.pocketcasts.service.api.LegacyRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.LegacyRequest =
    com.pocketcasts.service.api.LegacyRequestKt.Dsl._create(com.pocketcasts.service.api.LegacyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.LegacyRequest`
 */
public object LegacyRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.LegacyRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.LegacyRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.LegacyRequest = _builder.build()

        /**
         * `string device = 1;`
         */
        public var device: kotlin.String
            @JvmName("getDevice")
            get() = _builder.getDevice()
            @JvmName("setDevice")
            set(value) {
                _builder.setDevice(value)
            }
        /**
         * `string device = 1;`
         */
        public fun clearDevice() {
            _builder.clearDevice()
        }

        /**
         * `string datetime = 2;`
         */
        public var datetime: kotlin.String
            @JvmName("getDatetime")
            get() = _builder.getDatetime()
            @JvmName("setDatetime")
            set(value) {
                _builder.setDatetime(value)
            }
        /**
         * `string datetime = 2;`
         */
        public fun clearDatetime() {
            _builder.clearDatetime()
        }

        /**
         * `string v = 3;`
         */
        public var v: kotlin.String
            @JvmName("getV")
            get() = _builder.getV()
            @JvmName("setV")
            set(value) {
                _builder.setV(value)
            }
        /**
         * `string v = 3;`
         */
        public fun clearV() {
            _builder.clearV()
        }

        /**
         * `string av = 4;`
         */
        public var av: kotlin.String
            @JvmName("getAv")
            get() = _builder.getAv()
            @JvmName("setAv")
            set(value) {
                _builder.setAv(value)
            }
        /**
         * `string av = 4;`
         */
        public fun clearAv() {
            _builder.clearAv()
        }

        /**
         * `string ac = 5;`
         */
        public var ac: kotlin.String
            @JvmName("getAc")
            get() = _builder.getAc()
            @JvmName("setAc")
            set(value) {
                _builder.setAc(value)
            }
        /**
         * `string ac = 5;`
         */
        public fun clearAc() {
            _builder.clearAc()
        }

        /**
         * `string h = 6;`
         */
        public var h: kotlin.String
            @JvmName("getH")
            get() = _builder.getH()
            @JvmName("setH")
            set(value) {
                _builder.setH(value)
            }
        /**
         * `string h = 6;`
         */
        public fun clearH() {
            _builder.clearH()
        }

        /**
         * `string dt = 7;`
         */
        public var dt: kotlin.String
            @JvmName("getDt")
            get() = _builder.getDt()
            @JvmName("setDt")
            set(value) {
                _builder.setDt(value)
            }
        /**
         * `string dt = 7;`
         */
        public fun clearDt() {
            _builder.clearDt()
        }

        /**
         * `string c = 8;`
         */
        public var c: kotlin.String
            @JvmName("getC")
            get() = _builder.getC()
            @JvmName("setC")
            set(value) {
                _builder.setC(value)
            }
        /**
         * `string c = 8;`
         */
        public fun clearC() {
            _builder.clearC()
        }

        /**
         * `string l = 9;`
         */
        public var l: kotlin.String
            @JvmName("getL")
            get() = _builder.getL()
            @JvmName("setL")
            set(value) {
                _builder.setL(value)
            }
        /**
         * `string l = 9;`
         */
        public fun clearL() {
            _builder.clearL()
        }

        /**
         * `string m = 10;`
         */
        public var m: kotlin.String
            @JvmName("getM")
            get() = _builder.getM()
            @JvmName("setM")
            set(value) {
                _builder.setM(value)
            }
        /**
         * `string m = 10;`
         */
        public fun clearM() {
            _builder.clearM()
        }

        /**
         * `string email = 11;`
         */
        public var email: kotlin.String
            @JvmName("getEmail")
            get() = _builder.getEmail()
            @JvmName("setEmail")
            set(value) {
                _builder.setEmail(value)
            }
        /**
         * `string email = 11;`
         */
        public fun clearEmail() {
            _builder.clearEmail()
        }

        /**
         * `string password = 12;`
         */
        public var password: kotlin.String
            @JvmName("getPassword")
            get() = _builder.getPassword()
            @JvmName("setPassword")
            set(value) {
                _builder.setPassword(value)
            }
        /**
         * `string password = 12;`
         */
        public fun clearPassword() {
            _builder.clearPassword()
        }

        /**
         * `string token = 13;`
         */
        public var token: kotlin.String
            @JvmName("getToken")
            get() = _builder.getToken()
            @JvmName("setToken")
            set(value) {
                _builder.setToken(value)
            }
        /**
         * `string token = 13;`
         */
        public fun clearToken() {
            _builder.clearToken()
        }

        /**
         * `string device_utc_time_ms = 14;`
         */
        public var deviceUtcTimeMs: kotlin.String
            @JvmName("getDeviceUtcTimeMs")
            get() = _builder.getDeviceUtcTimeMs()
            @JvmName("setDeviceUtcTimeMs")
            set(value) {
                _builder.setDeviceUtcTimeMs(value)
            }
        /**
         * `string device_utc_time_ms = 14;`
         */
        public fun clearDeviceUtcTimeMs() {
            _builder.clearDeviceUtcTimeMs()
        }

        /**
         * `string data = 15;`
         */
        public var data: kotlin.String
            @JvmName("getData")
            get() = _builder.getData()
            @JvmName("setData")
            set(value) {
                _builder.setData(value)
            }
        /**
         * `string data = 15;`
         */
        public fun clearData() {
            _builder.clearData()
        }

        /**
         * `string message = 16;`
         */
        public var message: kotlin.String
            @JvmName("getMessage")
            get() = _builder.getMessage()
            @JvmName("setMessage")
            set(value) {
                _builder.setMessage(value)
            }
        /**
         * `string message = 16;`
         */
        public fun clearMessage() {
            _builder.clearMessage()
        }

        /**
         * `string last_modified = 17;`
         */
        public var lastModified: kotlin.String
            @JvmName("getLastModified")
            get() = _builder.getLastModified()
            @JvmName("setLastModified")
            set(value) {
                _builder.setLastModified(value)
            }
        /**
         * `string last_modified = 17;`
         */
        public fun clearLastModified() {
            _builder.clearLastModified()
        }
    }
}
public inline fun com.pocketcasts.service.api.LegacyRequest.copy(block: com.pocketcasts.service.api.LegacyRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.LegacyRequest =
    com.pocketcasts.service.api.LegacyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
