// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializenamedSettingsResponse")
public inline fun namedSettingsResponse(block: com.pocketcasts.service.api.NamedSettingsResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.NamedSettingsResponse =
    com.pocketcasts.service.api.NamedSettingsResponseKt.Dsl._create(com.pocketcasts.service.api.NamedSettingsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.NamedSettingsResponse`
 */
public object NamedSettingsResponseKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.NamedSettingsResponse.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.NamedSettingsResponse.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.NamedSettingsResponse = _builder.build()

        /**
         * `.api.Int32Setting grid_layout = 1;`
         */
        public var gridLayout: com.pocketcasts.service.api.Int32Setting
            @JvmName("getGridLayout")
            get() = _builder.getGridLayout()
            @JvmName("setGridLayout")
            set(value) {
                _builder.setGridLayout(value)
            }
        /**
         * `.api.Int32Setting grid_layout = 1;`
         */
        public fun clearGridLayout() {
            _builder.clearGridLayout()
        }
        /**
         * `.api.Int32Setting grid_layout = 1;`
         * @return Whether the gridLayout field is set.
         */
        public fun hasGridLayout(): kotlin.Boolean {
            return _builder.hasGridLayout()
        }

        /**
         * `.api.Int32Setting grid_order = 2;`
         */
        public var gridOrder: com.pocketcasts.service.api.Int32Setting
            @JvmName("getGridOrder")
            get() = _builder.getGridOrder()
            @JvmName("setGridOrder")
            set(value) {
                _builder.setGridOrder(value)
            }
        /**
         * `.api.Int32Setting grid_order = 2;`
         */
        public fun clearGridOrder() {
            _builder.clearGridOrder()
        }
        /**
         * `.api.Int32Setting grid_order = 2;`
         * @return Whether the gridOrder field is set.
         */
        public fun hasGridOrder(): kotlin.Boolean {
            return _builder.hasGridOrder()
        }

        /**
         * `.api.Int32Setting show_played = 3;`
         */
        public var showPlayed: com.pocketcasts.service.api.Int32Setting
            @JvmName("getShowPlayed")
            get() = _builder.getShowPlayed()
            @JvmName("setShowPlayed")
            set(value) {
                _builder.setShowPlayed(value)
            }
        /**
         * `.api.Int32Setting show_played = 3;`
         */
        public fun clearShowPlayed() {
            _builder.clearShowPlayed()
        }
        /**
         * `.api.Int32Setting show_played = 3;`
         * @return Whether the showPlayed field is set.
         */
        public fun hasShowPlayed(): kotlin.Boolean {
            return _builder.hasShowPlayed()
        }

        /**
         * `.api.Int32Setting theme = 4;`
         */
        public var theme: com.pocketcasts.service.api.Int32Setting
            @JvmName("getTheme")
            get() = _builder.getTheme()
            @JvmName("setTheme")
            set(value) {
                _builder.setTheme(value)
            }
        /**
         * `.api.Int32Setting theme = 4;`
         */
        public fun clearTheme() {
            _builder.clearTheme()
        }
        /**
         * `.api.Int32Setting theme = 4;`
         * @return Whether the theme field is set.
         */
        public fun hasTheme(): kotlin.Boolean {
            return _builder.hasTheme()
        }

        /**
         * `.api.Int32Setting skip_forward = 5;`
         */
        public var skipForward: com.pocketcasts.service.api.Int32Setting
            @JvmName("getSkipForward")
            get() = _builder.getSkipForward()
            @JvmName("setSkipForward")
            set(value) {
                _builder.setSkipForward(value)
            }
        /**
         * `.api.Int32Setting skip_forward = 5;`
         */
        public fun clearSkipForward() {
            _builder.clearSkipForward()
        }
        /**
         * `.api.Int32Setting skip_forward = 5;`
         * @return Whether the skipForward field is set.
         */
        public fun hasSkipForward(): kotlin.Boolean {
            return _builder.hasSkipForward()
        }

        /**
         * `.api.Int32Setting skip_back = 6;`
         */
        public var skipBack: com.pocketcasts.service.api.Int32Setting
            @JvmName("getSkipBack")
            get() = _builder.getSkipBack()
            @JvmName("setSkipBack")
            set(value) {
                _builder.setSkipBack(value)
            }
        /**
         * `.api.Int32Setting skip_back = 6;`
         */
        public fun clearSkipBack() {
            _builder.clearSkipBack()
        }
        /**
         * `.api.Int32Setting skip_back = 6;`
         * @return Whether the skipBack field is set.
         */
        public fun hasSkipBack(): kotlin.Boolean {
            return _builder.hasSkipBack()
        }

        /**
         * `.api.Int32Setting web_version = 7;`
         */
        public var webVersion: com.pocketcasts.service.api.Int32Setting
            @JvmName("getWebVersion")
            get() = _builder.getWebVersion()
            @JvmName("setWebVersion")
            set(value) {
                _builder.setWebVersion(value)
            }
        /**
         * `.api.Int32Setting web_version = 7;`
         */
        public fun clearWebVersion() {
            _builder.clearWebVersion()
        }
        /**
         * `.api.Int32Setting web_version = 7;`
         * @return Whether the webVersion field is set.
         */
        public fun hasWebVersion(): kotlin.Boolean {
            return _builder.hasWebVersion()
        }

        /**
         * `.api.StringSetting language = 8;`
         */
        public var language: com.pocketcasts.service.api.StringSetting
            @JvmName("getLanguage")
            get() = _builder.getLanguage()
            @JvmName("setLanguage")
            set(value) {
                _builder.setLanguage(value)
            }
        /**
         * `.api.StringSetting language = 8;`
         */
        public fun clearLanguage() {
            _builder.clearLanguage()
        }
        /**
         * `.api.StringSetting language = 8;`
         * @return Whether the language field is set.
         */
        public fun hasLanguage(): kotlin.Boolean {
            return _builder.hasLanguage()
        }

        /**
         * `.api.BoolSetting recommendations_on = 9;`
         */
        public var recommendationsOn: com.pocketcasts.service.api.BoolSetting
            @JvmName("getRecommendationsOn")
            get() = _builder.getRecommendationsOn()
            @JvmName("setRecommendationsOn")
            set(value) {
                _builder.setRecommendationsOn(value)
            }
        /**
         * `.api.BoolSetting recommendations_on = 9;`
         */
        public fun clearRecommendationsOn() {
            _builder.clearRecommendationsOn()
        }
        /**
         * `.api.BoolSetting recommendations_on = 9;`
         * @return Whether the recommendationsOn field is set.
         */
        public fun hasRecommendationsOn(): kotlin.Boolean {
            return _builder.hasRecommendationsOn()
        }

        /**
         * `.api.BoolSetting stream_by_default = 10;`
         */
        public var streamByDefault: com.pocketcasts.service.api.BoolSetting
            @JvmName("getStreamByDefault")
            get() = _builder.getStreamByDefault()
            @JvmName("setStreamByDefault")
            set(value) {
                _builder.setStreamByDefault(value)
            }
        /**
         * `.api.BoolSetting stream_by_default = 10;`
         */
        public fun clearStreamByDefault() {
            _builder.clearStreamByDefault()
        }
        /**
         * `.api.BoolSetting stream_by_default = 10;`
         * @return Whether the streamByDefault field is set.
         */
        public fun hasStreamByDefault(): kotlin.Boolean {
            return _builder.hasStreamByDefault()
        }

        /**
         * `.api.BoolSetting use_embedded_artwork = 11;`
         */
        public var useEmbeddedArtwork: com.pocketcasts.service.api.BoolSetting
            @JvmName("getUseEmbeddedArtwork")
            get() = _builder.getUseEmbeddedArtwork()
            @JvmName("setUseEmbeddedArtwork")
            set(value) {
                _builder.setUseEmbeddedArtwork(value)
            }
        /**
         * `.api.BoolSetting use_embedded_artwork = 11;`
         */
        public fun clearUseEmbeddedArtwork() {
            _builder.clearUseEmbeddedArtwork()
        }
        /**
         * `.api.BoolSetting use_embedded_artwork = 11;`
         * @return Whether the useEmbeddedArtwork field is set.
         */
        public fun hasUseEmbeddedArtwork(): kotlin.Boolean {
            return _builder.hasUseEmbeddedArtwork()
        }

        /**
         * `.api.DoubleSetting playback_speed = 12;`
         */
        public var playbackSpeed: com.pocketcasts.service.api.DoubleSetting
            @JvmName("getPlaybackSpeed")
            get() = _builder.getPlaybackSpeed()
            @JvmName("setPlaybackSpeed")
            set(value) {
                _builder.setPlaybackSpeed(value)
            }
        /**
         * `.api.DoubleSetting playback_speed = 12;`
         */
        public fun clearPlaybackSpeed() {
            _builder.clearPlaybackSpeed()
        }
        /**
         * `.api.DoubleSetting playback_speed = 12;`
         * @return Whether the playbackSpeed field is set.
         */
        public fun hasPlaybackSpeed(): kotlin.Boolean {
            return _builder.hasPlaybackSpeed()
        }

        /**
         * `.api.BoolSetting silence_removal = 13;`
         */
        public var silenceRemoval: com.pocketcasts.service.api.BoolSetting
            @JvmName("getSilenceRemoval")
            get() = _builder.getSilenceRemoval()
            @JvmName("setSilenceRemoval")
            set(value) {
                _builder.setSilenceRemoval(value)
            }
        /**
         * `.api.BoolSetting silence_removal = 13;`
         */
        public fun clearSilenceRemoval() {
            _builder.clearSilenceRemoval()
        }
        /**
         * `.api.BoolSetting silence_removal = 13;`
         * @return Whether the silenceRemoval field is set.
         */
        public fun hasSilenceRemoval(): kotlin.Boolean {
            return _builder.hasSilenceRemoval()
        }

        /**
         * `.api.BoolSetting volume_boost = 14;`
         */
        public var volumeBoost: com.pocketcasts.service.api.BoolSetting
            @JvmName("getVolumeBoost")
            get() = _builder.getVolumeBoost()
            @JvmName("setVolumeBoost")
            set(value) {
                _builder.setVolumeBoost(value)
            }
        /**
         * `.api.BoolSetting volume_boost = 14;`
         */
        public fun clearVolumeBoost() {
            _builder.clearVolumeBoost()
        }
        /**
         * `.api.BoolSetting volume_boost = 14;`
         * @return Whether the volumeBoost field is set.
         */
        public fun hasVolumeBoost(): kotlin.Boolean {
            return _builder.hasVolumeBoost()
        }

        /**
         * `.api.Int32Setting badges = 15;`
         */
        public var badges: com.pocketcasts.service.api.Int32Setting
            @JvmName("getBadges")
            get() = _builder.getBadges()
            @JvmName("setBadges")
            set(value) {
                _builder.setBadges(value)
            }
        /**
         * `.api.Int32Setting badges = 15;`
         */
        public fun clearBadges() {
            _builder.clearBadges()
        }
        /**
         * `.api.Int32Setting badges = 15;`
         * @return Whether the badges field is set.
         */
        public fun hasBadges(): kotlin.Boolean {
            return _builder.hasBadges()
        }

        /**
         * `.api.BoolSetting free_gift_acknowledgement = 16;`
         */
        public var freeGiftAcknowledgement: com.pocketcasts.service.api.BoolSetting
            @JvmName("getFreeGiftAcknowledgement")
            get() = _builder.getFreeGiftAcknowledgement()
            @JvmName("setFreeGiftAcknowledgement")
            set(value) {
                _builder.setFreeGiftAcknowledgement(value)
            }
        /**
         * `.api.BoolSetting free_gift_acknowledgement = 16;`
         */
        public fun clearFreeGiftAcknowledgement() {
            _builder.clearFreeGiftAcknowledgement()
        }
        /**
         * `.api.BoolSetting free_gift_acknowledgement = 16;`
         * @return Whether the freeGiftAcknowledgement field is set.
         */
        public fun hasFreeGiftAcknowledgement(): kotlin.Boolean {
            return _builder.hasFreeGiftAcknowledgement()
        }

        /**
         * `.api.BoolSetting marketing_opt_in = 17;`
         */
        public var marketingOptIn: com.pocketcasts.service.api.BoolSetting
            @JvmName("getMarketingOptIn")
            get() = _builder.getMarketingOptIn()
            @JvmName("setMarketingOptIn")
            set(value) {
                _builder.setMarketingOptIn(value)
            }
        /**
         * `.api.BoolSetting marketing_opt_in = 17;`
         */
        public fun clearMarketingOptIn() {
            _builder.clearMarketingOptIn()
        }
        /**
         * `.api.BoolSetting marketing_opt_in = 17;`
         * @return Whether the marketingOptIn field is set.
         */
        public fun hasMarketingOptIn(): kotlin.Boolean {
            return _builder.hasMarketingOptIn()
        }

        /**
         * `.api.BoolSetting auto_archive_played_episodes = 18;`
         */
        public var autoArchivePlayedEpisodes: com.pocketcasts.service.api.BoolSetting
            @JvmName("getAutoArchivePlayedEpisodes")
            get() = _builder.getAutoArchivePlayedEpisodes()
            @JvmName("setAutoArchivePlayedEpisodes")
            set(value) {
                _builder.setAutoArchivePlayedEpisodes(value)
            }
        /**
         * `.api.BoolSetting auto_archive_played_episodes = 18;`
         */
        public fun clearAutoArchivePlayedEpisodes() {
            _builder.clearAutoArchivePlayedEpisodes()
        }
        /**
         * `.api.BoolSetting auto_archive_played_episodes = 18;`
         * @return Whether the autoArchivePlayedEpisodes field is set.
         */
        public fun hasAutoArchivePlayedEpisodes(): kotlin.Boolean {
            return _builder.hasAutoArchivePlayedEpisodes()
        }

        /**
         * `.api.BoolSetting auto_archive_includes_starred = 19;`
         */
        public var autoArchiveIncludesStarred: com.pocketcasts.service.api.BoolSetting
            @JvmName("getAutoArchiveIncludesStarred")
            get() = _builder.getAutoArchiveIncludesStarred()
            @JvmName("setAutoArchiveIncludesStarred")
            set(value) {
                _builder.setAutoArchiveIncludesStarred(value)
            }
        /**
         * `.api.BoolSetting auto_archive_includes_starred = 19;`
         */
        public fun clearAutoArchiveIncludesStarred() {
            _builder.clearAutoArchiveIncludesStarred()
        }
        /**
         * `.api.BoolSetting auto_archive_includes_starred = 19;`
         * @return Whether the autoArchiveIncludesStarred field is set.
         */
        public fun hasAutoArchiveIncludesStarred(): kotlin.Boolean {
            return _builder.hasAutoArchiveIncludesStarred()
        }

        /**
         * `.api.StringSetting region = 20;`
         */
        public var region: com.pocketcasts.service.api.StringSetting
            @JvmName("getRegion")
            get() = _builder.getRegion()
            @JvmName("setRegion")
            set(value) {
                _builder.setRegion(value)
            }
        /**
         * `.api.StringSetting region = 20;`
         */
        public fun clearRegion() {
            _builder.clearRegion()
        }
        /**
         * `.api.StringSetting region = 20;`
         * @return Whether the region field is set.
         */
        public fun hasRegion(): kotlin.Boolean {
            return _builder.hasRegion()
        }
    }
}
public inline fun com.pocketcasts.service.api.NamedSettingsResponse.copy(block: com.pocketcasts.service.api.NamedSettingsResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.NamedSettingsResponse =
    com.pocketcasts.service.api.NamedSettingsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.gridLayoutOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasGridLayout()) getGridLayout() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.gridOrderOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasGridOrder()) getGridOrder() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.showPlayedOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasShowPlayed()) getShowPlayed() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.themeOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasTheme()) getTheme() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.skipForwardOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasSkipForward()) getSkipForward() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.skipBackOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasSkipBack()) getSkipBack() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.webVersionOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasWebVersion()) getWebVersion() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.languageOrNull: com.pocketcasts.service.api.StringSetting?
    get() = if (hasLanguage()) getLanguage() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.recommendationsOnOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasRecommendationsOn()) getRecommendationsOn() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.streamByDefaultOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasStreamByDefault()) getStreamByDefault() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.useEmbeddedArtworkOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasUseEmbeddedArtwork()) getUseEmbeddedArtwork() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.playbackSpeedOrNull: com.pocketcasts.service.api.DoubleSetting?
    get() = if (hasPlaybackSpeed()) getPlaybackSpeed() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.silenceRemovalOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasSilenceRemoval()) getSilenceRemoval() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.volumeBoostOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasVolumeBoost()) getVolumeBoost() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.badgesOrNull: com.pocketcasts.service.api.Int32Setting?
    get() = if (hasBadges()) getBadges() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.freeGiftAcknowledgementOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasFreeGiftAcknowledgement()) getFreeGiftAcknowledgement() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.marketingOptInOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasMarketingOptIn()) getMarketingOptIn() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.autoArchivePlayedEpisodesOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasAutoArchivePlayedEpisodes()) getAutoArchivePlayedEpisodes() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.autoArchiveIncludesStarredOrNull: com.pocketcasts.service.api.BoolSetting?
    get() = if (hasAutoArchiveIncludesStarred()) getAutoArchiveIncludesStarred() else null

public val com.pocketcasts.service.api.NamedSettingsResponseOrBuilder.regionOrNull: com.pocketcasts.service.api.StringSetting?
    get() = if (hasRegion()) getRegion() else null
