// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.NamedSettingsResponse}
 */
public  final class NamedSettingsResponse extends
    com.google.protobuf.GeneratedMessageLite<
        NamedSettingsResponse, NamedSettingsResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.NamedSettingsResponse)
    NamedSettingsResponseOrBuilder {
  private NamedSettingsResponse() {
  }
  public static final int GRID_LAYOUT_FIELD_NUMBER = 1;
  private com.pocketcasts.service.api.Int32Setting gridLayout_;
  /**
   * <code>.api.Int32Setting grid_layout = 1;</code>
   */
  @java.lang.Override
  public boolean hasGridLayout() {
    return gridLayout_ != null;
  }
  /**
   * <code>.api.Int32Setting grid_layout = 1;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getGridLayout() {
    return gridLayout_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : gridLayout_;
  }
  /**
   * <code>.api.Int32Setting grid_layout = 1;</code>
   */
  private void setGridLayout(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  gridLayout_ = value;

    }
  /**
   * <code>.api.Int32Setting grid_layout = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeGridLayout(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (gridLayout_ != null &&
        gridLayout_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      gridLayout_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(gridLayout_).mergeFrom(value).buildPartial();
    } else {
      gridLayout_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting grid_layout = 1;</code>
   */
  private void clearGridLayout() {  gridLayout_ = null;

  }

  public static final int GRID_ORDER_FIELD_NUMBER = 2;
  private com.pocketcasts.service.api.Int32Setting gridOrder_;
  /**
   * <code>.api.Int32Setting grid_order = 2;</code>
   */
  @java.lang.Override
  public boolean hasGridOrder() {
    return gridOrder_ != null;
  }
  /**
   * <code>.api.Int32Setting grid_order = 2;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getGridOrder() {
    return gridOrder_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : gridOrder_;
  }
  /**
   * <code>.api.Int32Setting grid_order = 2;</code>
   */
  private void setGridOrder(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  gridOrder_ = value;

    }
  /**
   * <code>.api.Int32Setting grid_order = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeGridOrder(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (gridOrder_ != null &&
        gridOrder_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      gridOrder_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(gridOrder_).mergeFrom(value).buildPartial();
    } else {
      gridOrder_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting grid_order = 2;</code>
   */
  private void clearGridOrder() {  gridOrder_ = null;

  }

  public static final int SHOW_PLAYED_FIELD_NUMBER = 3;
  private com.pocketcasts.service.api.Int32Setting showPlayed_;
  /**
   * <code>.api.Int32Setting show_played = 3;</code>
   */
  @java.lang.Override
  public boolean hasShowPlayed() {
    return showPlayed_ != null;
  }
  /**
   * <code>.api.Int32Setting show_played = 3;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getShowPlayed() {
    return showPlayed_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : showPlayed_;
  }
  /**
   * <code>.api.Int32Setting show_played = 3;</code>
   */
  private void setShowPlayed(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  showPlayed_ = value;

    }
  /**
   * <code>.api.Int32Setting show_played = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeShowPlayed(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (showPlayed_ != null &&
        showPlayed_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      showPlayed_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(showPlayed_).mergeFrom(value).buildPartial();
    } else {
      showPlayed_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting show_played = 3;</code>
   */
  private void clearShowPlayed() {  showPlayed_ = null;

  }

  public static final int THEME_FIELD_NUMBER = 4;
  private com.pocketcasts.service.api.Int32Setting theme_;
  /**
   * <code>.api.Int32Setting theme = 4;</code>
   */
  @java.lang.Override
  public boolean hasTheme() {
    return theme_ != null;
  }
  /**
   * <code>.api.Int32Setting theme = 4;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getTheme() {
    return theme_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : theme_;
  }
  /**
   * <code>.api.Int32Setting theme = 4;</code>
   */
  private void setTheme(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  theme_ = value;

    }
  /**
   * <code>.api.Int32Setting theme = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTheme(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (theme_ != null &&
        theme_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      theme_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(theme_).mergeFrom(value).buildPartial();
    } else {
      theme_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting theme = 4;</code>
   */
  private void clearTheme() {  theme_ = null;

  }

  public static final int SKIP_FORWARD_FIELD_NUMBER = 5;
  private com.pocketcasts.service.api.Int32Setting skipForward_;
  /**
   * <code>.api.Int32Setting skip_forward = 5;</code>
   */
  @java.lang.Override
  public boolean hasSkipForward() {
    return skipForward_ != null;
  }
  /**
   * <code>.api.Int32Setting skip_forward = 5;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getSkipForward() {
    return skipForward_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : skipForward_;
  }
  /**
   * <code>.api.Int32Setting skip_forward = 5;</code>
   */
  private void setSkipForward(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  skipForward_ = value;

    }
  /**
   * <code>.api.Int32Setting skip_forward = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSkipForward(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (skipForward_ != null &&
        skipForward_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      skipForward_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(skipForward_).mergeFrom(value).buildPartial();
    } else {
      skipForward_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting skip_forward = 5;</code>
   */
  private void clearSkipForward() {  skipForward_ = null;

  }

  public static final int SKIP_BACK_FIELD_NUMBER = 6;
  private com.pocketcasts.service.api.Int32Setting skipBack_;
  /**
   * <code>.api.Int32Setting skip_back = 6;</code>
   */
  @java.lang.Override
  public boolean hasSkipBack() {
    return skipBack_ != null;
  }
  /**
   * <code>.api.Int32Setting skip_back = 6;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getSkipBack() {
    return skipBack_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : skipBack_;
  }
  /**
   * <code>.api.Int32Setting skip_back = 6;</code>
   */
  private void setSkipBack(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  skipBack_ = value;

    }
  /**
   * <code>.api.Int32Setting skip_back = 6;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSkipBack(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (skipBack_ != null &&
        skipBack_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      skipBack_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(skipBack_).mergeFrom(value).buildPartial();
    } else {
      skipBack_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting skip_back = 6;</code>
   */
  private void clearSkipBack() {  skipBack_ = null;

  }

  public static final int WEB_VERSION_FIELD_NUMBER = 7;
  private com.pocketcasts.service.api.Int32Setting webVersion_;
  /**
   * <code>.api.Int32Setting web_version = 7;</code>
   */
  @java.lang.Override
  public boolean hasWebVersion() {
    return webVersion_ != null;
  }
  /**
   * <code>.api.Int32Setting web_version = 7;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getWebVersion() {
    return webVersion_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : webVersion_;
  }
  /**
   * <code>.api.Int32Setting web_version = 7;</code>
   */
  private void setWebVersion(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  webVersion_ = value;

    }
  /**
   * <code>.api.Int32Setting web_version = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeWebVersion(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (webVersion_ != null &&
        webVersion_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      webVersion_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(webVersion_).mergeFrom(value).buildPartial();
    } else {
      webVersion_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting web_version = 7;</code>
   */
  private void clearWebVersion() {  webVersion_ = null;

  }

  public static final int LANGUAGE_FIELD_NUMBER = 8;
  private com.pocketcasts.service.api.StringSetting language_;
  /**
   * <code>.api.StringSetting language = 8;</code>
   */
  @java.lang.Override
  public boolean hasLanguage() {
    return language_ != null;
  }
  /**
   * <code>.api.StringSetting language = 8;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.StringSetting getLanguage() {
    return language_ == null ? com.pocketcasts.service.api.StringSetting.getDefaultInstance() : language_;
  }
  /**
   * <code>.api.StringSetting language = 8;</code>
   */
  private void setLanguage(com.pocketcasts.service.api.StringSetting value) {
    value.getClass();
  language_ = value;

    }
  /**
   * <code>.api.StringSetting language = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLanguage(com.pocketcasts.service.api.StringSetting value) {
    value.getClass();
  if (language_ != null &&
        language_ != com.pocketcasts.service.api.StringSetting.getDefaultInstance()) {
      language_ =
        com.pocketcasts.service.api.StringSetting.newBuilder(language_).mergeFrom(value).buildPartial();
    } else {
      language_ = value;
    }

  }
  /**
   * <code>.api.StringSetting language = 8;</code>
   */
  private void clearLanguage() {  language_ = null;

  }

  public static final int RECOMMENDATIONS_ON_FIELD_NUMBER = 9;
  private com.pocketcasts.service.api.BoolSetting recommendationsOn_;
  /**
   * <code>.api.BoolSetting recommendations_on = 9;</code>
   */
  @java.lang.Override
  public boolean hasRecommendationsOn() {
    return recommendationsOn_ != null;
  }
  /**
   * <code>.api.BoolSetting recommendations_on = 9;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getRecommendationsOn() {
    return recommendationsOn_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : recommendationsOn_;
  }
  /**
   * <code>.api.BoolSetting recommendations_on = 9;</code>
   */
  private void setRecommendationsOn(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  recommendationsOn_ = value;

    }
  /**
   * <code>.api.BoolSetting recommendations_on = 9;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeRecommendationsOn(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (recommendationsOn_ != null &&
        recommendationsOn_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      recommendationsOn_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(recommendationsOn_).mergeFrom(value).buildPartial();
    } else {
      recommendationsOn_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting recommendations_on = 9;</code>
   */
  private void clearRecommendationsOn() {  recommendationsOn_ = null;

  }

  public static final int STREAM_BY_DEFAULT_FIELD_NUMBER = 10;
  private com.pocketcasts.service.api.BoolSetting streamByDefault_;
  /**
   * <code>.api.BoolSetting stream_by_default = 10;</code>
   */
  @java.lang.Override
  public boolean hasStreamByDefault() {
    return streamByDefault_ != null;
  }
  /**
   * <code>.api.BoolSetting stream_by_default = 10;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getStreamByDefault() {
    return streamByDefault_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : streamByDefault_;
  }
  /**
   * <code>.api.BoolSetting stream_by_default = 10;</code>
   */
  private void setStreamByDefault(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  streamByDefault_ = value;

    }
  /**
   * <code>.api.BoolSetting stream_by_default = 10;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeStreamByDefault(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (streamByDefault_ != null &&
        streamByDefault_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      streamByDefault_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(streamByDefault_).mergeFrom(value).buildPartial();
    } else {
      streamByDefault_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting stream_by_default = 10;</code>
   */
  private void clearStreamByDefault() {  streamByDefault_ = null;

  }

  public static final int USE_EMBEDDED_ARTWORK_FIELD_NUMBER = 11;
  private com.pocketcasts.service.api.BoolSetting useEmbeddedArtwork_;
  /**
   * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
   */
  @java.lang.Override
  public boolean hasUseEmbeddedArtwork() {
    return useEmbeddedArtwork_ != null;
  }
  /**
   * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getUseEmbeddedArtwork() {
    return useEmbeddedArtwork_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : useEmbeddedArtwork_;
  }
  /**
   * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
   */
  private void setUseEmbeddedArtwork(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  useEmbeddedArtwork_ = value;

    }
  /**
   * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUseEmbeddedArtwork(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (useEmbeddedArtwork_ != null &&
        useEmbeddedArtwork_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      useEmbeddedArtwork_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(useEmbeddedArtwork_).mergeFrom(value).buildPartial();
    } else {
      useEmbeddedArtwork_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
   */
  private void clearUseEmbeddedArtwork() {  useEmbeddedArtwork_ = null;

  }

  public static final int PLAYBACK_SPEED_FIELD_NUMBER = 12;
  private com.pocketcasts.service.api.DoubleSetting playbackSpeed_;
  /**
   * <code>.api.DoubleSetting playback_speed = 12;</code>
   */
  @java.lang.Override
  public boolean hasPlaybackSpeed() {
    return playbackSpeed_ != null;
  }
  /**
   * <code>.api.DoubleSetting playback_speed = 12;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.DoubleSetting getPlaybackSpeed() {
    return playbackSpeed_ == null ? com.pocketcasts.service.api.DoubleSetting.getDefaultInstance() : playbackSpeed_;
  }
  /**
   * <code>.api.DoubleSetting playback_speed = 12;</code>
   */
  private void setPlaybackSpeed(com.pocketcasts.service.api.DoubleSetting value) {
    value.getClass();
  playbackSpeed_ = value;

    }
  /**
   * <code>.api.DoubleSetting playback_speed = 12;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePlaybackSpeed(com.pocketcasts.service.api.DoubleSetting value) {
    value.getClass();
  if (playbackSpeed_ != null &&
        playbackSpeed_ != com.pocketcasts.service.api.DoubleSetting.getDefaultInstance()) {
      playbackSpeed_ =
        com.pocketcasts.service.api.DoubleSetting.newBuilder(playbackSpeed_).mergeFrom(value).buildPartial();
    } else {
      playbackSpeed_ = value;
    }

  }
  /**
   * <code>.api.DoubleSetting playback_speed = 12;</code>
   */
  private void clearPlaybackSpeed() {  playbackSpeed_ = null;

  }

  public static final int SILENCE_REMOVAL_FIELD_NUMBER = 13;
  private com.pocketcasts.service.api.BoolSetting silenceRemoval_;
  /**
   * <code>.api.BoolSetting silence_removal = 13;</code>
   */
  @java.lang.Override
  public boolean hasSilenceRemoval() {
    return silenceRemoval_ != null;
  }
  /**
   * <code>.api.BoolSetting silence_removal = 13;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getSilenceRemoval() {
    return silenceRemoval_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : silenceRemoval_;
  }
  /**
   * <code>.api.BoolSetting silence_removal = 13;</code>
   */
  private void setSilenceRemoval(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  silenceRemoval_ = value;

    }
  /**
   * <code>.api.BoolSetting silence_removal = 13;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSilenceRemoval(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (silenceRemoval_ != null &&
        silenceRemoval_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      silenceRemoval_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(silenceRemoval_).mergeFrom(value).buildPartial();
    } else {
      silenceRemoval_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting silence_removal = 13;</code>
   */
  private void clearSilenceRemoval() {  silenceRemoval_ = null;

  }

  public static final int VOLUME_BOOST_FIELD_NUMBER = 14;
  private com.pocketcasts.service.api.BoolSetting volumeBoost_;
  /**
   * <code>.api.BoolSetting volume_boost = 14;</code>
   */
  @java.lang.Override
  public boolean hasVolumeBoost() {
    return volumeBoost_ != null;
  }
  /**
   * <code>.api.BoolSetting volume_boost = 14;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getVolumeBoost() {
    return volumeBoost_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : volumeBoost_;
  }
  /**
   * <code>.api.BoolSetting volume_boost = 14;</code>
   */
  private void setVolumeBoost(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  volumeBoost_ = value;

    }
  /**
   * <code>.api.BoolSetting volume_boost = 14;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVolumeBoost(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (volumeBoost_ != null &&
        volumeBoost_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      volumeBoost_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(volumeBoost_).mergeFrom(value).buildPartial();
    } else {
      volumeBoost_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting volume_boost = 14;</code>
   */
  private void clearVolumeBoost() {  volumeBoost_ = null;

  }

  public static final int BADGES_FIELD_NUMBER = 15;
  private com.pocketcasts.service.api.Int32Setting badges_;
  /**
   * <code>.api.Int32Setting badges = 15;</code>
   */
  @java.lang.Override
  public boolean hasBadges() {
    return badges_ != null;
  }
  /**
   * <code>.api.Int32Setting badges = 15;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.Int32Setting getBadges() {
    return badges_ == null ? com.pocketcasts.service.api.Int32Setting.getDefaultInstance() : badges_;
  }
  /**
   * <code>.api.Int32Setting badges = 15;</code>
   */
  private void setBadges(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  badges_ = value;

    }
  /**
   * <code>.api.Int32Setting badges = 15;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBadges(com.pocketcasts.service.api.Int32Setting value) {
    value.getClass();
  if (badges_ != null &&
        badges_ != com.pocketcasts.service.api.Int32Setting.getDefaultInstance()) {
      badges_ =
        com.pocketcasts.service.api.Int32Setting.newBuilder(badges_).mergeFrom(value).buildPartial();
    } else {
      badges_ = value;
    }

  }
  /**
   * <code>.api.Int32Setting badges = 15;</code>
   */
  private void clearBadges() {  badges_ = null;

  }

  public static final int FREE_GIFT_ACKNOWLEDGEMENT_FIELD_NUMBER = 16;
  private com.pocketcasts.service.api.BoolSetting freeGiftAcknowledgement_;
  /**
   * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
   */
  @java.lang.Override
  public boolean hasFreeGiftAcknowledgement() {
    return freeGiftAcknowledgement_ != null;
  }
  /**
   * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getFreeGiftAcknowledgement() {
    return freeGiftAcknowledgement_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : freeGiftAcknowledgement_;
  }
  /**
   * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
   */
  private void setFreeGiftAcknowledgement(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  freeGiftAcknowledgement_ = value;

    }
  /**
   * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeFreeGiftAcknowledgement(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (freeGiftAcknowledgement_ != null &&
        freeGiftAcknowledgement_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      freeGiftAcknowledgement_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(freeGiftAcknowledgement_).mergeFrom(value).buildPartial();
    } else {
      freeGiftAcknowledgement_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
   */
  private void clearFreeGiftAcknowledgement() {  freeGiftAcknowledgement_ = null;

  }

  public static final int MARKETING_OPT_IN_FIELD_NUMBER = 17;
  private com.pocketcasts.service.api.BoolSetting marketingOptIn_;
  /**
   * <code>.api.BoolSetting marketing_opt_in = 17;</code>
   */
  @java.lang.Override
  public boolean hasMarketingOptIn() {
    return marketingOptIn_ != null;
  }
  /**
   * <code>.api.BoolSetting marketing_opt_in = 17;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getMarketingOptIn() {
    return marketingOptIn_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : marketingOptIn_;
  }
  /**
   * <code>.api.BoolSetting marketing_opt_in = 17;</code>
   */
  private void setMarketingOptIn(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  marketingOptIn_ = value;

    }
  /**
   * <code>.api.BoolSetting marketing_opt_in = 17;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeMarketingOptIn(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (marketingOptIn_ != null &&
        marketingOptIn_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      marketingOptIn_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(marketingOptIn_).mergeFrom(value).buildPartial();
    } else {
      marketingOptIn_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting marketing_opt_in = 17;</code>
   */
  private void clearMarketingOptIn() {  marketingOptIn_ = null;

  }

  public static final int AUTO_ARCHIVE_PLAYED_EPISODES_FIELD_NUMBER = 18;
  private com.pocketcasts.service.api.BoolSetting autoArchivePlayedEpisodes_;
  /**
   * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
   */
  @java.lang.Override
  public boolean hasAutoArchivePlayedEpisodes() {
    return autoArchivePlayedEpisodes_ != null;
  }
  /**
   * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getAutoArchivePlayedEpisodes() {
    return autoArchivePlayedEpisodes_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : autoArchivePlayedEpisodes_;
  }
  /**
   * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
   */
  private void setAutoArchivePlayedEpisodes(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  autoArchivePlayedEpisodes_ = value;

    }
  /**
   * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAutoArchivePlayedEpisodes(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (autoArchivePlayedEpisodes_ != null &&
        autoArchivePlayedEpisodes_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      autoArchivePlayedEpisodes_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(autoArchivePlayedEpisodes_).mergeFrom(value).buildPartial();
    } else {
      autoArchivePlayedEpisodes_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
   */
  private void clearAutoArchivePlayedEpisodes() {  autoArchivePlayedEpisodes_ = null;

  }

  public static final int AUTO_ARCHIVE_INCLUDES_STARRED_FIELD_NUMBER = 19;
  private com.pocketcasts.service.api.BoolSetting autoArchiveIncludesStarred_;
  /**
   * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
   */
  @java.lang.Override
  public boolean hasAutoArchiveIncludesStarred() {
    return autoArchiveIncludesStarred_ != null;
  }
  /**
   * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.BoolSetting getAutoArchiveIncludesStarred() {
    return autoArchiveIncludesStarred_ == null ? com.pocketcasts.service.api.BoolSetting.getDefaultInstance() : autoArchiveIncludesStarred_;
  }
  /**
   * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
   */
  private void setAutoArchiveIncludesStarred(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  autoArchiveIncludesStarred_ = value;

    }
  /**
   * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAutoArchiveIncludesStarred(com.pocketcasts.service.api.BoolSetting value) {
    value.getClass();
  if (autoArchiveIncludesStarred_ != null &&
        autoArchiveIncludesStarred_ != com.pocketcasts.service.api.BoolSetting.getDefaultInstance()) {
      autoArchiveIncludesStarred_ =
        com.pocketcasts.service.api.BoolSetting.newBuilder(autoArchiveIncludesStarred_).mergeFrom(value).buildPartial();
    } else {
      autoArchiveIncludesStarred_ = value;
    }

  }
  /**
   * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
   */
  private void clearAutoArchiveIncludesStarred() {  autoArchiveIncludesStarred_ = null;

  }

  public static final int REGION_FIELD_NUMBER = 20;
  private com.pocketcasts.service.api.StringSetting region_;
  /**
   * <code>.api.StringSetting region = 20;</code>
   */
  @java.lang.Override
  public boolean hasRegion() {
    return region_ != null;
  }
  /**
   * <code>.api.StringSetting region = 20;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.StringSetting getRegion() {
    return region_ == null ? com.pocketcasts.service.api.StringSetting.getDefaultInstance() : region_;
  }
  /**
   * <code>.api.StringSetting region = 20;</code>
   */
  private void setRegion(com.pocketcasts.service.api.StringSetting value) {
    value.getClass();
  region_ = value;

    }
  /**
   * <code>.api.StringSetting region = 20;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeRegion(com.pocketcasts.service.api.StringSetting value) {
    value.getClass();
  if (region_ != null &&
        region_ != com.pocketcasts.service.api.StringSetting.getDefaultInstance()) {
      region_ =
        com.pocketcasts.service.api.StringSetting.newBuilder(region_).mergeFrom(value).buildPartial();
    } else {
      region_ = value;
    }

  }
  /**
   * <code>.api.StringSetting region = 20;</code>
   */
  private void clearRegion() {  region_ = null;

  }

  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.NamedSettingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.NamedSettingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.NamedSettingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.NamedSettingsResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.NamedSettingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.NamedSettingsResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.NamedSettingsResponse)
      com.pocketcasts.service.api.NamedSettingsResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.NamedSettingsResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    @java.lang.Override
    public boolean hasGridLayout() {
      return instance.hasGridLayout();
    }
    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getGridLayout() {
      return instance.getGridLayout();
    }
    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    public Builder setGridLayout(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setGridLayout(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    public Builder setGridLayout(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setGridLayout(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    public Builder mergeGridLayout(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeGridLayout(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting grid_layout = 1;</code>
     */
    public Builder clearGridLayout() {  copyOnWrite();
      instance.clearGridLayout();
      return this;
    }

    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    @java.lang.Override
    public boolean hasGridOrder() {
      return instance.hasGridOrder();
    }
    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getGridOrder() {
      return instance.getGridOrder();
    }
    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    public Builder setGridOrder(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setGridOrder(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    public Builder setGridOrder(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setGridOrder(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    public Builder mergeGridOrder(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeGridOrder(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting grid_order = 2;</code>
     */
    public Builder clearGridOrder() {  copyOnWrite();
      instance.clearGridOrder();
      return this;
    }

    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    @java.lang.Override
    public boolean hasShowPlayed() {
      return instance.hasShowPlayed();
    }
    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getShowPlayed() {
      return instance.getShowPlayed();
    }
    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    public Builder setShowPlayed(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setShowPlayed(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    public Builder setShowPlayed(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setShowPlayed(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    public Builder mergeShowPlayed(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeShowPlayed(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting show_played = 3;</code>
     */
    public Builder clearShowPlayed() {  copyOnWrite();
      instance.clearShowPlayed();
      return this;
    }

    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    @java.lang.Override
    public boolean hasTheme() {
      return instance.hasTheme();
    }
    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getTheme() {
      return instance.getTheme();
    }
    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    public Builder setTheme(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setTheme(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    public Builder setTheme(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setTheme(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    public Builder mergeTheme(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeTheme(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting theme = 4;</code>
     */
    public Builder clearTheme() {  copyOnWrite();
      instance.clearTheme();
      return this;
    }

    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    @java.lang.Override
    public boolean hasSkipForward() {
      return instance.hasSkipForward();
    }
    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getSkipForward() {
      return instance.getSkipForward();
    }
    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    public Builder setSkipForward(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setSkipForward(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    public Builder setSkipForward(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setSkipForward(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    public Builder mergeSkipForward(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeSkipForward(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting skip_forward = 5;</code>
     */
    public Builder clearSkipForward() {  copyOnWrite();
      instance.clearSkipForward();
      return this;
    }

    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    @java.lang.Override
    public boolean hasSkipBack() {
      return instance.hasSkipBack();
    }
    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getSkipBack() {
      return instance.getSkipBack();
    }
    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    public Builder setSkipBack(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setSkipBack(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    public Builder setSkipBack(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setSkipBack(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    public Builder mergeSkipBack(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeSkipBack(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting skip_back = 6;</code>
     */
    public Builder clearSkipBack() {  copyOnWrite();
      instance.clearSkipBack();
      return this;
    }

    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    @java.lang.Override
    public boolean hasWebVersion() {
      return instance.hasWebVersion();
    }
    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getWebVersion() {
      return instance.getWebVersion();
    }
    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    public Builder setWebVersion(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setWebVersion(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    public Builder setWebVersion(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setWebVersion(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    public Builder mergeWebVersion(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeWebVersion(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting web_version = 7;</code>
     */
    public Builder clearWebVersion() {  copyOnWrite();
      instance.clearWebVersion();
      return this;
    }

    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    @java.lang.Override
    public boolean hasLanguage() {
      return instance.hasLanguage();
    }
    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.StringSetting getLanguage() {
      return instance.getLanguage();
    }
    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    public Builder setLanguage(com.pocketcasts.service.api.StringSetting value) {
      copyOnWrite();
      instance.setLanguage(value);
      return this;
      }
    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    public Builder setLanguage(
        com.pocketcasts.service.api.StringSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setLanguage(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    public Builder mergeLanguage(com.pocketcasts.service.api.StringSetting value) {
      copyOnWrite();
      instance.mergeLanguage(value);
      return this;
    }
    /**
     * <code>.api.StringSetting language = 8;</code>
     */
    public Builder clearLanguage() {  copyOnWrite();
      instance.clearLanguage();
      return this;
    }

    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    @java.lang.Override
    public boolean hasRecommendationsOn() {
      return instance.hasRecommendationsOn();
    }
    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getRecommendationsOn() {
      return instance.getRecommendationsOn();
    }
    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    public Builder setRecommendationsOn(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setRecommendationsOn(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    public Builder setRecommendationsOn(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setRecommendationsOn(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    public Builder mergeRecommendationsOn(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeRecommendationsOn(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting recommendations_on = 9;</code>
     */
    public Builder clearRecommendationsOn() {  copyOnWrite();
      instance.clearRecommendationsOn();
      return this;
    }

    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    @java.lang.Override
    public boolean hasStreamByDefault() {
      return instance.hasStreamByDefault();
    }
    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getStreamByDefault() {
      return instance.getStreamByDefault();
    }
    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    public Builder setStreamByDefault(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setStreamByDefault(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    public Builder setStreamByDefault(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setStreamByDefault(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    public Builder mergeStreamByDefault(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeStreamByDefault(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting stream_by_default = 10;</code>
     */
    public Builder clearStreamByDefault() {  copyOnWrite();
      instance.clearStreamByDefault();
      return this;
    }

    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    @java.lang.Override
    public boolean hasUseEmbeddedArtwork() {
      return instance.hasUseEmbeddedArtwork();
    }
    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getUseEmbeddedArtwork() {
      return instance.getUseEmbeddedArtwork();
    }
    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    public Builder setUseEmbeddedArtwork(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setUseEmbeddedArtwork(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    public Builder setUseEmbeddedArtwork(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setUseEmbeddedArtwork(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    public Builder mergeUseEmbeddedArtwork(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeUseEmbeddedArtwork(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting use_embedded_artwork = 11;</code>
     */
    public Builder clearUseEmbeddedArtwork() {  copyOnWrite();
      instance.clearUseEmbeddedArtwork();
      return this;
    }

    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    @java.lang.Override
    public boolean hasPlaybackSpeed() {
      return instance.hasPlaybackSpeed();
    }
    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.DoubleSetting getPlaybackSpeed() {
      return instance.getPlaybackSpeed();
    }
    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    public Builder setPlaybackSpeed(com.pocketcasts.service.api.DoubleSetting value) {
      copyOnWrite();
      instance.setPlaybackSpeed(value);
      return this;
      }
    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    public Builder setPlaybackSpeed(
        com.pocketcasts.service.api.DoubleSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setPlaybackSpeed(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    public Builder mergePlaybackSpeed(com.pocketcasts.service.api.DoubleSetting value) {
      copyOnWrite();
      instance.mergePlaybackSpeed(value);
      return this;
    }
    /**
     * <code>.api.DoubleSetting playback_speed = 12;</code>
     */
    public Builder clearPlaybackSpeed() {  copyOnWrite();
      instance.clearPlaybackSpeed();
      return this;
    }

    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    @java.lang.Override
    public boolean hasSilenceRemoval() {
      return instance.hasSilenceRemoval();
    }
    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getSilenceRemoval() {
      return instance.getSilenceRemoval();
    }
    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    public Builder setSilenceRemoval(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setSilenceRemoval(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    public Builder setSilenceRemoval(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setSilenceRemoval(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    public Builder mergeSilenceRemoval(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeSilenceRemoval(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting silence_removal = 13;</code>
     */
    public Builder clearSilenceRemoval() {  copyOnWrite();
      instance.clearSilenceRemoval();
      return this;
    }

    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    @java.lang.Override
    public boolean hasVolumeBoost() {
      return instance.hasVolumeBoost();
    }
    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getVolumeBoost() {
      return instance.getVolumeBoost();
    }
    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    public Builder setVolumeBoost(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setVolumeBoost(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    public Builder setVolumeBoost(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setVolumeBoost(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    public Builder mergeVolumeBoost(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeVolumeBoost(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting volume_boost = 14;</code>
     */
    public Builder clearVolumeBoost() {  copyOnWrite();
      instance.clearVolumeBoost();
      return this;
    }

    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    @java.lang.Override
    public boolean hasBadges() {
      return instance.hasBadges();
    }
    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.Int32Setting getBadges() {
      return instance.getBadges();
    }
    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    public Builder setBadges(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.setBadges(value);
      return this;
      }
    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    public Builder setBadges(
        com.pocketcasts.service.api.Int32Setting.Builder builderForValue) {
      copyOnWrite();
      instance.setBadges(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    public Builder mergeBadges(com.pocketcasts.service.api.Int32Setting value) {
      copyOnWrite();
      instance.mergeBadges(value);
      return this;
    }
    /**
     * <code>.api.Int32Setting badges = 15;</code>
     */
    public Builder clearBadges() {  copyOnWrite();
      instance.clearBadges();
      return this;
    }

    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    @java.lang.Override
    public boolean hasFreeGiftAcknowledgement() {
      return instance.hasFreeGiftAcknowledgement();
    }
    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getFreeGiftAcknowledgement() {
      return instance.getFreeGiftAcknowledgement();
    }
    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    public Builder setFreeGiftAcknowledgement(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setFreeGiftAcknowledgement(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    public Builder setFreeGiftAcknowledgement(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setFreeGiftAcknowledgement(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    public Builder mergeFreeGiftAcknowledgement(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeFreeGiftAcknowledgement(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting free_gift_acknowledgement = 16;</code>
     */
    public Builder clearFreeGiftAcknowledgement() {  copyOnWrite();
      instance.clearFreeGiftAcknowledgement();
      return this;
    }

    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    @java.lang.Override
    public boolean hasMarketingOptIn() {
      return instance.hasMarketingOptIn();
    }
    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getMarketingOptIn() {
      return instance.getMarketingOptIn();
    }
    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    public Builder setMarketingOptIn(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setMarketingOptIn(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    public Builder setMarketingOptIn(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setMarketingOptIn(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    public Builder mergeMarketingOptIn(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeMarketingOptIn(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting marketing_opt_in = 17;</code>
     */
    public Builder clearMarketingOptIn() {  copyOnWrite();
      instance.clearMarketingOptIn();
      return this;
    }

    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    @java.lang.Override
    public boolean hasAutoArchivePlayedEpisodes() {
      return instance.hasAutoArchivePlayedEpisodes();
    }
    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getAutoArchivePlayedEpisodes() {
      return instance.getAutoArchivePlayedEpisodes();
    }
    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    public Builder setAutoArchivePlayedEpisodes(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setAutoArchivePlayedEpisodes(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    public Builder setAutoArchivePlayedEpisodes(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setAutoArchivePlayedEpisodes(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    public Builder mergeAutoArchivePlayedEpisodes(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeAutoArchivePlayedEpisodes(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting auto_archive_played_episodes = 18;</code>
     */
    public Builder clearAutoArchivePlayedEpisodes() {  copyOnWrite();
      instance.clearAutoArchivePlayedEpisodes();
      return this;
    }

    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    @java.lang.Override
    public boolean hasAutoArchiveIncludesStarred() {
      return instance.hasAutoArchiveIncludesStarred();
    }
    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.BoolSetting getAutoArchiveIncludesStarred() {
      return instance.getAutoArchiveIncludesStarred();
    }
    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    public Builder setAutoArchiveIncludesStarred(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.setAutoArchiveIncludesStarred(value);
      return this;
      }
    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    public Builder setAutoArchiveIncludesStarred(
        com.pocketcasts.service.api.BoolSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setAutoArchiveIncludesStarred(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    public Builder mergeAutoArchiveIncludesStarred(com.pocketcasts.service.api.BoolSetting value) {
      copyOnWrite();
      instance.mergeAutoArchiveIncludesStarred(value);
      return this;
    }
    /**
     * <code>.api.BoolSetting auto_archive_includes_starred = 19;</code>
     */
    public Builder clearAutoArchiveIncludesStarred() {  copyOnWrite();
      instance.clearAutoArchiveIncludesStarred();
      return this;
    }

    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    @java.lang.Override
    public boolean hasRegion() {
      return instance.hasRegion();
    }
    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.StringSetting getRegion() {
      return instance.getRegion();
    }
    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    public Builder setRegion(com.pocketcasts.service.api.StringSetting value) {
      copyOnWrite();
      instance.setRegion(value);
      return this;
      }
    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    public Builder setRegion(
        com.pocketcasts.service.api.StringSetting.Builder builderForValue) {
      copyOnWrite();
      instance.setRegion(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    public Builder mergeRegion(com.pocketcasts.service.api.StringSetting value) {
      copyOnWrite();
      instance.mergeRegion(value);
      return this;
    }
    /**
     * <code>.api.StringSetting region = 20;</code>
     */
    public Builder clearRegion() {  copyOnWrite();
      instance.clearRegion();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.NamedSettingsResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.NamedSettingsResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "gridLayout_",
            "gridOrder_",
            "showPlayed_",
            "theme_",
            "skipForward_",
            "skipBack_",
            "webVersion_",
            "language_",
            "recommendationsOn_",
            "streamByDefault_",
            "useEmbeddedArtwork_",
            "playbackSpeed_",
            "silenceRemoval_",
            "volumeBoost_",
            "badges_",
            "freeGiftAcknowledgement_",
            "marketingOptIn_",
            "autoArchivePlayedEpisodes_",
            "autoArchiveIncludesStarred_",
            "region_",
          };
          java.lang.String info =
              "\u0000\u0014\u0000\u0000\u0001\u0014\u0014\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
              "\t\u0004\t\u0005\t\u0006\t\u0007\t\b\t\t\t\n\t\u000b\t\f\t\r\t\u000e\t\u000f\t\u0010" +
              "\t\u0011\t\u0012\t\u0013\t\u0014\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.NamedSettingsResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.NamedSettingsResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.NamedSettingsResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.NamedSettingsResponse)
  private static final com.pocketcasts.service.api.NamedSettingsResponse DEFAULT_INSTANCE;
  static {
    NamedSettingsResponse defaultInstance = new NamedSettingsResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NamedSettingsResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.NamedSettingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NamedSettingsResponse> PARSER;

  public static com.google.protobuf.Parser<NamedSettingsResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

