// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializenamedSettingsRequest")
public inline fun namedSettingsRequest(block: com.pocketcasts.service.api.NamedSettingsRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.NamedSettingsRequest =
    com.pocketcasts.service.api.NamedSettingsRequestKt.Dsl._create(com.pocketcasts.service.api.NamedSettingsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.NamedSettingsRequest`
 */
public object NamedSettingsRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.NamedSettingsRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.NamedSettingsRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.NamedSettingsRequest = _builder.build()

        /**
         * `string v = 1;`
         */
        public var v: kotlin.String
            @JvmName("getV")
            get() = _builder.getV()
            @JvmName("setV")
            set(value) {
                _builder.setV(value)
            }
        /**
         * `string v = 1;`
         */
        public fun clearV() {
            _builder.clearV()
        }

        /**
         * `string m = 2;`
         */
        public var m: kotlin.String
            @JvmName("getM")
            get() = _builder.getM()
            @JvmName("setM")
            set(value) {
                _builder.setM(value)
            }
        /**
         * `string m = 2;`
         */
        public fun clearM() {
            _builder.clearM()
        }

        /**
         * `.api.NamedSettings settings = 3;`
         */
        public var settings: com.pocketcasts.service.api.NamedSettings
            @JvmName("getSettings")
            get() = _builder.getSettings()
            @JvmName("setSettings")
            set(value) {
                _builder.setSettings(value)
            }
        /**
         * `.api.NamedSettings settings = 3;`
         */
        public fun clearSettings() {
            _builder.clearSettings()
        }
        /**
         * `.api.NamedSettings settings = 3;`
         * @return Whether the settings field is set.
         */
        public fun hasSettings(): kotlin.Boolean {
            return _builder.hasSettings()
        }
    }
}
public inline fun com.pocketcasts.service.api.NamedSettingsRequest.copy(block: com.pocketcasts.service.api.NamedSettingsRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.NamedSettingsRequest =
    com.pocketcasts.service.api.NamedSettingsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.pocketcasts.service.api.NamedSettingsRequestOrBuilder.settingsOrNull: com.pocketcasts.service.api.NamedSettings?
    get() = if (hasSettings()) getSettings() else null
