// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface PodcastFolderSortingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PodcastFolderSorting)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int32 position = 2;</code>
   * @return The position.
   */
  int getPosition();
}
