// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface PodcastPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.PodcastPair)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string masterPodcastUuid = 1;</code>
   * @return The masterPodcastUuid.
   */
  java.lang.String getMasterPodcastUuid();
  /**
   * <code>string masterPodcastUuid = 1;</code>
   * @return The bytes for masterPodcastUuid.
   */
  com.google.protobuf.ByteString
      getMasterPodcastUuidBytes();

  /**
   * <code>string userPodcastUuid = 2;</code>
   * @return The userPodcastUuid.
   */
  java.lang.String getUserPodcastUuid();
  /**
   * <code>string userPodcastUuid = 2;</code>
   * @return The bytes for userPodcastUuid.
   */
  com.google.protobuf.ByteString
      getUserPodcastUuidBytes();
}
