// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.Promotion}
 */
public  final class Promotion extends
    com.google.protobuf.GeneratedMessageLite<
        Promotion, Promotion.Builder> implements
    // @@protoc_insertion_point(message_implements:api.Promotion)
    PromotionOrBuilder {
  private Promotion() {
    code_ = "";
    description_ = "";
    startsAt_ = "";
    endsAt_ = "";
  }
  public static final int CODE_FIELD_NUMBER = 1;
  private java.lang.String code_;
  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    return code_;
  }
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(code_);
  }
  /**
   * <code>string code = 1;</code>
   * @param value The code to set.
   */
  private void setCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    code_ = value;
  }
  /**
   * <code>string code = 1;</code>
   */
  private void clearCode() {

    code_ = getDefaultInstance().getCode();
  }
  /**
   * <code>string code = 1;</code>
   * @param value The bytes for code to set.
   */
  private void setCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    code_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 2;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 2;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 2;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int STARTS_AT_FIELD_NUMBER = 3;
  private java.lang.String startsAt_;
  /**
   * <code>string starts_at = 3;</code>
   * @return The startsAt.
   */
  @java.lang.Override
  public java.lang.String getStartsAt() {
    return startsAt_;
  }
  /**
   * <code>string starts_at = 3;</code>
   * @return The bytes for startsAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartsAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(startsAt_);
  }
  /**
   * <code>string starts_at = 3;</code>
   * @param value The startsAt to set.
   */
  private void setStartsAt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    startsAt_ = value;
  }
  /**
   * <code>string starts_at = 3;</code>
   */
  private void clearStartsAt() {

    startsAt_ = getDefaultInstance().getStartsAt();
  }
  /**
   * <code>string starts_at = 3;</code>
   * @param value The bytes for startsAt to set.
   */
  private void setStartsAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    startsAt_ = value.toStringUtf8();

  }

  public static final int ENDS_AT_FIELD_NUMBER = 4;
  private java.lang.String endsAt_;
  /**
   * <code>string ends_at = 4;</code>
   * @return The endsAt.
   */
  @java.lang.Override
  public java.lang.String getEndsAt() {
    return endsAt_;
  }
  /**
   * <code>string ends_at = 4;</code>
   * @return The bytes for endsAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndsAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(endsAt_);
  }
  /**
   * <code>string ends_at = 4;</code>
   * @param value The endsAt to set.
   */
  private void setEndsAt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    endsAt_ = value;
  }
  /**
   * <code>string ends_at = 4;</code>
   */
  private void clearEndsAt() {

    endsAt_ = getDefaultInstance().getEndsAt();
  }
  /**
   * <code>string ends_at = 4;</code>
   * @param value The bytes for endsAt to set.
   */
  private void setEndsAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    endsAt_ = value.toStringUtf8();

  }

  public static com.pocketcasts.service.api.Promotion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.Promotion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.Promotion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.Promotion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.Promotion prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.Promotion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.Promotion, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.Promotion)
      com.pocketcasts.service.api.PromotionOrBuilder {
    // Construct using com.pocketcasts.service.api.Promotion.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      return instance.getCode();
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      return instance.getCodeBytes();
    }
    /**
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCodeBytes(value);
      return this;
    }

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>string starts_at = 3;</code>
     * @return The startsAt.
     */
    @java.lang.Override
    public java.lang.String getStartsAt() {
      return instance.getStartsAt();
    }
    /**
     * <code>string starts_at = 3;</code>
     * @return The bytes for startsAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartsAtBytes() {
      return instance.getStartsAtBytes();
    }
    /**
     * <code>string starts_at = 3;</code>
     * @param value The startsAt to set.
     * @return This builder for chaining.
     */
    public Builder setStartsAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setStartsAt(value);
      return this;
    }
    /**
     * <code>string starts_at = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartsAt() {
      copyOnWrite();
      instance.clearStartsAt();
      return this;
    }
    /**
     * <code>string starts_at = 3;</code>
     * @param value The bytes for startsAt to set.
     * @return This builder for chaining.
     */
    public Builder setStartsAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStartsAtBytes(value);
      return this;
    }

    /**
     * <code>string ends_at = 4;</code>
     * @return The endsAt.
     */
    @java.lang.Override
    public java.lang.String getEndsAt() {
      return instance.getEndsAt();
    }
    /**
     * <code>string ends_at = 4;</code>
     * @return The bytes for endsAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndsAtBytes() {
      return instance.getEndsAtBytes();
    }
    /**
     * <code>string ends_at = 4;</code>
     * @param value The endsAt to set.
     * @return This builder for chaining.
     */
    public Builder setEndsAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setEndsAt(value);
      return this;
    }
    /**
     * <code>string ends_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndsAt() {
      copyOnWrite();
      instance.clearEndsAt();
      return this;
    }
    /**
     * <code>string ends_at = 4;</code>
     * @param value The bytes for endsAt to set.
     * @return This builder for chaining.
     */
    public Builder setEndsAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEndsAtBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.Promotion)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.Promotion();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "code_",
            "description_",
            "startsAt_",
            "endsAt_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.Promotion> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.Promotion.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.Promotion>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.Promotion)
  private static final com.pocketcasts.service.api.Promotion DEFAULT_INSTANCE;
  static {
    Promotion defaultInstance = new Promotion();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Promotion.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.Promotion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Promotion> PARSER;

  public static com.google.protobuf.Parser<Promotion> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

