// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializepromotion")
public inline fun promotion(block: com.pocketcasts.service.api.PromotionKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.Promotion =
    com.pocketcasts.service.api.PromotionKt.Dsl._create(com.pocketcasts.service.api.Promotion.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.Promotion`
 */
public object PromotionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.Promotion.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.Promotion.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.Promotion = _builder.build()

        /**
         * `string code = 1;`
         */
        public var code: kotlin.String
            @JvmName("getCode")
            get() = _builder.getCode()
            @JvmName("setCode")
            set(value) {
                _builder.setCode(value)
            }
        /**
         * `string code = 1;`
         */
        public fun clearCode() {
            _builder.clearCode()
        }

        /**
         * `string description = 2;`
         */
        public var description: kotlin.String
            @JvmName("getDescription")
            get() = _builder.getDescription()
            @JvmName("setDescription")
            set(value) {
                _builder.setDescription(value)
            }
        /**
         * `string description = 2;`
         */
        public fun clearDescription() {
            _builder.clearDescription()
        }

        /**
         * `string starts_at = 3;`
         */
        public var startsAt: kotlin.String
            @JvmName("getStartsAt")
            get() = _builder.getStartsAt()
            @JvmName("setStartsAt")
            set(value) {
                _builder.setStartsAt(value)
            }
        /**
         * `string starts_at = 3;`
         */
        public fun clearStartsAt() {
            _builder.clearStartsAt()
        }

        /**
         * `string ends_at = 4;`
         */
        public var endsAt: kotlin.String
            @JvmName("getEndsAt")
            get() = _builder.getEndsAt()
            @JvmName("setEndsAt")
            set(value) {
                _builder.setEndsAt(value)
            }
        /**
         * `string ends_at = 4;`
         */
        public fun clearEndsAt() {
            _builder.clearEndsAt()
        }
    }
}
public inline fun com.pocketcasts.service.api.Promotion.copy(block: com.pocketcasts.service.api.PromotionKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.Promotion =
    com.pocketcasts.service.api.PromotionKt.Dsl._create(this.toBuilder()).apply { block() }._build()
