// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializestarredEpisode")
public inline fun starredEpisode(block: com.pocketcasts.service.api.StarredEpisodeKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.StarredEpisode =
    com.pocketcasts.service.api.StarredEpisodeKt.Dsl._create(com.pocketcasts.service.api.StarredEpisode.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.StarredEpisode`
 */
public object StarredEpisodeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.StarredEpisode.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.StarredEpisode.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.StarredEpisode = _builder.build()

        /**
         * `string uuid = 1;`
         */
        public var uuid: kotlin.String
            @JvmName("getUuid")
            get() = _builder.getUuid()
            @JvmName("setUuid")
            set(value) {
                _builder.setUuid(value)
            }
        /**
         * `string uuid = 1;`
         */
        public fun clearUuid() {
            _builder.clearUuid()
        }

        /**
         * `string podcast_uuid = 2;`
         */
        public var podcastUuid: kotlin.String
            @JvmName("getPodcastUuid")
            get() = _builder.getPodcastUuid()
            @JvmName("setPodcastUuid")
            set(value) {
                _builder.setPodcastUuid(value)
            }
        /**
         * `string podcast_uuid = 2;`
         */
        public fun clearPodcastUuid() {
            _builder.clearPodcastUuid()
        }

        /**
         * <code>int32 duration = 3;</code>
         */
        public var duration: kotlin.Int
            @JvmName("getDuration")
            get() = _builder.getDuration()
            @JvmName("setDuration")
            set(value) {
                _builder.setDuration(value)
            }
        /**
         * `int32 duration = 3;`
         */
        public fun clearDuration() {
            _builder.clearDuration()
        }

        /**
         * <code>int32 playing_status = 4;</code>
         */
        public var playingStatus: kotlin.Int
            @JvmName("getPlayingStatus")
            get() = _builder.getPlayingStatus()
            @JvmName("setPlayingStatus")
            set(value) {
                _builder.setPlayingStatus(value)
            }
        /**
         * `int32 playing_status = 4;`
         */
        public fun clearPlayingStatus() {
            _builder.clearPlayingStatus()
        }

        /**
         * <code>int32 played_up_to = 5;</code>
         */
        public var playedUpTo: kotlin.Int
            @JvmName("getPlayedUpTo")
            get() = _builder.getPlayedUpTo()
            @JvmName("setPlayedUpTo")
            set(value) {
                _builder.setPlayedUpTo(value)
            }
        /**
         * `int32 played_up_to = 5;`
         */
        public fun clearPlayedUpTo() {
            _builder.clearPlayedUpTo()
        }

        /**
         * <code>bool is_deleted = 6;</code>
         */
        public var isDeleted: kotlin.Boolean
            @JvmName("getIsDeleted")
            get() = _builder.getIsDeleted()
            @JvmName("setIsDeleted")
            set(value) {
                _builder.setIsDeleted(value)
            }
        /**
         * `bool is_deleted = 6;`
         */
        public fun clearIsDeleted() {
            _builder.clearIsDeleted()
        }

        /**
         * <code>int64 starred_modified = 7;</code>
         */
        public var starredModified: kotlin.Long
            @JvmName("getStarredModified")
            get() = _builder.getStarredModified()
            @JvmName("setStarredModified")
            set(value) {
                _builder.setStarredModified(value)
            }
        /**
         * `int64 starred_modified = 7;`
         */
        public fun clearStarredModified() {
            _builder.clearStarredModified()
        }
    }
}
public inline fun com.pocketcasts.service.api.StarredEpisode.copy(block: com.pocketcasts.service.api.StarredEpisodeKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.StarredEpisode =
    com.pocketcasts.service.api.StarredEpisodeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
