// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface StatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.StatsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 time_silence_removal = 1;</code>
   * @return The timeSilenceRemoval.
   */
  long getTimeSilenceRemoval();

  /**
   * <code>int64 time_skipping = 2;</code>
   * @return The timeSkipping.
   */
  long getTimeSkipping();

  /**
   * <code>int64 time_intro_skipping = 3;</code>
   * @return The timeIntroSkipping.
   */
  long getTimeIntroSkipping();

  /**
   * <code>int64 time_variable_speed = 4;</code>
   * @return The timeVariableSpeed.
   */
  long getTimeVariableSpeed();

  /**
   * <code>int64 time_listened = 5;</code>
   * @return The timeListened.
   */
  long getTimeListened();

  /**
   * <code>.google.protobuf.Timestamp times_started_at = 6;</code>
   * @return Whether the timesStartedAt field is set.
   */
  boolean hasTimesStartedAt();
  /**
   * <code>.google.protobuf.Timestamp times_started_at = 6;</code>
   * @return The timesStartedAt.
   */
  com.google.protobuf.Timestamp getTimesStartedAt();
}
