// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface SubscriptionsPurchaseAndroidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SubscriptionsPurchaseAndroidRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string purchaseToken = 1;</code>
   * @return The purchaseToken.
   */
  java.lang.String getPurchaseToken();
  /**
   * <code>string purchaseToken = 1;</code>
   * @return The bytes for purchaseToken.
   */
  com.google.protobuf.ByteString
      getPurchaseTokenBytes();

  /**
   * <code>string sku = 2;</code>
   * @return The sku.
   */
  java.lang.String getSku();
  /**
   * <code>string sku = 2;</code>
   * @return The bytes for sku.
   */
  com.google.protobuf.ByteString
      getSkuBytes();

  /**
   * <code>bool newsletterOptIn = 3;</code>
   * @return The newsletterOptIn.
   */
  boolean getNewsletterOptIn();
}
