// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializesubscriptionsPurchaseAppleRequest")
public inline fun subscriptionsPurchaseAppleRequest(block: com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest =
    com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequestKt.Dsl._create(com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.SubscriptionsPurchaseAppleRequest`
 */
public object SubscriptionsPurchaseAppleRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest = _builder.build()

        /**
         * `string receipt = 1;`
         */
        public var receipt: kotlin.String
            @JvmName("getReceipt")
            get() = _builder.getReceipt()
            @JvmName("setReceipt")
            set(value) {
                _builder.setReceipt(value)
            }
        /**
         * `string receipt = 1;`
         */
        public fun clearReceipt() {
            _builder.clearReceipt()
        }

        /**
         * <code>bool newsletterOptIn = 2;</code>
         */
        public var newsletterOptIn: kotlin.Boolean
            @JvmName("getNewsletterOptIn")
            get() = _builder.getNewsletterOptIn()
            @JvmName("setNewsletterOptIn")
            set(value) {
                _builder.setNewsletterOptIn(value)
            }
        /**
         * `bool newsletterOptIn = 2;`
         */
        public fun clearNewsletterOptIn() {
            _builder.clearNewsletterOptIn()
        }
    }
}
public inline fun com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.copy(block: com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest =
    com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
