// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.SubscriptionsPurchaseAppleRequest}
 */
public  final class SubscriptionsPurchaseAppleRequest extends
    com.google.protobuf.GeneratedMessageLite<
        SubscriptionsPurchaseAppleRequest, SubscriptionsPurchaseAppleRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:api.SubscriptionsPurchaseAppleRequest)
    SubscriptionsPurchaseAppleRequestOrBuilder {
  private SubscriptionsPurchaseAppleRequest() {
    receipt_ = "";
  }
  public static final int RECEIPT_FIELD_NUMBER = 1;
  private java.lang.String receipt_;
  /**
   * <code>string receipt = 1;</code>
   * @return The receipt.
   */
  @java.lang.Override
  public java.lang.String getReceipt() {
    return receipt_;
  }
  /**
   * <code>string receipt = 1;</code>
   * @return The bytes for receipt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiptBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(receipt_);
  }
  /**
   * <code>string receipt = 1;</code>
   * @param value The receipt to set.
   */
  private void setReceipt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    receipt_ = value;
  }
  /**
   * <code>string receipt = 1;</code>
   */
  private void clearReceipt() {

    receipt_ = getDefaultInstance().getReceipt();
  }
  /**
   * <code>string receipt = 1;</code>
   * @param value The bytes for receipt to set.
   */
  private void setReceiptBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    receipt_ = value.toStringUtf8();

  }

  public static final int NEWSLETTEROPTIN_FIELD_NUMBER = 2;
  private boolean newsletterOptIn_;
  /**
   * <code>bool newsletterOptIn = 2;</code>
   * @return The newsletterOptIn.
   */
  @java.lang.Override
  public boolean getNewsletterOptIn() {
    return newsletterOptIn_;
  }
  /**
   * <code>bool newsletterOptIn = 2;</code>
   * @param value The newsletterOptIn to set.
   */
  private void setNewsletterOptIn(boolean value) {
    
    newsletterOptIn_ = value;
  }
  /**
   * <code>bool newsletterOptIn = 2;</code>
   */
  private void clearNewsletterOptIn() {

    newsletterOptIn_ = false;
  }

  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.SubscriptionsPurchaseAppleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.SubscriptionsPurchaseAppleRequest)
      com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequestOrBuilder {
    // Construct using com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string receipt = 1;</code>
     * @return The receipt.
     */
    @java.lang.Override
    public java.lang.String getReceipt() {
      return instance.getReceipt();
    }
    /**
     * <code>string receipt = 1;</code>
     * @return The bytes for receipt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiptBytes() {
      return instance.getReceiptBytes();
    }
    /**
     * <code>string receipt = 1;</code>
     * @param value The receipt to set.
     * @return This builder for chaining.
     */
    public Builder setReceipt(
        java.lang.String value) {
      copyOnWrite();
      instance.setReceipt(value);
      return this;
    }
    /**
     * <code>string receipt = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceipt() {
      copyOnWrite();
      instance.clearReceipt();
      return this;
    }
    /**
     * <code>string receipt = 1;</code>
     * @param value The bytes for receipt to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReceiptBytes(value);
      return this;
    }

    /**
     * <code>bool newsletterOptIn = 2;</code>
     * @return The newsletterOptIn.
     */
    @java.lang.Override
    public boolean getNewsletterOptIn() {
      return instance.getNewsletterOptIn();
    }
    /**
     * <code>bool newsletterOptIn = 2;</code>
     * @param value The newsletterOptIn to set.
     * @return This builder for chaining.
     */
    public Builder setNewsletterOptIn(boolean value) {
      copyOnWrite();
      instance.setNewsletterOptIn(value);
      return this;
    }
    /**
     * <code>bool newsletterOptIn = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewsletterOptIn() {
      copyOnWrite();
      instance.clearNewsletterOptIn();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.SubscriptionsPurchaseAppleRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "receipt_",
            "newsletterOptIn_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.SubscriptionsPurchaseAppleRequest)
  private static final com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest DEFAULT_INSTANCE;
  static {
    SubscriptionsPurchaseAppleRequest defaultInstance = new SubscriptionsPurchaseAppleRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SubscriptionsPurchaseAppleRequest.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.SubscriptionsPurchaseAppleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SubscriptionsPurchaseAppleRequest> PARSER;

  public static com.google.protobuf.Parser<SubscriptionsPurchaseAppleRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

