// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializesyncUpdateEpisodeResponse")
public inline fun syncUpdateEpisodeResponse(block: com.pocketcasts.service.api.SyncUpdateEpisodeResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SyncUpdateEpisodeResponse =
    com.pocketcasts.service.api.SyncUpdateEpisodeResponseKt.Dsl._create(com.pocketcasts.service.api.SyncUpdateEpisodeResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.SyncUpdateEpisodeResponse`
 */
public object SyncUpdateEpisodeResponseKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.SyncUpdateEpisodeResponse.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.SyncUpdateEpisodeResponse.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.SyncUpdateEpisodeResponse = _builder.build()
    }
}
public inline fun com.pocketcasts.service.api.SyncUpdateEpisodeResponse.copy(block: com.pocketcasts.service.api.SyncUpdateEpisodeResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SyncUpdateEpisodeResponse =
    com.pocketcasts.service.api.SyncUpdateEpisodeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
