// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface SyncUserPlaylistOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SyncUserPlaylist)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.google.protobuf.BoolValue is_deleted = 2;</code>
   * @return Whether the isDeleted field is set.
   */
  boolean hasIsDeleted();
  /**
   * <code>.google.protobuf.BoolValue is_deleted = 2;</code>
   * @return The isDeleted.
   */
  com.google.protobuf.BoolValue getIsDeleted();

  /**
   * <code>.google.protobuf.StringValue title = 3;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>.google.protobuf.StringValue title = 3;</code>
   * @return The title.
   */
  com.google.protobuf.StringValue getTitle();

  /**
   * <code>.google.protobuf.BoolValue all_podcasts = 4;</code>
   * @return Whether the allPodcasts field is set.
   */
  boolean hasAllPodcasts();
  /**
   * <code>.google.protobuf.BoolValue all_podcasts = 4;</code>
   * @return The allPodcasts.
   */
  com.google.protobuf.BoolValue getAllPodcasts();

  /**
   * <code>.google.protobuf.StringValue podcast_uuids = 5;</code>
   * @return Whether the podcastUuids field is set.
   */
  boolean hasPodcastUuids();
  /**
   * <code>.google.protobuf.StringValue podcast_uuids = 5;</code>
   * @return The podcastUuids.
   */
  com.google.protobuf.StringValue getPodcastUuids();

  /**
   * <code>.google.protobuf.StringValue episode_uuids = 6;</code>
   * @return Whether the episodeUuids field is set.
   */
  boolean hasEpisodeUuids();
  /**
   * <code>.google.protobuf.StringValue episode_uuids = 6;</code>
   * @return The episodeUuids.
   */
  com.google.protobuf.StringValue getEpisodeUuids();

  /**
   * <code>.google.protobuf.Int32Value audio_video = 7;</code>
   * @return Whether the audioVideo field is set.
   */
  boolean hasAudioVideo();
  /**
   * <code>.google.protobuf.Int32Value audio_video = 7;</code>
   * @return The audioVideo.
   */
  com.google.protobuf.Int32Value getAudioVideo();

  /**
   * <code>.google.protobuf.BoolValue not_downloaded = 8;</code>
   * @return Whether the notDownloaded field is set.
   */
  boolean hasNotDownloaded();
  /**
   * <code>.google.protobuf.BoolValue not_downloaded = 8;</code>
   * @return The notDownloaded.
   */
  com.google.protobuf.BoolValue getNotDownloaded();

  /**
   * <code>.google.protobuf.BoolValue downloaded = 9;</code>
   * @return Whether the downloaded field is set.
   */
  boolean hasDownloaded();
  /**
   * <code>.google.protobuf.BoolValue downloaded = 9;</code>
   * @return The downloaded.
   */
  com.google.protobuf.BoolValue getDownloaded();

  /**
   * <code>.google.protobuf.BoolValue downloading = 10;</code>
   * @return Whether the downloading field is set.
   */
  boolean hasDownloading();
  /**
   * <code>.google.protobuf.BoolValue downloading = 10;</code>
   * @return The downloading.
   */
  com.google.protobuf.BoolValue getDownloading();

  /**
   * <code>.google.protobuf.BoolValue finished = 11;</code>
   * @return Whether the finished field is set.
   */
  boolean hasFinished();
  /**
   * <code>.google.protobuf.BoolValue finished = 11;</code>
   * @return The finished.
   */
  com.google.protobuf.BoolValue getFinished();

  /**
   * <code>.google.protobuf.BoolValue partially_played = 12;</code>
   * @return Whether the partiallyPlayed field is set.
   */
  boolean hasPartiallyPlayed();
  /**
   * <code>.google.protobuf.BoolValue partially_played = 12;</code>
   * @return The partiallyPlayed.
   */
  com.google.protobuf.BoolValue getPartiallyPlayed();

  /**
   * <code>.google.protobuf.BoolValue unplayed = 13;</code>
   * @return Whether the unplayed field is set.
   */
  boolean hasUnplayed();
  /**
   * <code>.google.protobuf.BoolValue unplayed = 13;</code>
   * @return The unplayed.
   */
  com.google.protobuf.BoolValue getUnplayed();

  /**
   * <code>.google.protobuf.BoolValue starred = 14;</code>
   * @return Whether the starred field is set.
   */
  boolean hasStarred();
  /**
   * <code>.google.protobuf.BoolValue starred = 14;</code>
   * @return The starred.
   */
  com.google.protobuf.BoolValue getStarred();

  /**
   * <code>.google.protobuf.BoolValue manual = 15;</code>
   * @return Whether the manual field is set.
   */
  boolean hasManual();
  /**
   * <code>.google.protobuf.BoolValue manual = 15;</code>
   * @return The manual.
   */
  com.google.protobuf.BoolValue getManual();

  /**
   * <code>.google.protobuf.Int32Value sort_position = 16;</code>
   * @return Whether the sortPosition field is set.
   */
  boolean hasSortPosition();
  /**
   * <code>.google.protobuf.Int32Value sort_position = 16;</code>
   * @return The sortPosition.
   */
  com.google.protobuf.Int32Value getSortPosition();

  /**
   * <code>.google.protobuf.Int32Value sort_type = 17;</code>
   * @return Whether the sortType field is set.
   */
  boolean hasSortType();
  /**
   * <code>.google.protobuf.Int32Value sort_type = 17;</code>
   * @return The sortType.
   */
  com.google.protobuf.Int32Value getSortType();

  /**
   * <code>.google.protobuf.Int32Value icon_id = 18;</code>
   * @return Whether the iconId field is set.
   */
  boolean hasIconId();
  /**
   * <code>.google.protobuf.Int32Value icon_id = 18;</code>
   * @return The iconId.
   */
  com.google.protobuf.Int32Value getIconId();

  /**
   * <code>.google.protobuf.Int32Value filter_hours = 19;</code>
   * @return Whether the filterHours field is set.
   */
  boolean hasFilterHours();
  /**
   * <code>.google.protobuf.Int32Value filter_hours = 19;</code>
   * @return The filterHours.
   */
  com.google.protobuf.Int32Value getFilterHours();

  /**
   * <code>string original_uuid = 20;</code>
   * @return The originalUuid.
   */
  java.lang.String getOriginalUuid();
  /**
   * <code>string original_uuid = 20;</code>
   * @return The bytes for originalUuid.
   */
  com.google.protobuf.ByteString
      getOriginalUuidBytes();

  /**
   * <code>.google.protobuf.BoolValue filter_duration = 21;</code>
   * @return Whether the filterDuration field is set.
   */
  boolean hasFilterDuration();
  /**
   * <code>.google.protobuf.BoolValue filter_duration = 21;</code>
   * @return The filterDuration.
   */
  com.google.protobuf.BoolValue getFilterDuration();

  /**
   * <code>.google.protobuf.Int32Value longer_than = 22;</code>
   * @return Whether the longerThan field is set.
   */
  boolean hasLongerThan();
  /**
   * <code>.google.protobuf.Int32Value longer_than = 22;</code>
   * @return The longerThan.
   */
  com.google.protobuf.Int32Value getLongerThan();

  /**
   * <code>.google.protobuf.Int32Value shorter_than = 23;</code>
   * @return Whether the shorterThan field is set.
   */
  boolean hasShorterThan();
  /**
   * <code>.google.protobuf.Int32Value shorter_than = 23;</code>
   * @return The shorterThan.
   */
  com.google.protobuf.Int32Value getShorterThan();
}
