// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializesyncUserPlaylist")
public inline fun syncUserPlaylist(block: com.pocketcasts.service.api.SyncUserPlaylistKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SyncUserPlaylist =
    com.pocketcasts.service.api.SyncUserPlaylistKt.Dsl._create(com.pocketcasts.service.api.SyncUserPlaylist.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.SyncUserPlaylist`
 */
public object SyncUserPlaylistKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.SyncUserPlaylist.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.SyncUserPlaylist.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.SyncUserPlaylist = _builder.build()

        /**
         * `string uuid = 1;`
         */
        public var uuid: kotlin.String
            @JvmName("getUuid")
            get() = _builder.getUuid()
            @JvmName("setUuid")
            set(value) {
                _builder.setUuid(value)
            }
        /**
         * `string uuid = 1;`
         */
        public fun clearUuid() {
            _builder.clearUuid()
        }

        /**
         * `.google.protobuf.BoolValue is_deleted = 2;`
         */
        public var isDeleted: com.google.protobuf.BoolValue
            @JvmName("getIsDeleted")
            get() = _builder.getIsDeleted()
            @JvmName("setIsDeleted")
            set(value) {
                _builder.setIsDeleted(value)
            }
        /**
         * `.google.protobuf.BoolValue is_deleted = 2;`
         */
        public fun clearIsDeleted() {
            _builder.clearIsDeleted()
        }
        /**
         * `.google.protobuf.BoolValue is_deleted = 2;`
         * @return Whether the isDeleted field is set.
         */
        public fun hasIsDeleted(): kotlin.Boolean {
            return _builder.hasIsDeleted()
        }

        /**
         * `.google.protobuf.StringValue title = 3;`
         */
        public var title: com.google.protobuf.StringValue
            @JvmName("getTitle")
            get() = _builder.getTitle()
            @JvmName("setTitle")
            set(value) {
                _builder.setTitle(value)
            }
        /**
         * `.google.protobuf.StringValue title = 3;`
         */
        public fun clearTitle() {
            _builder.clearTitle()
        }
        /**
         * `.google.protobuf.StringValue title = 3;`
         * @return Whether the title field is set.
         */
        public fun hasTitle(): kotlin.Boolean {
            return _builder.hasTitle()
        }

        /**
         * `.google.protobuf.BoolValue all_podcasts = 4;`
         */
        public var allPodcasts: com.google.protobuf.BoolValue
            @JvmName("getAllPodcasts")
            get() = _builder.getAllPodcasts()
            @JvmName("setAllPodcasts")
            set(value) {
                _builder.setAllPodcasts(value)
            }
        /**
         * `.google.protobuf.BoolValue all_podcasts = 4;`
         */
        public fun clearAllPodcasts() {
            _builder.clearAllPodcasts()
        }
        /**
         * `.google.protobuf.BoolValue all_podcasts = 4;`
         * @return Whether the allPodcasts field is set.
         */
        public fun hasAllPodcasts(): kotlin.Boolean {
            return _builder.hasAllPodcasts()
        }

        /**
         * `.google.protobuf.StringValue podcast_uuids = 5;`
         */
        public var podcastUuids: com.google.protobuf.StringValue
            @JvmName("getPodcastUuids")
            get() = _builder.getPodcastUuids()
            @JvmName("setPodcastUuids")
            set(value) {
                _builder.setPodcastUuids(value)
            }
        /**
         * `.google.protobuf.StringValue podcast_uuids = 5;`
         */
        public fun clearPodcastUuids() {
            _builder.clearPodcastUuids()
        }
        /**
         * `.google.protobuf.StringValue podcast_uuids = 5;`
         * @return Whether the podcastUuids field is set.
         */
        public fun hasPodcastUuids(): kotlin.Boolean {
            return _builder.hasPodcastUuids()
        }

        /**
         * `.google.protobuf.StringValue episode_uuids = 6;`
         */
        public var episodeUuids: com.google.protobuf.StringValue
            @JvmName("getEpisodeUuids")
            get() = _builder.getEpisodeUuids()
            @JvmName("setEpisodeUuids")
            set(value) {
                _builder.setEpisodeUuids(value)
            }
        /**
         * `.google.protobuf.StringValue episode_uuids = 6;`
         */
        public fun clearEpisodeUuids() {
            _builder.clearEpisodeUuids()
        }
        /**
         * `.google.protobuf.StringValue episode_uuids = 6;`
         * @return Whether the episodeUuids field is set.
         */
        public fun hasEpisodeUuids(): kotlin.Boolean {
            return _builder.hasEpisodeUuids()
        }

        /**
         * `.google.protobuf.Int32Value audio_video = 7;`
         */
        public var audioVideo: com.google.protobuf.Int32Value
            @JvmName("getAudioVideo")
            get() = _builder.getAudioVideo()
            @JvmName("setAudioVideo")
            set(value) {
                _builder.setAudioVideo(value)
            }
        /**
         * `.google.protobuf.Int32Value audio_video = 7;`
         */
        public fun clearAudioVideo() {
            _builder.clearAudioVideo()
        }
        /**
         * `.google.protobuf.Int32Value audio_video = 7;`
         * @return Whether the audioVideo field is set.
         */
        public fun hasAudioVideo(): kotlin.Boolean {
            return _builder.hasAudioVideo()
        }

        /**
         * `.google.protobuf.BoolValue not_downloaded = 8;`
         */
        public var notDownloaded: com.google.protobuf.BoolValue
            @JvmName("getNotDownloaded")
            get() = _builder.getNotDownloaded()
            @JvmName("setNotDownloaded")
            set(value) {
                _builder.setNotDownloaded(value)
            }
        /**
         * `.google.protobuf.BoolValue not_downloaded = 8;`
         */
        public fun clearNotDownloaded() {
            _builder.clearNotDownloaded()
        }
        /**
         * `.google.protobuf.BoolValue not_downloaded = 8;`
         * @return Whether the notDownloaded field is set.
         */
        public fun hasNotDownloaded(): kotlin.Boolean {
            return _builder.hasNotDownloaded()
        }

        /**
         * `.google.protobuf.BoolValue downloaded = 9;`
         */
        public var downloaded: com.google.protobuf.BoolValue
            @JvmName("getDownloaded")
            get() = _builder.getDownloaded()
            @JvmName("setDownloaded")
            set(value) {
                _builder.setDownloaded(value)
            }
        /**
         * `.google.protobuf.BoolValue downloaded = 9;`
         */
        public fun clearDownloaded() {
            _builder.clearDownloaded()
        }
        /**
         * `.google.protobuf.BoolValue downloaded = 9;`
         * @return Whether the downloaded field is set.
         */
        public fun hasDownloaded(): kotlin.Boolean {
            return _builder.hasDownloaded()
        }

        /**
         * `.google.protobuf.BoolValue downloading = 10;`
         */
        public var downloading: com.google.protobuf.BoolValue
            @JvmName("getDownloading")
            get() = _builder.getDownloading()
            @JvmName("setDownloading")
            set(value) {
                _builder.setDownloading(value)
            }
        /**
         * `.google.protobuf.BoolValue downloading = 10;`
         */
        public fun clearDownloading() {
            _builder.clearDownloading()
        }
        /**
         * `.google.protobuf.BoolValue downloading = 10;`
         * @return Whether the downloading field is set.
         */
        public fun hasDownloading(): kotlin.Boolean {
            return _builder.hasDownloading()
        }

        /**
         * `.google.protobuf.BoolValue finished = 11;`
         */
        public var finished: com.google.protobuf.BoolValue
            @JvmName("getFinished")
            get() = _builder.getFinished()
            @JvmName("setFinished")
            set(value) {
                _builder.setFinished(value)
            }
        /**
         * `.google.protobuf.BoolValue finished = 11;`
         */
        public fun clearFinished() {
            _builder.clearFinished()
        }
        /**
         * `.google.protobuf.BoolValue finished = 11;`
         * @return Whether the finished field is set.
         */
        public fun hasFinished(): kotlin.Boolean {
            return _builder.hasFinished()
        }

        /**
         * `.google.protobuf.BoolValue partially_played = 12;`
         */
        public var partiallyPlayed: com.google.protobuf.BoolValue
            @JvmName("getPartiallyPlayed")
            get() = _builder.getPartiallyPlayed()
            @JvmName("setPartiallyPlayed")
            set(value) {
                _builder.setPartiallyPlayed(value)
            }
        /**
         * `.google.protobuf.BoolValue partially_played = 12;`
         */
        public fun clearPartiallyPlayed() {
            _builder.clearPartiallyPlayed()
        }
        /**
         * `.google.protobuf.BoolValue partially_played = 12;`
         * @return Whether the partiallyPlayed field is set.
         */
        public fun hasPartiallyPlayed(): kotlin.Boolean {
            return _builder.hasPartiallyPlayed()
        }

        /**
         * `.google.protobuf.BoolValue unplayed = 13;`
         */
        public var unplayed: com.google.protobuf.BoolValue
            @JvmName("getUnplayed")
            get() = _builder.getUnplayed()
            @JvmName("setUnplayed")
            set(value) {
                _builder.setUnplayed(value)
            }
        /**
         * `.google.protobuf.BoolValue unplayed = 13;`
         */
        public fun clearUnplayed() {
            _builder.clearUnplayed()
        }
        /**
         * `.google.protobuf.BoolValue unplayed = 13;`
         * @return Whether the unplayed field is set.
         */
        public fun hasUnplayed(): kotlin.Boolean {
            return _builder.hasUnplayed()
        }

        /**
         * `.google.protobuf.BoolValue starred = 14;`
         */
        public var starred: com.google.protobuf.BoolValue
            @JvmName("getStarred")
            get() = _builder.getStarred()
            @JvmName("setStarred")
            set(value) {
                _builder.setStarred(value)
            }
        /**
         * `.google.protobuf.BoolValue starred = 14;`
         */
        public fun clearStarred() {
            _builder.clearStarred()
        }
        /**
         * `.google.protobuf.BoolValue starred = 14;`
         * @return Whether the starred field is set.
         */
        public fun hasStarred(): kotlin.Boolean {
            return _builder.hasStarred()
        }

        /**
         * `.google.protobuf.BoolValue manual = 15;`
         */
        public var manual: com.google.protobuf.BoolValue
            @JvmName("getManual")
            get() = _builder.getManual()
            @JvmName("setManual")
            set(value) {
                _builder.setManual(value)
            }
        /**
         * `.google.protobuf.BoolValue manual = 15;`
         */
        public fun clearManual() {
            _builder.clearManual()
        }
        /**
         * `.google.protobuf.BoolValue manual = 15;`
         * @return Whether the manual field is set.
         */
        public fun hasManual(): kotlin.Boolean {
            return _builder.hasManual()
        }

        /**
         * `.google.protobuf.Int32Value sort_position = 16;`
         */
        public var sortPosition: com.google.protobuf.Int32Value
            @JvmName("getSortPosition")
            get() = _builder.getSortPosition()
            @JvmName("setSortPosition")
            set(value) {
                _builder.setSortPosition(value)
            }
        /**
         * `.google.protobuf.Int32Value sort_position = 16;`
         */
        public fun clearSortPosition() {
            _builder.clearSortPosition()
        }
        /**
         * `.google.protobuf.Int32Value sort_position = 16;`
         * @return Whether the sortPosition field is set.
         */
        public fun hasSortPosition(): kotlin.Boolean {
            return _builder.hasSortPosition()
        }

        /**
         * `.google.protobuf.Int32Value sort_type = 17;`
         */
        public var sortType: com.google.protobuf.Int32Value
            @JvmName("getSortType")
            get() = _builder.getSortType()
            @JvmName("setSortType")
            set(value) {
                _builder.setSortType(value)
            }
        /**
         * `.google.protobuf.Int32Value sort_type = 17;`
         */
        public fun clearSortType() {
            _builder.clearSortType()
        }
        /**
         * `.google.protobuf.Int32Value sort_type = 17;`
         * @return Whether the sortType field is set.
         */
        public fun hasSortType(): kotlin.Boolean {
            return _builder.hasSortType()
        }

        /**
         * `.google.protobuf.Int32Value icon_id = 18;`
         */
        public var iconId: com.google.protobuf.Int32Value
            @JvmName("getIconId")
            get() = _builder.getIconId()
            @JvmName("setIconId")
            set(value) {
                _builder.setIconId(value)
            }
        /**
         * `.google.protobuf.Int32Value icon_id = 18;`
         */
        public fun clearIconId() {
            _builder.clearIconId()
        }
        /**
         * `.google.protobuf.Int32Value icon_id = 18;`
         * @return Whether the iconId field is set.
         */
        public fun hasIconId(): kotlin.Boolean {
            return _builder.hasIconId()
        }

        /**
         * `.google.protobuf.Int32Value filter_hours = 19;`
         */
        public var filterHours: com.google.protobuf.Int32Value
            @JvmName("getFilterHours")
            get() = _builder.getFilterHours()
            @JvmName("setFilterHours")
            set(value) {
                _builder.setFilterHours(value)
            }
        /**
         * `.google.protobuf.Int32Value filter_hours = 19;`
         */
        public fun clearFilterHours() {
            _builder.clearFilterHours()
        }
        /**
         * `.google.protobuf.Int32Value filter_hours = 19;`
         * @return Whether the filterHours field is set.
         */
        public fun hasFilterHours(): kotlin.Boolean {
            return _builder.hasFilterHours()
        }

        /**
         * `string original_uuid = 20;`
         */
        public var originalUuid: kotlin.String
            @JvmName("getOriginalUuid")
            get() = _builder.getOriginalUuid()
            @JvmName("setOriginalUuid")
            set(value) {
                _builder.setOriginalUuid(value)
            }
        /**
         * `string original_uuid = 20;`
         */
        public fun clearOriginalUuid() {
            _builder.clearOriginalUuid()
        }

        /**
         * `.google.protobuf.BoolValue filter_duration = 21;`
         */
        public var filterDuration: com.google.protobuf.BoolValue
            @JvmName("getFilterDuration")
            get() = _builder.getFilterDuration()
            @JvmName("setFilterDuration")
            set(value) {
                _builder.setFilterDuration(value)
            }
        /**
         * `.google.protobuf.BoolValue filter_duration = 21;`
         */
        public fun clearFilterDuration() {
            _builder.clearFilterDuration()
        }
        /**
         * `.google.protobuf.BoolValue filter_duration = 21;`
         * @return Whether the filterDuration field is set.
         */
        public fun hasFilterDuration(): kotlin.Boolean {
            return _builder.hasFilterDuration()
        }

        /**
         * `.google.protobuf.Int32Value longer_than = 22;`
         */
        public var longerThan: com.google.protobuf.Int32Value
            @JvmName("getLongerThan")
            get() = _builder.getLongerThan()
            @JvmName("setLongerThan")
            set(value) {
                _builder.setLongerThan(value)
            }
        /**
         * `.google.protobuf.Int32Value longer_than = 22;`
         */
        public fun clearLongerThan() {
            _builder.clearLongerThan()
        }
        /**
         * `.google.protobuf.Int32Value longer_than = 22;`
         * @return Whether the longerThan field is set.
         */
        public fun hasLongerThan(): kotlin.Boolean {
            return _builder.hasLongerThan()
        }

        /**
         * `.google.protobuf.Int32Value shorter_than = 23;`
         */
        public var shorterThan: com.google.protobuf.Int32Value
            @JvmName("getShorterThan")
            get() = _builder.getShorterThan()
            @JvmName("setShorterThan")
            set(value) {
                _builder.setShorterThan(value)
            }
        /**
         * `.google.protobuf.Int32Value shorter_than = 23;`
         */
        public fun clearShorterThan() {
            _builder.clearShorterThan()
        }
        /**
         * `.google.protobuf.Int32Value shorter_than = 23;`
         * @return Whether the shorterThan field is set.
         */
        public fun hasShorterThan(): kotlin.Boolean {
            return _builder.hasShorterThan()
        }
    }
}
public inline fun com.pocketcasts.service.api.SyncUserPlaylist.copy(block: com.pocketcasts.service.api.SyncUserPlaylistKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.SyncUserPlaylist =
    com.pocketcasts.service.api.SyncUserPlaylistKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.isDeletedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasIsDeleted()) getIsDeleted() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.titleOrNull: com.google.protobuf.StringValue?
    get() = if (hasTitle()) getTitle() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.allPodcastsOrNull: com.google.protobuf.BoolValue?
    get() = if (hasAllPodcasts()) getAllPodcasts() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.podcastUuidsOrNull: com.google.protobuf.StringValue?
    get() = if (hasPodcastUuids()) getPodcastUuids() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.episodeUuidsOrNull: com.google.protobuf.StringValue?
    get() = if (hasEpisodeUuids()) getEpisodeUuids() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.audioVideoOrNull: com.google.protobuf.Int32Value?
    get() = if (hasAudioVideo()) getAudioVideo() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.notDownloadedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasNotDownloaded()) getNotDownloaded() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.downloadedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasDownloaded()) getDownloaded() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.downloadingOrNull: com.google.protobuf.BoolValue?
    get() = if (hasDownloading()) getDownloading() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.finishedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasFinished()) getFinished() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.partiallyPlayedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasPartiallyPlayed()) getPartiallyPlayed() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.unplayedOrNull: com.google.protobuf.BoolValue?
    get() = if (hasUnplayed()) getUnplayed() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.starredOrNull: com.google.protobuf.BoolValue?
    get() = if (hasStarred()) getStarred() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.manualOrNull: com.google.protobuf.BoolValue?
    get() = if (hasManual()) getManual() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.sortPositionOrNull: com.google.protobuf.Int32Value?
    get() = if (hasSortPosition()) getSortPosition() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.sortTypeOrNull: com.google.protobuf.Int32Value?
    get() = if (hasSortType()) getSortType() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.iconIdOrNull: com.google.protobuf.Int32Value?
    get() = if (hasIconId()) getIconId() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.filterHoursOrNull: com.google.protobuf.Int32Value?
    get() = if (hasFilterHours()) getFilterHours() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.filterDurationOrNull: com.google.protobuf.BoolValue?
    get() = if (hasFilterDuration()) getFilterDuration() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.longerThanOrNull: com.google.protobuf.Int32Value?
    get() = if (hasLongerThan()) getLongerThan() else null

public val com.pocketcasts.service.api.SyncUserPlaylistOrBuilder.shorterThanOrNull: com.google.protobuf.Int32Value?
    get() = if (hasShorterThan()) getShorterThan() else null
