// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.TokenLoginResponse}
 */
public  final class TokenLoginResponse extends
    com.google.protobuf.GeneratedMessageLite<
        TokenLoginResponse, TokenLoginResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.TokenLoginResponse)
    TokenLoginResponseOrBuilder {
  private TokenLoginResponse() {
    email_ = "";
    uuid_ = "";
    accessToken_ = "";
    tokenType_ = "";
    refreshToken_ = "";
  }
  public static final int EMAIL_FIELD_NUMBER = 1;
  private java.lang.String email_;
  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    return email_;
  }
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(email_);
  }
  /**
   * <code>string email = 1;</code>
   * @param value The email to set.
   */
  private void setEmail(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    email_ = value;
  }
  /**
   * <code>string email = 1;</code>
   */
  private void clearEmail() {

    email_ = getDefaultInstance().getEmail();
  }
  /**
   * <code>string email = 1;</code>
   * @param value The bytes for email to set.
   */
  private void setEmailBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    email_ = value.toStringUtf8();

  }

  public static final int UUID_FIELD_NUMBER = 2;
  private java.lang.String uuid_;
  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    return uuid_;
  }
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uuid_);
  }
  /**
   * <code>string uuid = 2;</code>
   * @param value The uuid to set.
   */
  private void setUuid(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    uuid_ = value;
  }
  /**
   * <code>string uuid = 2;</code>
   */
  private void clearUuid() {

    uuid_ = getDefaultInstance().getUuid();
  }
  /**
   * <code>string uuid = 2;</code>
   * @param value The bytes for uuid to set.
   */
  private void setUuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uuid_ = value.toStringUtf8();

  }

  public static final int IS_NEW_FIELD_NUMBER = 3;
  private boolean isNew_;
  /**
   * <code>bool is_new = 3;</code>
   * @return The isNew.
   */
  @java.lang.Override
  public boolean getIsNew() {
    return isNew_;
  }
  /**
   * <code>bool is_new = 3;</code>
   * @param value The isNew to set.
   */
  private void setIsNew(boolean value) {
    
    isNew_ = value;
  }
  /**
   * <code>bool is_new = 3;</code>
   */
  private void clearIsNew() {

    isNew_ = false;
  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 4;
  private java.lang.String accessToken_;
  /**
   * <code>string access_token = 4;</code>
   * @return The accessToken.
   */
  @java.lang.Override
  public java.lang.String getAccessToken() {
    return accessToken_;
  }
  /**
   * <code>string access_token = 4;</code>
   * @return The bytes for accessToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(accessToken_);
  }
  /**
   * <code>string access_token = 4;</code>
   * @param value The accessToken to set.
   */
  private void setAccessToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    accessToken_ = value;
  }
  /**
   * <code>string access_token = 4;</code>
   */
  private void clearAccessToken() {

    accessToken_ = getDefaultInstance().getAccessToken();
  }
  /**
   * <code>string access_token = 4;</code>
   * @param value The bytes for accessToken to set.
   */
  private void setAccessTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    accessToken_ = value.toStringUtf8();

  }

  public static final int TOKEN_TYPE_FIELD_NUMBER = 5;
  private java.lang.String tokenType_;
  /**
   * <code>string token_type = 5;</code>
   * @return The tokenType.
   */
  @java.lang.Override
  public java.lang.String getTokenType() {
    return tokenType_;
  }
  /**
   * <code>string token_type = 5;</code>
   * @return The bytes for tokenType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tokenType_);
  }
  /**
   * <code>string token_type = 5;</code>
   * @param value The tokenType to set.
   */
  private void setTokenType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    tokenType_ = value;
  }
  /**
   * <code>string token_type = 5;</code>
   */
  private void clearTokenType() {

    tokenType_ = getDefaultInstance().getTokenType();
  }
  /**
   * <code>string token_type = 5;</code>
   * @param value The bytes for tokenType to set.
   */
  private void setTokenTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tokenType_ = value.toStringUtf8();

  }

  public static final int EXPIRES_IN_FIELD_NUMBER = 6;
  private int expiresIn_;
  /**
   * <code>int32 expires_in = 6;</code>
   * @return The expiresIn.
   */
  @java.lang.Override
  public int getExpiresIn() {
    return expiresIn_;
  }
  /**
   * <code>int32 expires_in = 6;</code>
   * @param value The expiresIn to set.
   */
  private void setExpiresIn(int value) {
    
    expiresIn_ = value;
  }
  /**
   * <code>int32 expires_in = 6;</code>
   */
  private void clearExpiresIn() {

    expiresIn_ = 0;
  }

  public static final int REFRESH_TOKEN_FIELD_NUMBER = 7;
  private java.lang.String refreshToken_;
  /**
   * <code>string refresh_token = 7;</code>
   * @return The refreshToken.
   */
  @java.lang.Override
  public java.lang.String getRefreshToken() {
    return refreshToken_;
  }
  /**
   * <code>string refresh_token = 7;</code>
   * @return The bytes for refreshToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefreshTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(refreshToken_);
  }
  /**
   * <code>string refresh_token = 7;</code>
   * @param value The refreshToken to set.
   */
  private void setRefreshToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    refreshToken_ = value;
  }
  /**
   * <code>string refresh_token = 7;</code>
   */
  private void clearRefreshToken() {

    refreshToken_ = getDefaultInstance().getRefreshToken();
  }
  /**
   * <code>string refresh_token = 7;</code>
   * @param value The bytes for refreshToken to set.
   */
  private void setRefreshTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    refreshToken_ = value.toStringUtf8();

  }

  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.TokenLoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.TokenLoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.TokenLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.TokenLoginResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.TokenLoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.TokenLoginResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TokenLoginResponse)
      com.pocketcasts.service.api.TokenLoginResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.TokenLoginResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return instance.getEmail();
    }
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return instance.getEmailBytes();
    }
    /**
     * <code>string email = 1;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      copyOnWrite();
      instance.setEmail(value);
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      copyOnWrite();
      instance.clearEmail();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmailBytes(value);
      return this;
    }

    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      return instance.getUuid();
    }
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      return instance.getUuidBytes();
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setUuid(value);
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      copyOnWrite();
      instance.clearUuid();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUuidBytes(value);
      return this;
    }

    /**
     * <code>bool is_new = 3;</code>
     * @return The isNew.
     */
    @java.lang.Override
    public boolean getIsNew() {
      return instance.getIsNew();
    }
    /**
     * <code>bool is_new = 3;</code>
     * @param value The isNew to set.
     * @return This builder for chaining.
     */
    public Builder setIsNew(boolean value) {
      copyOnWrite();
      instance.setIsNew(value);
      return this;
    }
    /**
     * <code>bool is_new = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNew() {
      copyOnWrite();
      instance.clearIsNew();
      return this;
    }

    /**
     * <code>string access_token = 4;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      return instance.getAccessToken();
    }
    /**
     * <code>string access_token = 4;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      return instance.getAccessTokenBytes();
    }
    /**
     * <code>string access_token = 4;</code>
     * @param value The accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setAccessToken(value);
      return this;
    }
    /**
     * <code>string access_token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessToken() {
      copyOnWrite();
      instance.clearAccessToken();
      return this;
    }
    /**
     * <code>string access_token = 4;</code>
     * @param value The bytes for accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAccessTokenBytes(value);
      return this;
    }

    /**
     * <code>string token_type = 5;</code>
     * @return The tokenType.
     */
    @java.lang.Override
    public java.lang.String getTokenType() {
      return instance.getTokenType();
    }
    /**
     * <code>string token_type = 5;</code>
     * @return The bytes for tokenType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenTypeBytes() {
      return instance.getTokenTypeBytes();
    }
    /**
     * <code>string token_type = 5;</code>
     * @param value The tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenType(
        java.lang.String value) {
      copyOnWrite();
      instance.setTokenType(value);
      return this;
    }
    /**
     * <code>string token_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenType() {
      copyOnWrite();
      instance.clearTokenType();
      return this;
    }
    /**
     * <code>string token_type = 5;</code>
     * @param value The bytes for tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenTypeBytes(value);
      return this;
    }

    /**
     * <code>int32 expires_in = 6;</code>
     * @return The expiresIn.
     */
    @java.lang.Override
    public int getExpiresIn() {
      return instance.getExpiresIn();
    }
    /**
     * <code>int32 expires_in = 6;</code>
     * @param value The expiresIn to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresIn(int value) {
      copyOnWrite();
      instance.setExpiresIn(value);
      return this;
    }
    /**
     * <code>int32 expires_in = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresIn() {
      copyOnWrite();
      instance.clearExpiresIn();
      return this;
    }

    /**
     * <code>string refresh_token = 7;</code>
     * @return The refreshToken.
     */
    @java.lang.Override
    public java.lang.String getRefreshToken() {
      return instance.getRefreshToken();
    }
    /**
     * <code>string refresh_token = 7;</code>
     * @return The bytes for refreshToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      return instance.getRefreshTokenBytes();
    }
    /**
     * <code>string refresh_token = 7;</code>
     * @param value The refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setRefreshToken(value);
      return this;
    }
    /**
     * <code>string refresh_token = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefreshToken() {
      copyOnWrite();
      instance.clearRefreshToken();
      return this;
    }
    /**
     * <code>string refresh_token = 7;</code>
     * @param value The bytes for refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRefreshTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.TokenLoginResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.TokenLoginResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "email_",
            "uuid_",
            "isNew_",
            "accessToken_",
            "tokenType_",
            "expiresIn_",
            "refreshToken_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0007\u0004\u0208\u0005\u0208\u0006\u0004\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.TokenLoginResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.TokenLoginResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.TokenLoginResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.TokenLoginResponse)
  private static final com.pocketcasts.service.api.TokenLoginResponse DEFAULT_INSTANCE;
  static {
    TokenLoginResponse defaultInstance = new TokenLoginResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TokenLoginResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.TokenLoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TokenLoginResponse> PARSER;

  public static com.google.protobuf.Parser<TokenLoginResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

