// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface TokenLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TokenLoginRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id_token = 1;</code>
   * @return The idToken.
   */
  java.lang.String getIdToken();
  /**
   * <code>string id_token = 1;</code>
   * @return The bytes for idToken.
   */
  com.google.protobuf.ByteString
      getIdTokenBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string scope = 4;</code>
   * @return The scope.
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 4;</code>
   * @return The bytes for scope.
   */
  com.google.protobuf.ByteString
      getScopeBytes();
}
