// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializeupdateEpisodeStarRequest")
public inline fun updateEpisodeStarRequest(block: com.pocketcasts.service.api.UpdateEpisodeStarRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.UpdateEpisodeStarRequest =
    com.pocketcasts.service.api.UpdateEpisodeStarRequestKt.Dsl._create(com.pocketcasts.service.api.UpdateEpisodeStarRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.UpdateEpisodeStarRequest`
 */
public object UpdateEpisodeStarRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.UpdateEpisodeStarRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.UpdateEpisodeStarRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.UpdateEpisodeStarRequest = _builder.build()

        /**
         * `string uuid = 1;`
         */
        public var uuid: kotlin.String
            @JvmName("getUuid")
            get() = _builder.getUuid()
            @JvmName("setUuid")
            set(value) {
                _builder.setUuid(value)
            }
        /**
         * `string uuid = 1;`
         */
        public fun clearUuid() {
            _builder.clearUuid()
        }

        /**
         * `string podcast = 2;`
         */
        public var podcast: kotlin.String
            @JvmName("getPodcast")
            get() = _builder.getPodcast()
            @JvmName("setPodcast")
            set(value) {
                _builder.setPodcast(value)
            }
        /**
         * `string podcast = 2;`
         */
        public fun clearPodcast() {
            _builder.clearPodcast()
        }

        /**
         * <code>bool star = 3;</code>
         */
        public var star: kotlin.Boolean
            @JvmName("getStar")
            get() = _builder.getStar()
            @JvmName("setStar")
            set(value) {
                _builder.setStar(value)
            }
        /**
         * `bool star = 3;`
         */
        public fun clearStar() {
            _builder.clearStar()
        }
    }
}
public inline fun com.pocketcasts.service.api.UpdateEpisodeStarRequest.copy(block: com.pocketcasts.service.api.UpdateEpisodeStarRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.UpdateEpisodeStarRequest =
    com.pocketcasts.service.api.UpdateEpisodeStarRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
