// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UpdateEpisodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpdateEpisodeRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string podcast = 2;</code>
   * @return The podcast.
   */
  java.lang.String getPodcast();
  /**
   * <code>string podcast = 2;</code>
   * @return The bytes for podcast.
   */
  com.google.protobuf.ByteString
      getPodcastBytes();

  /**
   * <code>.google.protobuf.Int32Value position = 3;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.google.protobuf.Int32Value position = 3;</code>
   * @return The position.
   */
  com.google.protobuf.Int32Value getPosition();

  /**
   * <code>int32 status = 4;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 duration = 5;</code>
   * @return The duration.
   */
  int getDuration();

  /**
   * <code>.api.StatsRequest stats = 6;</code>
   * @return Whether the stats field is set.
   */
  boolean hasStats();
  /**
   * <code>.api.StatsRequest stats = 6;</code>
   * @return The stats.
   */
  com.pocketcasts.service.api.StatsRequest getStats();
}
