// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UpdateEpisodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpdateEpisodeResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
