// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UpNextChangesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpNextChanges)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 server_modified = 1;</code>
   * @return The serverModified.
   */
  long getServerModified();

  /**
   * <code>repeated .api.UpNextChanges.Change changes = 2;</code>
   */
  java.util.List<com.pocketcasts.service.api.UpNextChanges.Change> 
      getChangesList();
  /**
   * <code>repeated .api.UpNextChanges.Change changes = 2;</code>
   */
  com.pocketcasts.service.api.UpNextChanges.Change getChanges(int index);
  /**
   * <code>repeated .api.UpNextChanges.Change changes = 2;</code>
   */
  int getChangesCount();

  /**
   * <code>repeated string order = 3;</code>
   * @return A list containing the order.
   */
  java.util.List<java.lang.String>
      getOrderList();
  /**
   * <code>repeated string order = 3;</code>
   * @return The count of order.
   */
  int getOrderCount();
  /**
   * <code>repeated string order = 3;</code>
   * @param index The index of the element to return.
   * @return The order at the given index.
   */
  java.lang.String getOrder(int index);
  /**
   * <code>repeated string order = 3;</code>
   * @param index The index of the element to return.
   * @return The order at the given index.
   */
  com.google.protobuf.ByteString
      getOrderBytes(int index);
}
