// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UpNextSyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpNextSyncRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 device_time = 1;</code>
   * @return The deviceTime.
   */
  long getDeviceTime();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string model = 3;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 3;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>.api.UpNextChanges up_next = 4;</code>
   * @return Whether the upNext field is set.
   */
  boolean hasUpNext();
  /**
   * <code>.api.UpNextChanges up_next = 4;</code>
   * @return The upNext.
   */
  com.pocketcasts.service.api.UpNextChanges getUpNext();

  /**
   * <code>bool show_play_status = 5;</code>
   * @return The showPlayStatus.
   */
  boolean getShowPlayStatus();
}
