// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UpNextResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpNextResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 server_modified = 1;</code>
   * @return The serverModified.
   */
  long getServerModified();

  /**
   * <code>repeated .api.UpNextResponse.EpisodeResponse episodes = 4;</code>
   */
  java.util.List<com.pocketcasts.service.api.UpNextResponse.EpisodeResponse> 
      getEpisodesList();
  /**
   * <code>repeated .api.UpNextResponse.EpisodeResponse episodes = 4;</code>
   */
  com.pocketcasts.service.api.UpNextResponse.EpisodeResponse getEpisodes(int index);
  /**
   * <code>repeated .api.UpNextResponse.EpisodeResponse episodes = 4;</code>
   */
  int getEpisodesCount();

  /**
   * <code>repeated .api.UpNextResponse.EpisodeSyncResponse episodeSync = 5;</code>
   */
  java.util.List<com.pocketcasts.service.api.UpNextResponse.EpisodeSyncResponse> 
      getEpisodeSyncList();
  /**
   * <code>repeated .api.UpNextResponse.EpisodeSyncResponse episodeSync = 5;</code>
   */
  com.pocketcasts.service.api.UpNextResponse.EpisodeSyncResponse getEpisodeSync(int index);
  /**
   * <code>repeated .api.UpNextResponse.EpisodeSyncResponse episodeSync = 5;</code>
   */
  int getEpisodeSyncCount();
}
