// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.UpNextPlayRequest}
 */
public  final class UpNextPlayRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UpNextPlayRequest, UpNextPlayRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:api.UpNextPlayRequest)
    UpNextPlayRequestOrBuilder {
  private UpNextPlayRequest() {
    version_ = "";
    model_ = "";
  }
  public static final int VERSION_FIELD_NUMBER = 1;
  private java.lang.String version_;
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    return version_;
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(version_);
  }
  /**
   * <code>string version = 1;</code>
   * @param value The version to set.
   */
  private void setVersion(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    version_ = value;
  }
  /**
   * <code>string version = 1;</code>
   */
  private void clearVersion() {

    version_ = getDefaultInstance().getVersion();
  }
  /**
   * <code>string version = 1;</code>
   * @param value The bytes for version to set.
   */
  private void setVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    version_ = value.toStringUtf8();

  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private java.lang.String model_;
  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    return model_;
  }
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(model_);
  }
  /**
   * <code>string model = 2;</code>
   * @param value The model to set.
   */
  private void setModel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    model_ = value;
  }
  /**
   * <code>string model = 2;</code>
   */
  private void clearModel() {

    model_ = getDefaultInstance().getModel();
  }
  /**
   * <code>string model = 2;</code>
   * @param value The bytes for model to set.
   */
  private void setModelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    model_ = value.toStringUtf8();

  }

  public static final int EPISODE_FIELD_NUMBER = 3;
  private com.pocketcasts.service.api.UpNextEpisodeRequest episode_;
  /**
   * <code>.api.UpNextEpisodeRequest episode = 3;</code>
   */
  @java.lang.Override
  public boolean hasEpisode() {
    return episode_ != null;
  }
  /**
   * <code>.api.UpNextEpisodeRequest episode = 3;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.UpNextEpisodeRequest getEpisode() {
    return episode_ == null ? com.pocketcasts.service.api.UpNextEpisodeRequest.getDefaultInstance() : episode_;
  }
  /**
   * <code>.api.UpNextEpisodeRequest episode = 3;</code>
   */
  private void setEpisode(com.pocketcasts.service.api.UpNextEpisodeRequest value) {
    value.getClass();
  episode_ = value;

    }
  /**
   * <code>.api.UpNextEpisodeRequest episode = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeEpisode(com.pocketcasts.service.api.UpNextEpisodeRequest value) {
    value.getClass();
  if (episode_ != null &&
        episode_ != com.pocketcasts.service.api.UpNextEpisodeRequest.getDefaultInstance()) {
      episode_ =
        com.pocketcasts.service.api.UpNextEpisodeRequest.newBuilder(episode_).mergeFrom(value).buildPartial();
    } else {
      episode_ = value;
    }

  }
  /**
   * <code>.api.UpNextEpisodeRequest episode = 3;</code>
   */
  private void clearEpisode() {  episode_ = null;

  }

  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.UpNextPlayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.UpNextPlayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UpNextPlayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.UpNextPlayRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.UpNextPlayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.UpNextPlayRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.UpNextPlayRequest)
      com.pocketcasts.service.api.UpNextPlayRequestOrBuilder {
    // Construct using com.pocketcasts.service.api.UpNextPlayRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return instance.getVersionBytes();
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionBytes(value);
      return this;
    }

    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      return instance.getModel();
    }
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      return instance.getModelBytes();
    }
    /**
     * <code>string model = 2;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      copyOnWrite();
      instance.setModel(value);
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      copyOnWrite();
      instance.clearModel();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setModelBytes(value);
      return this;
    }

    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    @java.lang.Override
    public boolean hasEpisode() {
      return instance.hasEpisode();
    }
    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.UpNextEpisodeRequest getEpisode() {
      return instance.getEpisode();
    }
    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    public Builder setEpisode(com.pocketcasts.service.api.UpNextEpisodeRequest value) {
      copyOnWrite();
      instance.setEpisode(value);
      return this;
      }
    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    public Builder setEpisode(
        com.pocketcasts.service.api.UpNextEpisodeRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setEpisode(builderForValue.build());
      return this;
    }
    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    public Builder mergeEpisode(com.pocketcasts.service.api.UpNextEpisodeRequest value) {
      copyOnWrite();
      instance.mergeEpisode(value);
      return this;
    }
    /**
     * <code>.api.UpNextEpisodeRequest episode = 3;</code>
     */
    public Builder clearEpisode() {  copyOnWrite();
      instance.clearEpisode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.UpNextPlayRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.UpNextPlayRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "version_",
            "model_",
            "episode_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.UpNextPlayRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.UpNextPlayRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.UpNextPlayRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.UpNextPlayRequest)
  private static final com.pocketcasts.service.api.UpNextPlayRequest DEFAULT_INSTANCE;
  static {
    UpNextPlayRequest defaultInstance = new UpNextPlayRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpNextPlayRequest.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.UpNextPlayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpNextPlayRequest> PARSER;

  public static com.google.protobuf.Parser<UpNextPlayRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

