// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.UserPodcastListResponse}
 */
public  final class UserPodcastListResponse extends
    com.google.protobuf.GeneratedMessageLite<
        UserPodcastListResponse, UserPodcastListResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.UserPodcastListResponse)
    UserPodcastListResponseOrBuilder {
  private UserPodcastListResponse() {
    podcasts_ = emptyProtobufList();
    folders_ = emptyProtobufList();
  }
  public static final int PODCASTS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.UserPodcastResponse> podcasts_;
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.pocketcasts.service.api.UserPodcastResponse> getPodcastsList() {
    return podcasts_;
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  public java.util.List<? extends com.pocketcasts.service.api.UserPodcastResponseOrBuilder> 
      getPodcastsOrBuilderList() {
    return podcasts_;
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  @java.lang.Override
  public int getPodcastsCount() {
    return podcasts_.size();
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.UserPodcastResponse getPodcasts(int index) {
    return podcasts_.get(index);
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  public com.pocketcasts.service.api.UserPodcastResponseOrBuilder getPodcastsOrBuilder(
      int index) {
    return podcasts_.get(index);
  }
  private void ensurePodcastsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.UserPodcastResponse> tmp = podcasts_;
    if (!tmp.isModifiable()) {
      podcasts_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void setPodcasts(
      int index, com.pocketcasts.service.api.UserPodcastResponse value) {
    value.getClass();
  ensurePodcastsIsMutable();
    podcasts_.set(index, value);
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void addPodcasts(com.pocketcasts.service.api.UserPodcastResponse value) {
    value.getClass();
  ensurePodcastsIsMutable();
    podcasts_.add(value);
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void addPodcasts(
      int index, com.pocketcasts.service.api.UserPodcastResponse value) {
    value.getClass();
  ensurePodcastsIsMutable();
    podcasts_.add(index, value);
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void addAllPodcasts(
      java.lang.Iterable<? extends com.pocketcasts.service.api.UserPodcastResponse> values) {
    ensurePodcastsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, podcasts_);
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void clearPodcasts() {
    podcasts_ = emptyProtobufList();
  }
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  private void removePodcasts(int index) {
    ensurePodcastsIsMutable();
    podcasts_.remove(index);
  }

  public static final int FOLDERS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.PodcastFolder> folders_;
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.pocketcasts.service.api.PodcastFolder> getFoldersList() {
    return folders_;
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  public java.util.List<? extends com.pocketcasts.service.api.PodcastFolderOrBuilder> 
      getFoldersOrBuilderList() {
    return folders_;
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  @java.lang.Override
  public int getFoldersCount() {
    return folders_.size();
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  @java.lang.Override
  public com.pocketcasts.service.api.PodcastFolder getFolders(int index) {
    return folders_.get(index);
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  public com.pocketcasts.service.api.PodcastFolderOrBuilder getFoldersOrBuilder(
      int index) {
    return folders_.get(index);
  }
  private void ensureFoldersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.pocketcasts.service.api.PodcastFolder> tmp = folders_;
    if (!tmp.isModifiable()) {
      folders_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void setFolders(
      int index, com.pocketcasts.service.api.PodcastFolder value) {
    value.getClass();
  ensureFoldersIsMutable();
    folders_.set(index, value);
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void addFolders(com.pocketcasts.service.api.PodcastFolder value) {
    value.getClass();
  ensureFoldersIsMutable();
    folders_.add(value);
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void addFolders(
      int index, com.pocketcasts.service.api.PodcastFolder value) {
    value.getClass();
  ensureFoldersIsMutable();
    folders_.add(index, value);
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void addAllFolders(
      java.lang.Iterable<? extends com.pocketcasts.service.api.PodcastFolder> values) {
    ensureFoldersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, folders_);
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void clearFolders() {
    folders_ = emptyProtobufList();
  }
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  private void removeFolders(int index) {
    ensureFoldersIsMutable();
    folders_.remove(index);
  }

  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.UserPodcastListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.UserPodcastListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserPodcastListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.UserPodcastListResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.UserPodcastListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.UserPodcastListResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.UserPodcastListResponse)
      com.pocketcasts.service.api.UserPodcastListResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.UserPodcastListResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.pocketcasts.service.api.UserPodcastResponse> getPodcastsList() {
      return java.util.Collections.unmodifiableList(
          instance.getPodcastsList());
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    @java.lang.Override
    public int getPodcastsCount() {
      return instance.getPodcastsCount();
    }/**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.UserPodcastResponse getPodcasts(int index) {
      return instance.getPodcasts(index);
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder setPodcasts(
        int index, com.pocketcasts.service.api.UserPodcastResponse value) {
      copyOnWrite();
      instance.setPodcasts(index, value);
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder setPodcasts(
        int index, com.pocketcasts.service.api.UserPodcastResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setPodcasts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder addPodcasts(com.pocketcasts.service.api.UserPodcastResponse value) {
      copyOnWrite();
      instance.addPodcasts(value);
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder addPodcasts(
        int index, com.pocketcasts.service.api.UserPodcastResponse value) {
      copyOnWrite();
      instance.addPodcasts(index, value);
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder addPodcasts(
        com.pocketcasts.service.api.UserPodcastResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addPodcasts(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder addPodcasts(
        int index, com.pocketcasts.service.api.UserPodcastResponse.Builder builderForValue) {
      copyOnWrite();
      instance.addPodcasts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder addAllPodcasts(
        java.lang.Iterable<? extends com.pocketcasts.service.api.UserPodcastResponse> values) {
      copyOnWrite();
      instance.addAllPodcasts(values);
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder clearPodcasts() {
      copyOnWrite();
      instance.clearPodcasts();
      return this;
    }
    /**
     * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
     */
    public Builder removePodcasts(int index) {
      copyOnWrite();
      instance.removePodcasts(index);
      return this;
    }

    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.pocketcasts.service.api.PodcastFolder> getFoldersList() {
      return java.util.Collections.unmodifiableList(
          instance.getFoldersList());
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    @java.lang.Override
    public int getFoldersCount() {
      return instance.getFoldersCount();
    }/**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    @java.lang.Override
    public com.pocketcasts.service.api.PodcastFolder getFolders(int index) {
      return instance.getFolders(index);
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder setFolders(
        int index, com.pocketcasts.service.api.PodcastFolder value) {
      copyOnWrite();
      instance.setFolders(index, value);
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder setFolders(
        int index, com.pocketcasts.service.api.PodcastFolder.Builder builderForValue) {
      copyOnWrite();
      instance.setFolders(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder addFolders(com.pocketcasts.service.api.PodcastFolder value) {
      copyOnWrite();
      instance.addFolders(value);
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder addFolders(
        int index, com.pocketcasts.service.api.PodcastFolder value) {
      copyOnWrite();
      instance.addFolders(index, value);
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder addFolders(
        com.pocketcasts.service.api.PodcastFolder.Builder builderForValue) {
      copyOnWrite();
      instance.addFolders(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder addFolders(
        int index, com.pocketcasts.service.api.PodcastFolder.Builder builderForValue) {
      copyOnWrite();
      instance.addFolders(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder addAllFolders(
        java.lang.Iterable<? extends com.pocketcasts.service.api.PodcastFolder> values) {
      copyOnWrite();
      instance.addAllFolders(values);
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder clearFolders() {
      copyOnWrite();
      instance.clearFolders();
      return this;
    }
    /**
     * <code>repeated .api.PodcastFolder folders = 2;</code>
     */
    public Builder removeFolders(int index) {
      copyOnWrite();
      instance.removeFolders(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.UserPodcastListResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.UserPodcastListResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "podcasts_",
            com.pocketcasts.service.api.UserPodcastResponse.class,
            "folders_",
            com.pocketcasts.service.api.PodcastFolder.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u001b\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.UserPodcastListResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.UserPodcastListResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.UserPodcastListResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.UserPodcastListResponse)
  private static final com.pocketcasts.service.api.UserPodcastListResponse DEFAULT_INSTANCE;
  static {
    UserPodcastListResponse defaultInstance = new UserPodcastListResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserPodcastListResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.UserPodcastListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserPodcastListResponse> PARSER;

  public static com.google.protobuf.Parser<UserPodcastListResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

