// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UserPodcastListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UserPodcastListResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  java.util.List<com.pocketcasts.service.api.UserPodcastResponse> 
      getPodcastsList();
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  com.pocketcasts.service.api.UserPodcastResponse getPodcasts(int index);
  /**
   * <code>repeated .api.UserPodcastResponse podcasts = 1;</code>
   */
  int getPodcastsCount();

  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  java.util.List<com.pocketcasts.service.api.PodcastFolder> 
      getFoldersList();
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  com.pocketcasts.service.api.PodcastFolder getFolders(int index);
  /**
   * <code>repeated .api.PodcastFolder folders = 2;</code>
   */
  int getFoldersCount();
}
