// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UserChangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UserChangeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.google.protobuf.BoolValue success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.google.protobuf.BoolValue success = 1;</code>
   * @return The success.
   */
  com.google.protobuf.BoolValue getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string messageId = 3;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 3;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();
}
