// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.UserTokenRequest}
 */
public  final class UserTokenRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UserTokenRequest, UserTokenRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:api.UserTokenRequest)
    UserTokenRequestOrBuilder {
  private UserTokenRequest() {
    code_ = "";
    grantType_ = "";
    refreshToken_ = "";
    scope_ = "";
  }
  public static final int CODE_FIELD_NUMBER = 1;
  private java.lang.String code_;
  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    return code_;
  }
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(code_);
  }
  /**
   * <code>string code = 1;</code>
   * @param value The code to set.
   */
  private void setCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    code_ = value;
  }
  /**
   * <code>string code = 1;</code>
   */
  private void clearCode() {

    code_ = getDefaultInstance().getCode();
  }
  /**
   * <code>string code = 1;</code>
   * @param value The bytes for code to set.
   */
  private void setCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    code_ = value.toStringUtf8();

  }

  public static final int GRANT_TYPE_FIELD_NUMBER = 2;
  private java.lang.String grantType_;
  /**
   * <code>string grant_type = 2;</code>
   * @return The grantType.
   */
  @java.lang.Override
  public java.lang.String getGrantType() {
    return grantType_;
  }
  /**
   * <code>string grant_type = 2;</code>
   * @return The bytes for grantType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGrantTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(grantType_);
  }
  /**
   * <code>string grant_type = 2;</code>
   * @param value The grantType to set.
   */
  private void setGrantType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    grantType_ = value;
  }
  /**
   * <code>string grant_type = 2;</code>
   */
  private void clearGrantType() {

    grantType_ = getDefaultInstance().getGrantType();
  }
  /**
   * <code>string grant_type = 2;</code>
   * @param value The bytes for grantType to set.
   */
  private void setGrantTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    grantType_ = value.toStringUtf8();

  }

  public static final int REFRESH_TOKEN_FIELD_NUMBER = 3;
  private java.lang.String refreshToken_;
  /**
   * <code>string refresh_token = 3;</code>
   * @return The refreshToken.
   */
  @java.lang.Override
  public java.lang.String getRefreshToken() {
    return refreshToken_;
  }
  /**
   * <code>string refresh_token = 3;</code>
   * @return The bytes for refreshToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefreshTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(refreshToken_);
  }
  /**
   * <code>string refresh_token = 3;</code>
   * @param value The refreshToken to set.
   */
  private void setRefreshToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    refreshToken_ = value;
  }
  /**
   * <code>string refresh_token = 3;</code>
   */
  private void clearRefreshToken() {

    refreshToken_ = getDefaultInstance().getRefreshToken();
  }
  /**
   * <code>string refresh_token = 3;</code>
   * @param value The bytes for refreshToken to set.
   */
  private void setRefreshTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    refreshToken_ = value.toStringUtf8();

  }

  public static final int SCOPE_FIELD_NUMBER = 4;
  private java.lang.String scope_;
  /**
   * <code>string scope = 4;</code>
   * @return The scope.
   */
  @java.lang.Override
  public java.lang.String getScope() {
    return scope_;
  }
  /**
   * <code>string scope = 4;</code>
   * @return The bytes for scope.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(scope_);
  }
  /**
   * <code>string scope = 4;</code>
   * @param value The scope to set.
   */
  private void setScope(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    scope_ = value;
  }
  /**
   * <code>string scope = 4;</code>
   */
  private void clearScope() {

    scope_ = getDefaultInstance().getScope();
  }
  /**
   * <code>string scope = 4;</code>
   * @param value The bytes for scope to set.
   */
  private void setScopeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    scope_ = value.toStringUtf8();

  }

  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.UserTokenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.UserTokenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserTokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.UserTokenRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.UserTokenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.UserTokenRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.UserTokenRequest)
      com.pocketcasts.service.api.UserTokenRequestOrBuilder {
    // Construct using com.pocketcasts.service.api.UserTokenRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      return instance.getCode();
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      return instance.getCodeBytes();
    }
    /**
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCodeBytes(value);
      return this;
    }

    /**
     * <code>string grant_type = 2;</code>
     * @return The grantType.
     */
    @java.lang.Override
    public java.lang.String getGrantType() {
      return instance.getGrantType();
    }
    /**
     * <code>string grant_type = 2;</code>
     * @return The bytes for grantType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrantTypeBytes() {
      return instance.getGrantTypeBytes();
    }
    /**
     * <code>string grant_type = 2;</code>
     * @param value The grantType to set.
     * @return This builder for chaining.
     */
    public Builder setGrantType(
        java.lang.String value) {
      copyOnWrite();
      instance.setGrantType(value);
      return this;
    }
    /**
     * <code>string grant_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrantType() {
      copyOnWrite();
      instance.clearGrantType();
      return this;
    }
    /**
     * <code>string grant_type = 2;</code>
     * @param value The bytes for grantType to set.
     * @return This builder for chaining.
     */
    public Builder setGrantTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGrantTypeBytes(value);
      return this;
    }

    /**
     * <code>string refresh_token = 3;</code>
     * @return The refreshToken.
     */
    @java.lang.Override
    public java.lang.String getRefreshToken() {
      return instance.getRefreshToken();
    }
    /**
     * <code>string refresh_token = 3;</code>
     * @return The bytes for refreshToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      return instance.getRefreshTokenBytes();
    }
    /**
     * <code>string refresh_token = 3;</code>
     * @param value The refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setRefreshToken(value);
      return this;
    }
    /**
     * <code>string refresh_token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefreshToken() {
      copyOnWrite();
      instance.clearRefreshToken();
      return this;
    }
    /**
     * <code>string refresh_token = 3;</code>
     * @param value The bytes for refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRefreshTokenBytes(value);
      return this;
    }

    /**
     * <code>string scope = 4;</code>
     * @return The scope.
     */
    @java.lang.Override
    public java.lang.String getScope() {
      return instance.getScope();
    }
    /**
     * <code>string scope = 4;</code>
     * @return The bytes for scope.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScopeBytes() {
      return instance.getScopeBytes();
    }
    /**
     * <code>string scope = 4;</code>
     * @param value The scope to set.
     * @return This builder for chaining.
     */
    public Builder setScope(
        java.lang.String value) {
      copyOnWrite();
      instance.setScope(value);
      return this;
    }
    /**
     * <code>string scope = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      copyOnWrite();
      instance.clearScope();
      return this;
    }
    /**
     * <code>string scope = 4;</code>
     * @param value The bytes for scope to set.
     * @return This builder for chaining.
     */
    public Builder setScopeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setScopeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.UserTokenRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.UserTokenRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "code_",
            "grantType_",
            "refreshToken_",
            "scope_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.UserTokenRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.UserTokenRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.UserTokenRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.UserTokenRequest)
  private static final com.pocketcasts.service.api.UserTokenRequest DEFAULT_INSTANCE;
  static {
    UserTokenRequest defaultInstance = new UserTokenRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserTokenRequest.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.UserTokenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserTokenRequest> PARSER;

  public static com.google.protobuf.Parser<UserTokenRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

