// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.service.api

@kotlin.jvm.JvmName("-initializeuserResetPasswordRequest")
public inline fun userResetPasswordRequest(block: com.pocketcasts.service.api.UserResetPasswordRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.UserResetPasswordRequest =
    com.pocketcasts.service.api.UserResetPasswordRequestKt.Dsl._create(com.pocketcasts.service.api.UserResetPasswordRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `api.UserResetPasswordRequest`
 */
public object UserResetPasswordRequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.service.api.UserResetPasswordRequest.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.service.api.UserResetPasswordRequest.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.service.api.UserResetPasswordRequest = _builder.build()

        /**
         * `string reset_password_token = 1;`
         */
        public var resetPasswordToken: kotlin.String
            @JvmName("getResetPasswordToken")
            get() = _builder.getResetPasswordToken()
            @JvmName("setResetPasswordToken")
            set(value) {
                _builder.setResetPasswordToken(value)
            }
        /**
         * `string reset_password_token = 1;`
         */
        public fun clearResetPasswordToken() {
            _builder.clearResetPasswordToken()
        }

        /**
         * `string password = 2;`
         */
        public var password: kotlin.String
            @JvmName("getPassword")
            get() = _builder.getPassword()
            @JvmName("setPassword")
            set(value) {
                _builder.setPassword(value)
            }
        /**
         * `string password = 2;`
         */
        public fun clearPassword() {
            _builder.clearPassword()
        }

        /**
         * `string scope = 3;`
         */
        public var scope: kotlin.String
            @JvmName("getScope")
            get() = _builder.getScope()
            @JvmName("setScope")
            set(value) {
                _builder.setScope(value)
            }
        /**
         * `string scope = 3;`
         */
        public fun clearScope() {
            _builder.clearScope()
        }
    }
}
public inline fun com.pocketcasts.service.api.UserResetPasswordRequest.copy(block: com.pocketcasts.service.api.UserResetPasswordRequestKt.Dsl.() -> kotlin.Unit): com.pocketcasts.service.api.UserResetPasswordRequest =
    com.pocketcasts.service.api.UserResetPasswordRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
