// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

public interface UserAuthorizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UserAuthorizeRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string response_type = 3;</code>
   * @return The responseType.
   */
  java.lang.String getResponseType();
  /**
   * <code>string response_type = 3;</code>
   * @return The bytes for responseType.
   */
  com.google.protobuf.ByteString
      getResponseTypeBytes();

  /**
   * <code>string client_id = 4;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 4;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string redirect_uri = 5;</code>
   * @return The redirectUri.
   */
  java.lang.String getRedirectUri();
  /**
   * <code>string redirect_uri = 5;</code>
   * @return The bytes for redirectUri.
   */
  com.google.protobuf.ByteString
      getRedirectUriBytes();

  /**
   * <code>string scope = 6;</code>
   * @return The scope.
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 6;</code>
   * @return The bytes for scope.
   */
  com.google.protobuf.ByteString
      getScopeBytes();

  /**
   * <code>string state = 7;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 7;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
