// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.pocketcasts.service.api;

/**
 * Protobuf type {@code api.UserPodcastResponse}
 */
public  final class UserPodcastResponse extends
    com.google.protobuf.GeneratedMessageLite<
        UserPodcastResponse, UserPodcastResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:api.UserPodcastResponse)
    UserPodcastResponseOrBuilder {
  private UserPodcastResponse() {
    uuid_ = "";
    title_ = "";
    author_ = "";
    description_ = "";
    url_ = "";
    lastEpisodeUuid_ = "";
  }
  public static final int UUID_FIELD_NUMBER = 1;
  private java.lang.String uuid_;
  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    return uuid_;
  }
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uuid_);
  }
  /**
   * <code>string uuid = 1;</code>
   * @param value The uuid to set.
   */
  private void setUuid(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    uuid_ = value;
  }
  /**
   * <code>string uuid = 1;</code>
   */
  private void clearUuid() {

    uuid_ = getDefaultInstance().getUuid();
  }
  /**
   * <code>string uuid = 1;</code>
   * @param value The bytes for uuid to set.
   */
  private void setUuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uuid_ = value.toStringUtf8();

  }

  public static final int EPISODES_SORT_ORDER_FIELD_NUMBER = 2;
  private int episodesSortOrder_;
  /**
   * <code>int32 episodes_sort_order = 2;</code>
   * @return The episodesSortOrder.
   */
  @java.lang.Override
  public int getEpisodesSortOrder() {
    return episodesSortOrder_;
  }
  /**
   * <code>int32 episodes_sort_order = 2;</code>
   * @param value The episodesSortOrder to set.
   */
  private void setEpisodesSortOrder(int value) {
    
    episodesSortOrder_ = value;
  }
  /**
   * <code>int32 episodes_sort_order = 2;</code>
   */
  private void clearEpisodesSortOrder() {

    episodesSortOrder_ = 0;
  }

  public static final int AUTO_START_FROM_FIELD_NUMBER = 3;
  private int autoStartFrom_;
  /**
   * <code>int32 auto_start_from = 3;</code>
   * @return The autoStartFrom.
   */
  @java.lang.Override
  public int getAutoStartFrom() {
    return autoStartFrom_;
  }
  /**
   * <code>int32 auto_start_from = 3;</code>
   * @param value The autoStartFrom to set.
   */
  private void setAutoStartFrom(int value) {
    
    autoStartFrom_ = value;
  }
  /**
   * <code>int32 auto_start_from = 3;</code>
   */
  private void clearAutoStartFrom() {

    autoStartFrom_ = 0;
  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private java.lang.String title_;
  /**
   * <code>string title = 4;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 4;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 4;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <code>string title = 4;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 4;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int AUTHOR_FIELD_NUMBER = 5;
  private java.lang.String author_;
  /**
   * <code>string author = 5;</code>
   * @return The author.
   */
  @java.lang.Override
  public java.lang.String getAuthor() {
    return author_;
  }
  /**
   * <code>string author = 5;</code>
   * @return The bytes for author.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(author_);
  }
  /**
   * <code>string author = 5;</code>
   * @param value The author to set.
   */
  private void setAuthor(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    author_ = value;
  }
  /**
   * <code>string author = 5;</code>
   */
  private void clearAuthor() {

    author_ = getDefaultInstance().getAuthor();
  }
  /**
   * <code>string author = 5;</code>
   * @param value The bytes for author to set.
   */
  private void setAuthorBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    author_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 6;
  private java.lang.String description_;
  /**
   * <code>string description = 6;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 6;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 6;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 6;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int URL_FIELD_NUMBER = 7;
  private java.lang.String url_;
  /**
   * <code>string url = 7;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <code>string url = 7;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <code>string url = 7;</code>
   * @param value The url to set.
   */
  private void setUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    url_ = value;
  }
  /**
   * <code>string url = 7;</code>
   */
  private void clearUrl() {

    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <code>string url = 7;</code>
   * @param value The bytes for url to set.
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    url_ = value.toStringUtf8();

  }

  public static final int LAST_EPISODE_PUBLISHED_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp lastEpisodePublished_;
  /**
   * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
   */
  @java.lang.Override
  public boolean hasLastEpisodePublished() {
    return lastEpisodePublished_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastEpisodePublished() {
    return lastEpisodePublished_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastEpisodePublished_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
   */
  private void setLastEpisodePublished(com.google.protobuf.Timestamp value) {
    value.getClass();
  lastEpisodePublished_ = value;

    }
  /**
   * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLastEpisodePublished(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (lastEpisodePublished_ != null &&
        lastEpisodePublished_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      lastEpisodePublished_ =
        com.google.protobuf.Timestamp.newBuilder(lastEpisodePublished_).mergeFrom(value).buildPartial();
    } else {
      lastEpisodePublished_ = value;
    }

  }
  /**
   * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
   */
  private void clearLastEpisodePublished() {  lastEpisodePublished_ = null;

  }

  public static final int UNPLAYED_FIELD_NUMBER = 9;
  private boolean unplayed_;
  /**
   * <code>bool unplayed = 9;</code>
   * @return The unplayed.
   */
  @java.lang.Override
  public boolean getUnplayed() {
    return unplayed_;
  }
  /**
   * <code>bool unplayed = 9;</code>
   * @param value The unplayed to set.
   */
  private void setUnplayed(boolean value) {
    
    unplayed_ = value;
  }
  /**
   * <code>bool unplayed = 9;</code>
   */
  private void clearUnplayed() {

    unplayed_ = false;
  }

  public static final int LAST_EPISODE_UUID_FIELD_NUMBER = 10;
  private java.lang.String lastEpisodeUuid_;
  /**
   * <code>string last_episode_uuid = 10;</code>
   * @return The lastEpisodeUuid.
   */
  @java.lang.Override
  public java.lang.String getLastEpisodeUuid() {
    return lastEpisodeUuid_;
  }
  /**
   * <code>string last_episode_uuid = 10;</code>
   * @return The bytes for lastEpisodeUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastEpisodeUuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lastEpisodeUuid_);
  }
  /**
   * <code>string last_episode_uuid = 10;</code>
   * @param value The lastEpisodeUuid to set.
   */
  private void setLastEpisodeUuid(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    lastEpisodeUuid_ = value;
  }
  /**
   * <code>string last_episode_uuid = 10;</code>
   */
  private void clearLastEpisodeUuid() {

    lastEpisodeUuid_ = getDefaultInstance().getLastEpisodeUuid();
  }
  /**
   * <code>string last_episode_uuid = 10;</code>
   * @param value The bytes for lastEpisodeUuid to set.
   */
  private void setLastEpisodeUuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lastEpisodeUuid_ = value.toStringUtf8();

  }

  public static final int LAST_EPISODE_PLAYING_STATUS_FIELD_NUMBER = 11;
  private int lastEpisodePlayingStatus_;
  /**
   * <code>int32 last_episode_playing_status = 11;</code>
   * @return The lastEpisodePlayingStatus.
   */
  @java.lang.Override
  public int getLastEpisodePlayingStatus() {
    return lastEpisodePlayingStatus_;
  }
  /**
   * <code>int32 last_episode_playing_status = 11;</code>
   * @param value The lastEpisodePlayingStatus to set.
   */
  private void setLastEpisodePlayingStatus(int value) {
    
    lastEpisodePlayingStatus_ = value;
  }
  /**
   * <code>int32 last_episode_playing_status = 11;</code>
   */
  private void clearLastEpisodePlayingStatus() {

    lastEpisodePlayingStatus_ = 0;
  }

  public static final int LAST_EPISODE_ARCHIVED_FIELD_NUMBER = 12;
  private boolean lastEpisodeArchived_;
  /**
   * <code>bool last_episode_archived = 12;</code>
   * @return The lastEpisodeArchived.
   */
  @java.lang.Override
  public boolean getLastEpisodeArchived() {
    return lastEpisodeArchived_;
  }
  /**
   * <code>bool last_episode_archived = 12;</code>
   * @param value The lastEpisodeArchived to set.
   */
  private void setLastEpisodeArchived(boolean value) {
    
    lastEpisodeArchived_ = value;
  }
  /**
   * <code>bool last_episode_archived = 12;</code>
   */
  private void clearLastEpisodeArchived() {

    lastEpisodeArchived_ = false;
  }

  public static final int AUTO_SKIP_LAST_FIELD_NUMBER = 13;
  private int autoSkipLast_;
  /**
   * <code>int32 auto_skip_last = 13;</code>
   * @return The autoSkipLast.
   */
  @java.lang.Override
  public int getAutoSkipLast() {
    return autoSkipLast_;
  }
  /**
   * <code>int32 auto_skip_last = 13;</code>
   * @param value The autoSkipLast to set.
   */
  private void setAutoSkipLast(int value) {
    
    autoSkipLast_ = value;
  }
  /**
   * <code>int32 auto_skip_last = 13;</code>
   */
  private void clearAutoSkipLast() {

    autoSkipLast_ = 0;
  }

  public static final int FOLDER_UUID_FIELD_NUMBER = 14;
  private com.google.protobuf.StringValue folderUuid_;
  /**
   * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
   */
  @java.lang.Override
  public boolean hasFolderUuid() {
    return folderUuid_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getFolderUuid() {
    return folderUuid_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : folderUuid_;
  }
  /**
   * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
   */
  private void setFolderUuid(com.google.protobuf.StringValue value) {
    value.getClass();
  folderUuid_ = value;

    }
  /**
   * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeFolderUuid(com.google.protobuf.StringValue value) {
    value.getClass();
  if (folderUuid_ != null &&
        folderUuid_ != com.google.protobuf.StringValue.getDefaultInstance()) {
      folderUuid_ =
        com.google.protobuf.StringValue.newBuilder(folderUuid_).mergeFrom(value).buildPartial();
    } else {
      folderUuid_ = value;
    }

  }
  /**
   * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
   */
  private void clearFolderUuid() {  folderUuid_ = null;

  }

  public static final int SORT_POSITION_FIELD_NUMBER = 15;
  private com.google.protobuf.Int32Value sortPosition_;
  /**
   * <code>.google.protobuf.Int32Value sort_position = 15;</code>
   */
  @java.lang.Override
  public boolean hasSortPosition() {
    return sortPosition_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value sort_position = 15;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getSortPosition() {
    return sortPosition_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : sortPosition_;
  }
  /**
   * <code>.google.protobuf.Int32Value sort_position = 15;</code>
   */
  private void setSortPosition(com.google.protobuf.Int32Value value) {
    value.getClass();
  sortPosition_ = value;

    }
  /**
   * <code>.google.protobuf.Int32Value sort_position = 15;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSortPosition(com.google.protobuf.Int32Value value) {
    value.getClass();
  if (sortPosition_ != null &&
        sortPosition_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
      sortPosition_ =
        com.google.protobuf.Int32Value.newBuilder(sortPosition_).mergeFrom(value).buildPartial();
    } else {
      sortPosition_ = value;
    }

  }
  /**
   * <code>.google.protobuf.Int32Value sort_position = 15;</code>
   */
  private void clearSortPosition() {  sortPosition_ = null;

  }

  public static final int DATE_ADDED_FIELD_NUMBER = 16;
  private com.google.protobuf.Timestamp dateAdded_;
  /**
   * <code>.google.protobuf.Timestamp date_added = 16;</code>
   */
  @java.lang.Override
  public boolean hasDateAdded() {
    return dateAdded_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp date_added = 16;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDateAdded() {
    return dateAdded_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateAdded_;
  }
  /**
   * <code>.google.protobuf.Timestamp date_added = 16;</code>
   */
  private void setDateAdded(com.google.protobuf.Timestamp value) {
    value.getClass();
  dateAdded_ = value;

    }
  /**
   * <code>.google.protobuf.Timestamp date_added = 16;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDateAdded(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (dateAdded_ != null &&
        dateAdded_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      dateAdded_ =
        com.google.protobuf.Timestamp.newBuilder(dateAdded_).mergeFrom(value).buildPartial();
    } else {
      dateAdded_ = value;
    }

  }
  /**
   * <code>.google.protobuf.Timestamp date_added = 16;</code>
   */
  private void clearDateAdded() {  dateAdded_ = null;

  }

  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.pocketcasts.service.api.UserPodcastResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.pocketcasts.service.api.UserPodcastResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.pocketcasts.service.api.UserPodcastResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.pocketcasts.service.api.UserPodcastResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code api.UserPodcastResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.pocketcasts.service.api.UserPodcastResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:api.UserPodcastResponse)
      com.pocketcasts.service.api.UserPodcastResponseOrBuilder {
    // Construct using com.pocketcasts.service.api.UserPodcastResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      return instance.getUuid();
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      return instance.getUuidBytes();
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setUuid(value);
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      copyOnWrite();
      instance.clearUuid();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUuidBytes(value);
      return this;
    }

    /**
     * <code>int32 episodes_sort_order = 2;</code>
     * @return The episodesSortOrder.
     */
    @java.lang.Override
    public int getEpisodesSortOrder() {
      return instance.getEpisodesSortOrder();
    }
    /**
     * <code>int32 episodes_sort_order = 2;</code>
     * @param value The episodesSortOrder to set.
     * @return This builder for chaining.
     */
    public Builder setEpisodesSortOrder(int value) {
      copyOnWrite();
      instance.setEpisodesSortOrder(value);
      return this;
    }
    /**
     * <code>int32 episodes_sort_order = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpisodesSortOrder() {
      copyOnWrite();
      instance.clearEpisodesSortOrder();
      return this;
    }

    /**
     * <code>int32 auto_start_from = 3;</code>
     * @return The autoStartFrom.
     */
    @java.lang.Override
    public int getAutoStartFrom() {
      return instance.getAutoStartFrom();
    }
    /**
     * <code>int32 auto_start_from = 3;</code>
     * @param value The autoStartFrom to set.
     * @return This builder for chaining.
     */
    public Builder setAutoStartFrom(int value) {
      copyOnWrite();
      instance.setAutoStartFrom(value);
      return this;
    }
    /**
     * <code>int32 auto_start_from = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoStartFrom() {
      copyOnWrite();
      instance.clearAutoStartFrom();
      return this;
    }

    /**
     * <code>string title = 4;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 4;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 4;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string author = 5;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      return instance.getAuthor();
    }
    /**
     * <code>string author = 5;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      return instance.getAuthorBytes();
    }
    /**
     * <code>string author = 5;</code>
     * @param value The author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthor(
        java.lang.String value) {
      copyOnWrite();
      instance.setAuthor(value);
      return this;
    }
    /**
     * <code>string author = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthor() {
      copyOnWrite();
      instance.clearAuthor();
      return this;
    }
    /**
     * <code>string author = 5;</code>
     * @param value The bytes for author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAuthorBytes(value);
      return this;
    }

    /**
     * <code>string description = 6;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 6;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 6;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 6;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>string url = 7;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <code>string url = 7;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <code>string url = 7;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <code>string url = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <code>string url = 7;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    @java.lang.Override
    public boolean hasLastEpisodePublished() {
      return instance.hasLastEpisodePublished();
    }
    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastEpisodePublished() {
      return instance.getLastEpisodePublished();
    }
    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    public Builder setLastEpisodePublished(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setLastEpisodePublished(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    public Builder setLastEpisodePublished(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setLastEpisodePublished(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    public Builder mergeLastEpisodePublished(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeLastEpisodePublished(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_episode_published = 8;</code>
     */
    public Builder clearLastEpisodePublished() {  copyOnWrite();
      instance.clearLastEpisodePublished();
      return this;
    }

    /**
     * <code>bool unplayed = 9;</code>
     * @return The unplayed.
     */
    @java.lang.Override
    public boolean getUnplayed() {
      return instance.getUnplayed();
    }
    /**
     * <code>bool unplayed = 9;</code>
     * @param value The unplayed to set.
     * @return This builder for chaining.
     */
    public Builder setUnplayed(boolean value) {
      copyOnWrite();
      instance.setUnplayed(value);
      return this;
    }
    /**
     * <code>bool unplayed = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnplayed() {
      copyOnWrite();
      instance.clearUnplayed();
      return this;
    }

    /**
     * <code>string last_episode_uuid = 10;</code>
     * @return The lastEpisodeUuid.
     */
    @java.lang.Override
    public java.lang.String getLastEpisodeUuid() {
      return instance.getLastEpisodeUuid();
    }
    /**
     * <code>string last_episode_uuid = 10;</code>
     * @return The bytes for lastEpisodeUuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastEpisodeUuidBytes() {
      return instance.getLastEpisodeUuidBytes();
    }
    /**
     * <code>string last_episode_uuid = 10;</code>
     * @param value The lastEpisodeUuid to set.
     * @return This builder for chaining.
     */
    public Builder setLastEpisodeUuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setLastEpisodeUuid(value);
      return this;
    }
    /**
     * <code>string last_episode_uuid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastEpisodeUuid() {
      copyOnWrite();
      instance.clearLastEpisodeUuid();
      return this;
    }
    /**
     * <code>string last_episode_uuid = 10;</code>
     * @param value The bytes for lastEpisodeUuid to set.
     * @return This builder for chaining.
     */
    public Builder setLastEpisodeUuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLastEpisodeUuidBytes(value);
      return this;
    }

    /**
     * <code>int32 last_episode_playing_status = 11;</code>
     * @return The lastEpisodePlayingStatus.
     */
    @java.lang.Override
    public int getLastEpisodePlayingStatus() {
      return instance.getLastEpisodePlayingStatus();
    }
    /**
     * <code>int32 last_episode_playing_status = 11;</code>
     * @param value The lastEpisodePlayingStatus to set.
     * @return This builder for chaining.
     */
    public Builder setLastEpisodePlayingStatus(int value) {
      copyOnWrite();
      instance.setLastEpisodePlayingStatus(value);
      return this;
    }
    /**
     * <code>int32 last_episode_playing_status = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastEpisodePlayingStatus() {
      copyOnWrite();
      instance.clearLastEpisodePlayingStatus();
      return this;
    }

    /**
     * <code>bool last_episode_archived = 12;</code>
     * @return The lastEpisodeArchived.
     */
    @java.lang.Override
    public boolean getLastEpisodeArchived() {
      return instance.getLastEpisodeArchived();
    }
    /**
     * <code>bool last_episode_archived = 12;</code>
     * @param value The lastEpisodeArchived to set.
     * @return This builder for chaining.
     */
    public Builder setLastEpisodeArchived(boolean value) {
      copyOnWrite();
      instance.setLastEpisodeArchived(value);
      return this;
    }
    /**
     * <code>bool last_episode_archived = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastEpisodeArchived() {
      copyOnWrite();
      instance.clearLastEpisodeArchived();
      return this;
    }

    /**
     * <code>int32 auto_skip_last = 13;</code>
     * @return The autoSkipLast.
     */
    @java.lang.Override
    public int getAutoSkipLast() {
      return instance.getAutoSkipLast();
    }
    /**
     * <code>int32 auto_skip_last = 13;</code>
     * @param value The autoSkipLast to set.
     * @return This builder for chaining.
     */
    public Builder setAutoSkipLast(int value) {
      copyOnWrite();
      instance.setAutoSkipLast(value);
      return this;
    }
    /**
     * <code>int32 auto_skip_last = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoSkipLast() {
      copyOnWrite();
      instance.clearAutoSkipLast();
      return this;
    }

    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    @java.lang.Override
    public boolean hasFolderUuid() {
      return instance.hasFolderUuid();
    }
    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getFolderUuid() {
      return instance.getFolderUuid();
    }
    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    public Builder setFolderUuid(com.google.protobuf.StringValue value) {
      copyOnWrite();
      instance.setFolderUuid(value);
      return this;
      }
    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    public Builder setFolderUuid(
        com.google.protobuf.StringValue.Builder builderForValue) {
      copyOnWrite();
      instance.setFolderUuid(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    public Builder mergeFolderUuid(com.google.protobuf.StringValue value) {
      copyOnWrite();
      instance.mergeFolderUuid(value);
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue folder_uuid = 14;</code>
     */
    public Builder clearFolderUuid() {  copyOnWrite();
      instance.clearFolderUuid();
      return this;
    }

    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    @java.lang.Override
    public boolean hasSortPosition() {
      return instance.hasSortPosition();
    }
    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int32Value getSortPosition() {
      return instance.getSortPosition();
    }
    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    public Builder setSortPosition(com.google.protobuf.Int32Value value) {
      copyOnWrite();
      instance.setSortPosition(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    public Builder setSortPosition(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      copyOnWrite();
      instance.setSortPosition(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    public Builder mergeSortPosition(com.google.protobuf.Int32Value value) {
      copyOnWrite();
      instance.mergeSortPosition(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value sort_position = 15;</code>
     */
    public Builder clearSortPosition() {  copyOnWrite();
      instance.clearSortPosition();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    @java.lang.Override
    public boolean hasDateAdded() {
      return instance.hasDateAdded();
    }
    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDateAdded() {
      return instance.getDateAdded();
    }
    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    public Builder setDateAdded(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setDateAdded(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    public Builder setDateAdded(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setDateAdded(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    public Builder mergeDateAdded(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeDateAdded(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_added = 16;</code>
     */
    public Builder clearDateAdded() {  copyOnWrite();
      instance.clearDateAdded();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.UserPodcastResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.pocketcasts.service.api.UserPodcastResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "uuid_",
            "episodesSortOrder_",
            "autoStartFrom_",
            "title_",
            "author_",
            "description_",
            "url_",
            "lastEpisodePublished_",
            "unplayed_",
            "lastEpisodeUuid_",
            "lastEpisodePlayingStatus_",
            "lastEpisodeArchived_",
            "autoSkipLast_",
            "folderUuid_",
            "sortPosition_",
            "dateAdded_",
          };
          java.lang.String info =
              "\u0000\u0010\u0000\u0000\u0001\u0010\u0010\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\u0004\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\t\t\u0007\n\u0208" +
              "\u000b\u0004\f\u0007\r\u0004\u000e\t\u000f\t\u0010\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.pocketcasts.service.api.UserPodcastResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.pocketcasts.service.api.UserPodcastResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.pocketcasts.service.api.UserPodcastResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:api.UserPodcastResponse)
  private static final com.pocketcasts.service.api.UserPodcastResponse DEFAULT_INSTANCE;
  static {
    UserPodcastResponse defaultInstance = new UserPodcastResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserPodcastResponse.class, defaultInstance);
  }

  public static com.pocketcasts.service.api.UserPodcastResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserPodcastResponse> PARSER;

  public static com.google.protobuf.Parser<UserPodcastResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

