// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.pocketcasts.files.data;

public interface FileUploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:files.FileUploadRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int64 size = 3;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>string contentType = 4;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string contentType = 4;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>int64 duration = 5;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>.google.protobuf.Int32Value colour = 6;</code>
   * @return Whether the colour field is set.
   */
  boolean hasColour();
  /**
   * <code>.google.protobuf.Int32Value colour = 6;</code>
   * @return The colour.
   */
  com.google.protobuf.Int32Value getColour();

  /**
   * <code>bool hasCustomImage = 7;</code>
   * @return The hasCustomImage.
   */
  boolean getHasCustomImage();
}
