// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.pocketcasts.files.data;

public interface FileDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:files.FileDeleteResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
