// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: files.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pocketcasts.files.data

@kotlin.jvm.JvmName("-initializefileUploadResponse")
public inline fun fileUploadResponse(block: com.pocketcasts.files.data.FileUploadResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.files.data.FileUploadResponse =
    com.pocketcasts.files.data.FileUploadResponseKt.Dsl._create(com.pocketcasts.files.data.FileUploadResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `files.FileUploadResponse`
 */
public object FileUploadResponseKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.pocketcasts.files.data.FileUploadResponse.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.pocketcasts.files.data.FileUploadResponse.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.pocketcasts.files.data.FileUploadResponse = _builder.build()

        /**
         * `string uuid = 1;`
         */
        public var uuid: kotlin.String
            @JvmName("getUuid")
            get() = _builder.getUuid()
            @JvmName("setUuid")
            set(value) {
                _builder.setUuid(value)
            }
        /**
         * `string uuid = 1;`
         */
        public fun clearUuid() {
            _builder.clearUuid()
        }

        /**
         * `string url = 2;`
         */
        public var url: kotlin.String
            @JvmName("getUrl")
            get() = _builder.getUrl()
            @JvmName("setUrl")
            set(value) {
                _builder.setUrl(value)
            }
        /**
         * `string url = 2;`
         */
        public fun clearUrl() {
            _builder.clearUrl()
        }
    }
}
public inline fun com.pocketcasts.files.data.FileUploadResponse.copy(block: com.pocketcasts.files.data.FileUploadResponseKt.Dsl.() -> kotlin.Unit): com.pocketcasts.files.data.FileUploadResponse =
    com.pocketcasts.files.data.FileUploadResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
