// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.pocketcasts.files.data;

public interface FileDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:files.FileDeleteRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
