// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.pocketcasts.files.data;

public interface ImageUploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:files.ImageUploadRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>string contentType = 3;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string contentType = 3;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();
}
